
import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class GaneshGte112024ImageList {
imageRoot = 'assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/';
public allImageList:ImageElement[]  =  [
  {  
            folder:'ganesh-gte-11-2024',
            theme:'<theme>',
            themeSummary: '',
files: [
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  '03-11-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 4 March 11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-4-Mar11-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 4 March 11 2025 </li><li> 4th of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 11 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '03-11-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 3 March 11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-3-Mar11-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 3 March 11 2025 </li><li> 3rd of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 11 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color pencil, charcoal pencil, metal color pencil',
dateUploaded:  '03-04-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 2 March 4 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-2-Mar4-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 2 March 4 2025 </li><li> 2nd of 8 Ganesh with musical instruments - Tanpura </li><li> Base template copied from B&W </li><li> Completion and upload March 4 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color pencil, charcoal pencil, metal color pencil',
dateUploaded:  '03-04-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 1 March 4 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-1-Mar4-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 1 March 4 2025 </li><li> 1st of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 4 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '03-04-2025',
duplicate:  'true',
evolution:  `<b>First charcoal sketch <br/></B>`,
evolutionSequence:  5,
evolutionDate:  '03-04-2025',
summaryLabel:  `Ganesh using Charcoal pencils March 3 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Ganesh-Charcoal-March-3-2025.jpeg`,
description: `<ul><li> Ganesh using Charcoal pencils March 3 2025 </li><li> Using Kalour Hard, Medium and Soft black, and white charcoal pencils </li><li> These pencils were gifted by my wife long back and I finally got down to using them  </li><li> Uploaded March 4 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '02-17-2025',
duplicate:  'true',
evolution:  `<b>first metal color drawing<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-17-2025',
summaryLabel:  `Ganesh Metal Gold color pencil Feb 17 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-metal-gold-pencil-Feb17-2025.jpeg`,
description: `<ul><li> Ganesh Metal Gold color pencil Feb 17 2025 </li><li> Using 'Kalour' metal pencil Gold shade </li><li> based on a Brass Ganesh Idol I've had since engineering days </li><li> Upload feb 17 itself </li></ul>`,
rating:  1,
ratingYear:  2025,
},
{
canvassMaterial:  'other',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '02-13-2025',
duplicate:  'true',
evolution:  `<b>print out of an original hard copy and a processed soft copy next to each other<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-13-2025',
summaryLabel:  `Ganesh Reverse Color(3) Original & Processed Feb06-2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-Reverse-Shade-Orig+ProcessedFeb06-2025.jpeg`,
description: `<ul><li> Ganesh Reverse Color(3) Original & Processed Feb06-2025 </li><li> Felt it best to 'collage' the original and processed </li><li> This goes a little tangential in this list by placing two separate images next to each other. But felt the need to </li><li> uploaded Feb 13 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '02-13-2025',
duplicate:  'true',
evolution:  `<b>Reverse color processed. Unique where this image is not a collage but actually processed. Also a print out of a soft copy <br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-13-2025',
summaryLabel:  `Ganesh Reverse color (2) Processed Green Feb 6 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-Reverse-Shade-Processed-Green-Feb06-2025.jpeg`,
description: `<ul><li> Ganesh Reverse color (2) Processed Green Feb 6 2025 </li><li> See 'Ganesh Reverse color (1) Red Feb 6 2025'  </li><li> This is the same image, run through an image processing tool to invert the colors </li><li> Uploaded Feb 13 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  '02-13-2025',
duplicate:  'true',
evolution:  `<b>The description says it all. (See the next = before or after sketch also)<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-13-2025',
summaryLabel:  `Ganesh Reverse color Red Feb 6 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-Reverse-Shade-Red-Feb06-2025.jpeg`,
description: `<ul><li> Ganesh Reverse color Red Feb 6 2025 </li><li> Tried to create a 'negative print' effect here </li><li> normal bright areas are shaded dark and, normally dark areas are not colored or shaded light </li><li> Next (either after or before) is this image processed to reverse the colors </li></ul>`,
rating:  1,
ratingYear:  2025,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '01-16-2025',
duplicate:  'true',
summaryLabel:  `Ganesh Tan color pencil Jan 16 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/GaneshTanMonochromeJan162025.jpeg`,
description: `<ul><li> Ganesh Tan color pencil Jan 16 2025 </li><li>hopeful sandalwood look</li><li> 'Templatized' off an earlier color pencil sketch </li><li> completion AND upload 01/16/2025 </li></ul>`,
},
  {
    canvassMaterial:  'Plain paper',
    canvassSize:  '',
    content:  'color-pencil',
    dateUploaded:  '01-07-2025',
    duplicate:  'true',
    summaryLabel:  `Ganesh Color Monochrome Jan 2 2025`,
    fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/GaneshRedOrangeJan22025.jpeg`,
    description: `<ul><li> Ganesh Color Monochrome Jan 2 2025 </li><li> Start of a new series shades and shines color </li><li> Using red orange color pencil </li></ul>`,
    },
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'true',
summaryLabel:  `Baby Ganesh on Swing Nov 19 2024`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BalGaneshNov192024.jpeg`,
description: `<ul><li> 'Bal Ganesh Jhula' (tongue in cheek on Laxman Jhula)</li><li>Baby Ganesh on Swing Nov 19 2024 </li><li> The 1st  </li><li> So this initial sketch in this series </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '11-18-2024',
duplicate:  'false',
evolution:  `Testing almost complete automation of new image list and menu update`,
evolutionSequence:  4,
evolutionDate:  '11-18-2024',
summaryLabel:  `Ganesh Sankashti Chaturthi Nov 18 2024`,
fullFileName: `${this.imageRoot}GaneshSankashtiChaturthiNov182024.jpeg`,
description: `<ul><li> Ganesh Sankashti Chaturthi Nov 18 2024 </li><li> This also happened to be a Monday </li><li> drawing finish and upload same day  </li></ul>`,
rating:  1,
ratingYear:  2024,
},
  ]}]}
