 import {  ImageElement } from '@settings-and-models/image-detail'
// /Users/Shantanu/Documents/GitHub/cms-sources/journey-of-drawings/src/${this.imageRoot}Ganesh-1-March1723.jpeg
export class MostRecentlyUploadedImageList {
 sort: string = 'asc'
 imageRoot=`assets/gallery-files/images/religion/aumkar-shree-ganesh/gte-q1-2024/` ;
public allImageList:ImageElement[]  =  [
   { 
        folder:'shree-ganesh-gte-q1-2024',
        theme:'Shree Ganesh',
        themeSummary:
        `Lord Ganesh, remover of Obstacles. Vigneshwar, Aumkar, Gamapati, Vignahartha - Compilation of sketches Q1 2024 onward. *INCLUDING WATER COLOR SKETCHES`,
        files: [ 
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:29:22 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Aruna (Anurag's wife) DOB MM/DD 10/03 complete 10/04/2025 -> Oct 16 `,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Aruna-Birthday-Oct3-belated-2025.jpeg`,
description: `<ul><li>Aruna (Anurag's wife) DOB MM/DD 10/03 complete 10/04/2025 -> Oct 16 </li>
  <li> Aruna is the wife of Anurag very close friend since RAIT engineering </li><li>Falooda concept in Greeting since she loves ice cream </li><li>VIDAMs is Vijay Pawar, Diwakar Menon(Murali), Anurag and Mohan (who is not with us since 2002), lower case 's' is Shantanu - me </li>
  <li>'Snohal' is tongue in cheek by Shridhar Ranganathan also from RAIT combo of Snehal and Sonal</li>
  <li>Note - the words ARUNA - they are generated by ChatGPT
  <li>Birthday was Oct 3, card was made Oct 4, uploaded Oct 16 2025</li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:39:13 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Samadhi Anniv (Gregorian) Oct 15 2025 (1918) -> Oct 16 `,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Baba-Samadhi-Gregorian-for-Oct15-2025.jpeg`,
description: `<ul><li> Baba Samadhi Anniv (Gregorian) Oct 15 2025 (1918) -> Oct 16  </li><li> Sai took Samadhi on Dassera Day 1918 which was Oct 15, Tuesday </li><li> Uploaded Oct 16 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:29:22 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Santosh Manjrekar MM/DD 09/28 2025 - Oct 16`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SISL-Santosh-Birthday-09282025.png`,
description: `<ul><li> Santosh Manjrekar MM/DD 09/28 2025 - Oct 16 </li><li> Santosh is an ex colleague from SISL </li><li> He is a great enthusiast of planes and flies small planes (of the kind shown) </li><li> Also likes the high life, party, and a carnivore </li><li> His wife Teju, also ex SISL is a vegan ;)  </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 08:07:38 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Tribute to IAF Mig21 last flight 26 Sept 2025 drawing 1, 09/27-10/16`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Mig21-farewell-tribute-Sept27-2025.jpeg`,
description: `<ul><li> Tribute to IAF Mig21 last flight 26 Sept 2025 drawing 1, 09/27-10/16 </li><li> A tribute to the Mig21 which was  backbone to Indian Air Force and had its last flight 26 Sept 2025. </li><li> 63 years of service </li><li> This is a soft copy made from two original sketches showing 2 mig 21's and a mig 29 </li><li> compiled and completed Sept 27, uploaded Oct 16 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Thu Oct 16 2025 07:44:14 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Karva Chauth 2025 Ganesh from Sept 2024`,
fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/Ganesh-divine-09-13-25-2-Oct925-Oct16.jpeg`,album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 27} ,
description: `<ul><li> Karva Chauth 2025 Ganesh from Sept 2024 </li><li> Updated the 'hard copy' final sketch of my sarvajanik idol sequence of Sept 13 2025 </li><li> Added Durva, background, etc </li><li> Completed Oct 9 over the existing (Sept 13 2025) and uploaded Oct 13 </li><li>Note: This makes its way to the album 'Divine in colors so fine' BUT I expect insert: a print out of the earlier version AND insert the Diwali Laxmi Narayan sketch before</li></ul>`,
},

{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Thu Oct 02 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Dassera special 2025 Oct 1 - 3 2025. Sanskrit Prayer to Maa Saraswati`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/VijayDashmiSaraswatiPrayer-Oct1-Oct2-2025.jpeg`,
description: `<ul>
<li>Dassera special 2025 Oct 1 - 3 2025. Sanskrit Prayer to Maa Saraswati</li>
  <li>(The words mean something like this:)<br/><br/>
          <ul>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like a lotus may the mind open with learning and enlightenment.</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like a lotus may the mind bloom with creativity spreading beautiful pure and innocent art</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Like the lotus thrives even in mud, to practise these in any time</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like a swan, pure, simple, white elegant, yet distinguishing milk from water</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Like the swan gliding over water without getting its feathers wet, a calmness to reach my divine goal </li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My devotion carry these O veena pustak dharini</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Offer my prayers at your lotus feet Maa Saraswati</li>
            <li><b>***** HAPPY VIJAYADASHMI ********</li></ul><br/>(My composition, thought I'd make it extra special by translating to Sanskrit)
    </li>
    <li> Upload Oct 2-3 2025 </li></ul>`,
},{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  'Thu Oct 02 2025 11:10:00 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Kishore Kumar Birthday.. Bhimsen Tribute Scene - 08/08 - Oct 2 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/Bhimsen-Kishore-Trbute-Aug8-Oct2-2025.jpeg`,
description: `<ul><li> Kishore Kumar Birthday.. Bhimsen Tribute Scene - 08/08 - Oct 2 2025 </li><li> A hallmark of artists true to their passion, humble, down to earth, grounded Attempt to capture how legendary classical singer Bharat Ratna Pt Bhimsen Joshi was enamored by  Kishore Kumar's voice and singing ability esp Amar Prem songs </li><li> Complete on Aug8  in celebration of Kishore Da birth anniversary Aug 4 2025 </li><li> Uploaded Oct 2 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  'Thu Oct 02 2025 10:37:38 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Typical Battle of Britain Scene Complete 09/20 Upl 10/02/2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BattleOfBritain-Sept20-Oct-2-2025.jpeg`,
description: `<ul><li> Typical Battle of Britain Scene Complete 09/20 Upl 10/02/2025 </li><li> Actually an enhancement of a previous sketch </li><li> Attempt to show a bombing raid by Heinkel He-111 with Me-109 escorts being attacked by Spitfires </li><li> Enhancement completed Sept 20, uploaded Oct 2 2025 </li></ul>`,
},
                {
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '10-02-2025',
duplicate:  'true',
summaryLabel:  `Baba Dassera 2025 - Oct 1- 2 2025`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2025-q1-2026/Baba-Dassera-Oct1-Oct2-2025.jpeg`,
description: `<ul><li> Special sketch for Baba Samadhi using metallic and othe color pencils</li><li> Uploaded Oct 2 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Thu Aug 28 2025 22:47:07 Indian Standard Time',

album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 0} ,
duplicate:  'true',
summaryLabel:  `Home Ganapati Sept 30 - Oct 2 2025`,
fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/HomeGanapatiSept30-Oct2-2025.jpeg`,
description: `<ul>
        <li>An appropriate first for a physical album ('The Divine in Colors So Fine') = our 'Home Ganapati' </li>
         <li>Started around Ganesh Chaturthi 2025 time 1st version was released then.  </li>
         <li>Completed Sept 30 2025, detailing with new Silver metallic pencil and <b> trying out fluorescent color pencils (see attempt to draw lights around main piC)<b></li>
         <li>Uploaded Oct 2 2025</li>
       </ul>`,
},

{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Mon Sep 29 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Tushar Pradhan SISL ex colleague Birthday Sept 24`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Falooda-Tushar-Birthday-Sept24-29-2025.jpeg`,
description: `<ul><li>Tushar Pradhan SISL ex colleague Birthday Sept 24</li><li> Upload Sept 29 2025 </li></ul>`,
},
              
{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Mon Sep 29 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Aparna Abhyankar RAIT mate birthday Sept 16`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Falooda-Aparna-Birthday-Sept16-29-2025.jpeg`,
description: `<ul><li> Aparna Abhyankar RAIT mate birthday Sept 16 </li><li> I affectionately call her Guru Maiyya </li><li> Upload Sept 29 2025 </li></ul>`,
},            
{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Mon Sep 29 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Aparna Abhyankar RAIT mate birthday Sept 16`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Falooda-Aparna-Birthday-Sept16-29-2025.jpeg`,
description: `<ul><li> Aparna Abhyankar RAIT mate birthday Sept 16 </li><li> I affectionately call her Guru Maiyya </li><li> Upload Sept 29 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',
dateUploaded:  'Sun Sep 28 2025 15:17:40 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Swami, Datta Sai Chatgpt 09/18 - 9/28/2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SwamiDattaSaiSept172025-chatGPT-pasteback-final.jpeg`,
description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> FINAL VERSION (Step 4 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> 2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> 3. Asked ChatGPT to extend the background  </li><li> 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>`,
iterations: [
{fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SwamiDattaSaiSept172025-chatGPT-pasteback-final.jpeg`, description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> FINAL VERSION (Step 4 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> 2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> 3. Asked ChatGPT to extend the background  </li><li> 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>` },
{fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SwamiDattaSaiSept172025-rawl.jpeg`, description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> Initial RAW VERSION (Step 1 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> (next)2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> (next)3. Asked ChatGPT to extend the background  </li><li> (last) 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>` },
{fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SwamiDattaSaiSept172025-chatGPT-background.png`, description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> CHATGPT VERSION (Step 3 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> (next)2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> (next)3. Asked ChatGPT to extend the background  </li><li> (last) 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>` },
]
},{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '09/11/2025Thu Sep 11 2025 11:03:15 GMT-0700 (Pacific Daylight Time)',

duplicate:  'true',
summaryLabel:  `Baba and Bajrangbali Sept 11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Baba-Bajrangbali-0911-2025.jpg`,
description: `<ul><li>Baba and Bajrangbali compiled and uploaded Sept 11 2025</li></ul>`,
       },  {
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '09/11/2025Thu Sep 11 2025 11:02:34 GMT-0700 (Pacific Daylight Time)',

duplicate:  'true',
summaryLabel:  `A tribute to 4th std Class teacher Ms. Dandekar Sept 10-11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/MsDandekarThanksCardSept10-11-2025.jpeg`,
description: `<ul><li>Ms Dandekar was my class teacher in school in the 4th std which was the only year I stood 1st in class</li><li> A couple of our alumni were to visit her Sept 11 lunch time (IST) so was inspired to create this</li><li> My second tribute to a school teacher after Mr Rodricks our Art teacher</ul>`,
       },
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  'Wed Sep 10 2025 23:03:04 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Sai Doing Ganesh Visarjan complete: Sept 28 2023 upload: Sept 10 2025`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2023/SaiAnantChaturdashi-092823-091025.jpeg`,
description: `<ul><li> Sai Doing Ganesh Visarjan complete: Sept 28 2023 upload: Sept 10 2025 </li></ul>`,
},{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '09/01/2025',

duplicate:  'true',
summaryLabel:  `Carnival Legend cruise to Ensenada Gratitude soft copy Sept 1 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/CarnivalLegendEnsenada4-SC-thanksSep125.jpeg`,

description: `<ul><li>Soft copy gratitude</li><li> Carnival Legend cruise to Ensenada July, (Aug18/19-2025) </li><li> Our very first cruise!!! Carnival Legend SFO-Ensenada(Baja Mexico)-SFO </li><li> Sail 17th afternoon, dock one day - all day Ensenada 19th.. Return 21st Morning </li><li> A *MUST DO* for complete rest and fooding </li><li> Completed Aug 18, upload Aug 19 </li></ul>`,
       },
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Aug 28 2025 22:47:07 Indian Standard Time',

duplicate:  'true',
summaryLabel:  `Gurus with Shree Ganesh Aug 28 2025, Ganesh Chaturthu`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Sai-Ganesh-Chaturthi-Aug27-28.jpeg`,
description: `<ul><li>Collage of Ganesh, with Gurus compiled and uploaded Aug 28 2025</li>
        </ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Wed Aug 27 2025 7:47:07 Indian Standard Time',

duplicate:  'true',
summaryLabel:  `Shripad Vallabh Parayan Aug 27 2025, Ganesh Chaturthu`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Guru-Ganesh-Chaturthi-Aug27.jpeg`,
description: `<ul><li>Collage of Ganesh, Datta and Shripad Vallabh compiled and uploaded Aug 27 2025</li>
        <li>as part of my chapter read (49th) of Shripad Vallabh charitamrutam</li></ul>`,
},{
canvassMaterial:  'Plain paper',
canvassSize:  'A3',
content:  'color-pencil',
dateUploaded:  'Tue Aug 19 2025 22:46:24 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Carnival Legend cruise to Ensenada July, (Aug18/19-2025)`,
fullFileName: `assets/gallery-files/images/transports-and-machines/machines-others/planes-ships-cars-2/CarnivalLegendEnsenada4July19-Aug18-2025.jpeg`,
description: `<ul><li> Carnival Legend cruise to Ensenada July, (Aug18/19-2025) </li><li> Our very first cruise!!! Carnival Legend SFO-Ensenada(Baja Mexico)-SFO </li><li> Sail 17th afternoon, dock one day - all day Ensenada 19th.. Return 21st Morning </li><li> A *MUST DO* for complete rest and fooding </li><li> Completed Aug 18, upload Aug 19 color pencils + charcoal </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A3',
content:  'color pencils + charcoal',
dateUploaded:  'Tue Aug 19 2025 19:31:06 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `India 79th Independence Day Theme Aug 15 - Aug 19 2025`,
fullFileName: `assets/gallery-files/images/themes-misc/India79thIndependenceDay-Aug15-18-2025.jpeg`,
description: `<ul><li> India 79th Independence Day Theme Aug 15 - Aug 19 2025 </li><li> My August 15 theme.. Made in India  centered around Atal Setu - Nhava Sheva end.. Dhruv Helicopter.. At the top, center right is a sort of Independence Day 'mela' with floats of Vande Bharat, PSLV3, Mumbai Sealink  etc. </li><li> Complete Aug 15, uploaded Aug 19 2025 </li></ul>`,
},
 
{ // /Users/shantanug/Documents/GitHub/cms-code/customized-cms/cms-main/src/assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/BabaFeetAug1-2025-Upload-AUg13.jpeg
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  'Wed Aug 13 2025 19:28:25 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Sai Sitting on Stone,. position of hands and legs - Aug 1 - 13 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/BabaFeetAug1-2025-Upload-AUg13.jpeg`,
description: `<ul><li> Sai Sitting on Stone,. position of hands and legs - Aug 1 - 13 2025 </li><li> The significance of Baba's fingers over His toe in sitting posture is profound. It symbolizes that if one wishes to see His Light, they should be ego-less and humble, meditating on His toe through the opening between the two branches. This posture reflects a state of awareness and connection to the divine, emphasizing the importance of humility and meditation in spiritual practice.  </li><li> Completed Aug 1 - uploaded Aug 13 2025 </li><li> Shading pencils and Charcoal </li></ul>`,
},{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Aug 13 2025 12:07:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Wife Uncle Deepak 75th Birthday August 13 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/DeepakKakaBirthdayAug13-2025.jpeg`,
description: `<ul><li>Deepak Rele is my wife's paternal Uncle, who lives in CBD Navi Mumbai (date of this upload)</li>
<li> 75th (platinum) Birthday </li><li> Created and Uploaded Aug 13 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  'Sat Aug 09 2025 10:11:04 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Kargil War Vijay Din July26 (complete Aug1) 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/VijayDinJuly26-CompAug1.jpeg`,
description: `<ul><li> Kargil War Vijay Din July26 (complete Aug1) 2025 </li><li> Symbolic celebration of Victory at Kargil July 26 1999 </li><li> Photo of  victorious Indian Army at Tololing, a pivotal battle  </li><li> ('victory above the clouds') </li><li> The cylinders at either side, at the bottom are empty artillery shells </li><li> Color pencils with Charcoal finish </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Aug 08 2025 19:13:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Sai ChaturMaas compilation Aug8-2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SaiChaturMaasAug8-2025.jpeg`,
description: `<ul><li> Sai ChaturMaas compilation Aug8-2025 </li><li> Compilation of Shirdi Sai sketches across Chaturmass (4 months)  </li><li> Four lunar months, Ashadh, Shravan, Bhadrapad, and Ashwin, or four solar months, starting from Shravana to Kartika.  </li><li> Vithal Ashadh, Shiv + Rakee - Shravan, Ganesh - Bhadrapadh, Ramayan Ashwin, Baba lighting Lamps - Karthik </li><li> compiled and uploaded Aug 8 2025 (Aug 7 Thu, Aug 8 Raksha Bandhan) </li></ul>`,
},

{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Fri Aug 08 2025 19:00:32 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba 2022 --> 2025 RakshaBandan`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2022/BabaAug112022-RakshaBandan-NrliPnima.jpeg`,
description: `<ul><li> Baba 2022 --> 2025 RakshaBandan </li><li> This sketch of Baba wearing Rakhee (Raksha Bandan), having 'Narali Bhaat' (coconut rice) and sea with coconut trees background ('Narali Poornima') was  completed Aug 11 2022, Raskha Bandan THEN  </li><li> uploaded August 8 2025 Raksha Bandan </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Jul 25 2025 10:41:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Samadhi to Masjid July 24-25 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/BabaSamadhiToMAshidJuly242025.jpeg`,
description: `<ul><li> Baba Samadhi to Masjid July 24-25 2025 </li><li> Collage of two paper sketches (unless requested) soft copy only </li><li> "समाधि उथ्रोनिया गुरु चला मशीदी कड़े " Part of Baba Kakad arti line - come from Samadhi and go to the Masjid (Dwarkamai) </li><li> compiled July 24, upload July 25, 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  'Fri Jul 25 2025 10:32:45 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `MV Chidambaram SCI Chennai<->Singapore/Penang`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/MVChidambaramJuly24-2025.jpeg`,
description: `<ul><li> MV Chidambaram SCI Chennai<->Singapore/Penang </li><li> MV Chidambaram was owned by  Shipping Corporation of India(SCI). This liner was originally the M.V. Pasteur and was build in Dunkerque, France. It was sold to the Indian government in 1972. </li><li> Service started 1972, she used to ply the route from Madras to Penang, Port Klang and Singapore, then back again to Madras.  </li><li> Unfortunately ended abruptly 1985 when she caught fire and was decommissioned shortly after </li><li> Drawing completed July 24, uploaded July 25, 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  'Wed Jul 23 2025 00:53:30 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Konkan S** Steamship Mumbai Panjim July22-23 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/KonkanS---SteamshipMumbaiPanjimJuly232025.jpeg`,
description: `<ul><li> Konkan S** Steamship Mumbai Panjim July22-23 2025 </li><li> There used to be a  steamship service between Mumbai and Panjim in the 70s and the 80s.<br/> I traveled by this steamer service once in 1975. My dad had gotten transferred to Goa, Vasco and we decided to travel by the steamer.  Konkan Sevak, Konkan Shakti, - Sarita (not sure if this was renamed Konkan Shakti) and one or two more </li><li>  It was a fantastic and very pleasant journey including a sighting of a dolphin/porpoise that I remember vividly  </li><li> I've captured this <a href="https://art-is-worship.web.app/view/places-scenes-objects">in this list</a> scroll to the bottom </li><li> Completed using regular 4B pencil around July 21, but refreshed with charcoals and uploaded july 23 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A3',
content:  '',
dateUploaded:  'Mon Jul 14 2025 06:48:15 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Gurupoornima 2025 Samadhi Mandir`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/Baba-Gurupoornima-11x17-A4-july10-25.jpeg`,
description: `<ul><li> Baba Gurupoornima 2025 Samadhi Mandir </li><li> Completed a previous unfinished sketch </li><li> Gurupoornima was Thu July 10 2025 </li><li> (Changers 2025 qualifier) to add to the physical album 'The Divine in colors so fine' an A4 copy was made  </li><li> another ground breaker.. allow multiple physical albums if the original list is only a soft copy list like this one </li><li> Uploaded July 14 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  '',
dateUploaded:  'Sun Jul 13 2025 21:31:10 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Vari Symbolic July4, 13 2026`,
fullFileName: `assets/gallery-files/images/religion/laxmi-vishnu-hanuman/Vari-July-4-2025.jpeg`,
description: `<ul><li> Vari Symbolic July4, 13 2026 </li><li> Ashadi Ekadahi being July 6 this year, Varis(Sacred Pilgrimages) leave from different parts of Maharashtra to end at Pandharpur before this date  </li><li> Symbolic of 'Bhagwa' flags, Paduka Palkhi top, and Vithal Rakhumabai in the top left minature  </li><li> Completed July 4, uploaded July 13 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  'Sun Jul 13 2025 15:26:54 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Vari July 3, 13 2025`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/Baba-Vari-July3-2025.jpeg`,
description: `<ul><li> Baba Vari July 3, 13 2025 </li><li> Ashadi Ekadahi being July 6 this year, Varis(Sacred Pilgrimages) leave from different parts of Maharashtra to end at Pandharpur before this date  </li><li> Symbolic of Baba carrying the 'Bhagwa' flag and Vithal Rakhumabai in the top left minature </li><li> Completed July 3, uploaded July 13 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  '',
dateUploaded:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>Comemorating fresh Parayan of Unabridged Sai SatCharit Thu June 26<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Sai Satcharit Chapt1 June 26-27 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/BabaSatCharit1NewParayanJun262025.jpeg`,
description: `<ul><li> Sai Satcharit Chapt1 June 26-27 2025 </li><li> Sai Satcharit Chapt1 .. Hemadpant who (physically) wrote the script pays obeisance to Shree Ganesh, Maa Saraswati, and the 'Guru' which I depict as Lord Datta, then the main story of Baba grinding wheat to keep away the cholera epidemic </li><li> A collage from previous drawings..  </li><li> Compiled June 26 late evening, uploaded just post midnight June 27 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Fri Jun 27 2025 00:06:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>Commemorative of one of the most disruptive events in  Cricket History<br/>Giving the 'underdog' the power of belief that they can win, make it their day<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Fri Jun 27 2025 00:06:07 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Prudential World Cup Oct 23 - June 25`,
fullFileName: `assets/gallery-files/images/places-scenes-objects/PrudentialCup83-Oct1723-June262025.jpeg`,
description: `<ul><li> Prudential World Cup Oct 23 - June 25 </li><li> The Cricketing World was stunned on JUne 25 1983, when the Indian Cricket Team lead by Kapil Dev won the One Day World Cup at Lords England </li><li> Cup shown with a red cricket ball. India defeated West Indies to lift the cup.. a 'nothing short of a miracle event' </li><li> Originally completed Oct 17 2023 - when the latest edition of the World Cup was going on (India, lost the finals, unfortunately, to Australia) </li><li> This was shared on June 25 2025 as a 42nd anniversary commemorative </li><li> Uploaded Midnight June 27 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>A first with the Deity combination<br/>The 1st upload using one click add to 'Most Recent  Uploads' and 'Changers' (2025)<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Ganesh Shiv Hanuman, June 24-26 2025 `,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/GaneshShivHanumanJune24-26-2025.jpeg`,
description: `<ul><li> Ganesh Shiv Hanuman, June 24-26 2025  </li><li> Towards the end of the Jyesth Lunar Month </li><li> Showing Ganesh ji doing milk Abhishek to Shivling and Hanuman ji waiting for His turn </li><li> Showing a 'not waste' concept of the milk being collected from the Shivling </li><li> Completed June 24, uploaded June 26 2025 </li></ul>`,
},
         
         
         {
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '06-14-2025',
duplicate:  'true',
summaryLabel:  `Father's day special Jun 15 2025. Upload Same day`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/FathersDay2025.jpeg`, 
description: `<ul><li>Father's day special Jun 15 2025. Upload Same day</li><li>Shirdi Sai from Dec 2021 to my flower vase template</li></ul>`
} ,{
canvassMaterial: 'Plain paper',
canvassSize: 'A4',
content: 'black-white',
dateUploaded: 'Sat Jun 14 2025 17:34:45 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `DDayJune122025 Upload June 14`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/DDayJune122025Shades1Complete.jpeg`,
description: `<ul><li> DDayJune122025 Upload June 14 </li><li> A belated commemorative of one of several game changing events of WW2 - D Day June 6 1944 The ship numbers on the LCTs are a (tongue in cheek) reference and tribute to the 82nd and 101st airborne: for their significant contributions to D-Day </li></ul>`,
},{
canvassMaterial: 'Plain paper',
canvassSize: '',
content: 'black-white',
dateUploaded: 'Sat Jun 14 2025 17:28:45 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `Rafi June12 2025 Upload June 14`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/RafiJUne122025Shades1Complete.jpeg`,
description: `<ul><li> Rafi June12 2025 Upload June 14 </li><li> Mohammed Rafi, Legendary Playback singer </li><li> December 24, 1924, Kotla Sultan Singh, India </li><li> Died July 31, 1980 </li><li> Actually the sketch was completed Dec 24 ish 2024 </li><li> But it needed some work which I finally got down to doin June 2025 </li></ul>`,
},{
canvassMaterial: 'Plain paper',
canvassSize: 'A4',
content: 'color-pencil',
dateUploaded: 'Sat Jun 14 2025 17:21:55 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true', roles: ["guru"],
summaryLabel: `Baba June12 2025 - June 14 upload`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/BabaJune122025Complete.jpeg`,
description: `<ul><li> Baba June12 2025 - June 14 upload </li><li> Baba Shirdi Murthy Idol with attempt of Milpitas throne backgrpund </li><li> Gray color pencil. Made decision of not to add to the special list since it wasnt up to the mark </li></ul>`,
},{
canvassMaterial: 'Plain paper',
canvassSize: '',
content: 'soft',contentOther: 'charcoal and shading',
dateUploaded: 'Sat Jun 14 2025 17:09:27 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `Jag Pradakshina Jun10,25 Charcoal1 Upload Jun14`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/JagPradakshinaJun102025Charcoal1Complete.jpeg`,
description: `<ul><li> Jag Pradakshina Jun10,25 Charcoal1 Upload Jun14 </li><li> Mahadev had a contest where the God would get special status who completed 'Pradakshina' (clockwise religious circumambulation ) fastest of the World </li><li> Shree Ganesh showed His wisdom by doing Pradakshina of His parents who mean the wordl </li></ul>`,
},
           ,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"06-01-2025 18:25","duplicate":"true","summaryLabel":"Baba- Shivling Gray June1 2025 SIXHUNDREDTH","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/BabaShivlingGrayJune12025-SIXHUNDREDTH.jpeg","description":"<ul><li> Baba- Shivling Gray June1 2025 SIXHUNDREDTH </li><li> Celebrating my 600th website uploaded sketch them my beloved Baba and Mahadev </li><li> June 1, 2025 </li></ul>"}
,{"canvassMaterial":"Photo print matt paper","canvassSize":"A4","content":"watercolor-pencil","dateUploaded":"06-01-2025 17:00","duplicate":"true","summaryLabel":"General Sunrise Scene.. March 1 2024, Upload June 1 2025","fullFileName":"assets/gallery-files/images/places-scenes-objects/WCPencilsMar1-2024-June1-2025.jpeg","description":"<ul><li> General Sunrise Scene.. March 1 2024, Upload June 1 2025 </li><li> Watercolor pencils some regular color pencils on matt paper </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"color-pencil","dateUploaded":"06-01-2025 17:00","duplicate":"true","summaryLabel":"Possible Mosquito Bomber Juky 2022/ June 2025","fullFileName":"assets/gallery-files/images/transports-and-machines/machines-others/planes-ships-cars/QuestonableMosquiteJuly2022.jpeg","description":"<ul><li> Possible Mosquito Bomber Juky 2022/ June 2025 </li><li> Completed July 5 2022, upload June 1, 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"06-01-2025 16:30","duplicate":"true","summaryLabel":"Experimental sketch of Cock April 22, June 2025","fullFileName":"assets/gallery-files/images/flora-and-fauna/CockApril20-2022.jpeg","description":"<ul><li> Experimental sketch of Cock April 22, June 2025 </li><li> Shared April 20, 2022, uploaded June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 16:10","duplicate":"true","summaryLabel":"Baba Dec 16 2021 Uploaded June 1 2025","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q3-q4-2021/BabaDec162021.jpeg","description":"<ul><li> Baba Dec 16 2021 Uploaded June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"black-white","dateUploaded":"06-01-2025 16:05","duplicate":"true","summaryLabel":"Baba Nov2022 Upload Jun12025","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2022-q1-2023/BabaNov2022-Jun12025.jpeg","description":"<ul><li> Baba Nov2022 Upload Jun12025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"black-white","dateUploaded":"06-01-2025 14:55","duplicate":"true","summaryLabel":"Atal Bihari Bajpayee Nov2-2023 June1 2025","fullFileName":"assets/gallery-files/images/people-places/AtalBajpayeeNov2-2023-June1-2025.jpeg","description":"<ul><li> Atal Bihari Bajpayee Nov2-2023 June1 2025 </li><li> Atal Bihari Vajpayee[1] (25 December 1924 – 16 August 2018) was an Indian poet, writer and statesman who served as the prime minister of India, first for a term of 13 days in 1996, then for a period of 13 months from 1998 to 1999, followed by a full term from 1999 to 2004 </li><li> Drawing completed Nov 2023, upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 14:50","duplicate":"true","summaryLabel":"Vishwesaraiya 09152023 June12025 ","fullFileName":"assets/gallery-files/images/people-places/Vishwesaraiya-09152023-June12025.jpeg","description":"<ul><li> Vishwesaraiya 09152023 June12025  </li><li> Sir Mokshagundam Visvesvaraya (Moːkśguṇam Viśveśvarayya; 15 September 1861 – 12/14 April 1962),[1][2] also referred to by his initials, MV, was an Indian civil engineer, administrator, and statesman,[3] who served as the 19th Dewan of Mysore from 1912 to 1918.[4]  Visvesvaraya is regarded in India as one of the foremost civil engineers whose birthday, 15 September, is celebrated every year as Engineer's Day in India </li><li> Completed Sep 15. 2023, uploaded June 1 2023 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 14:45","duplicate":"true","summaryLabel":"Famous Musician Bhupen Hazarika 09/23 - 06/25","fullFileName":"assets/gallery-files/images/people-places/BhupenHazarikaSept82023-June1-25.jpeg","description":"<ul><li> Famous Musician Bhupen Hazarika 09/23 - 06/25 </li><li> Known as the Bard of the Brahmaputra, A Bharat Ratna, hailing from Assam he has lot of famous works </li><li> Uploaded June 1 2024</li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 14:40","duplicate":"true","fullFileName":"assets/gallery-files/images/people-places/GilmourNov8-2022-June1-2025.jpeg","summaryLabel":"David Gilmour (Comfortably Numb) Pink Floyd Nov8,'22 Upload June 1 2025","description":"<ul><li> One of the famous 'THE WALL' quartet Waters, Mason, Wright, Gilmour </li>\n<li> He joined in 1967, shortly before the departure of the founder member Syd Barrett.[1] By the early 1980s, Pink Floyd had become one of the highest-selling and most acclaimed acts in music history</li>\n<li>His Guitar solo in \"THE WALL:Comfortably Numb\" is aclaimed to be one of the best lead solos of all time - it was \"an utter master at work, leaving space, repeating and building on licks to give a sense of structure, not overplaying, building to a shrieking climax, and then fading out while leaving the listener wanting more\"</li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"06-01-2025 14:30","duplicate":"true","album":{"name":"the-divine-in-colors-so-fine","status":"added","sequence":15},"summaryLabel":"Swami Samartha June 1 2025","fullFileName":"assets/gallery-files/images/religion/swami-samartha-q2-2023/SwamiJune1-2025.jpeg","description":"<ul><li> Swami Samartha June 1 2025 </li><li> Completion and upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 11:30","duplicate":"true","summaryLabel":"Baba Ardhanareshwar Sept 22, June 1 2025","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2022/BabaArdhanareshwar-ShripadhVallabh-Sept012022.jpeg","description":"<ul><li> Baba Ardhanareshwar Sept 22, June 1 2025 </li><li> Inspired by Chapter from Shripad Vallabh Charit, Baba with Shiva Shakti </li><li> Completed Sept 1 2022, upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","contentOther":"charcoal and shading","dateUploaded":"06-01-2025 11:00","album":{"name":"the-third-album","status":"added","sequence":34},"duplicate":"true","evolution":"<b>The first A3 Charcoal sketch. .. Also inserted a copy in 'Charcoal Times Other Colors Shines'<br/></B>","evolutionSequence":5,"evolutionDate":"06-01-2025","summaryLabel":"Hanuman A3 Charcoal May 31, upload June 1, 2025","fullFileName":"assets/gallery-files/images/religion/laxmi-vishnu-hanuman/HanumanMay31-2025.jpeg","description":"<ul><li> CHANGER: The first A3 Charcoal sketch. .. Also inserted a copy in 'Charcoal Times Other Colors Shines' </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 10:10","duplicate":"true","summaryLabel":"Sambhajiraje Shivaji Son. Punyatithi 05/14/25.. upload June 1 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/SambhajMay14-2025Ounyatithi0June12025.jpeg","description":"<ul><li> Sambhajiraje Shivaji Son. Punyatithi 05/14/25.. upload June 1 2025 </li><li> The legendary son, Sambhaji of Shivaji Raje, the founder of the Maratha Raj  </li><li> Completed for May 14 2025 (the Heir's punyatithi) </li><li> Final touches and upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"black-white","dateUploaded":"06-01-2025 10:05","duplicate":"true","summaryLabel":"Original Baba Samadhi Mandir -- final touch and upload June 1 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BabaSamadhiMandirJun12025.jpeg","description":"<ul><li> Original Baba Samadhi Mandir -- final touch and upload June 1 2025 </li><li> This is what the original Samadhi Mandir looked at Shirdi </li></ul>"}
,{"canvassSize":"","content":"","dateUploaded":"06-01-2025 10:00","duplicate":"true","summaryLabel":"Baba Sketch final touch and upload June 1 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BabaJun12025.jpeg","description":"<ul><li> Baba Sketch final touch and upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Beriev A50 AWAC + SU30 May23-31,2025","fullFileName":"assets/gallery-files/images/transports-and-machines/machines-others/majestic-lifters-legendary-carriers/IL76BerievA50IAFSu30-0523-05312025.jpeg","description":"<ul><li> Beriev A50 AWAC + SU30 May23-31,2025 </li><li> IAF il76 variant Beriev A50 awac with phalcon radar with 2 su30 </li><li> The No. 50 Squadron were raised in 2009 at Agra Airforce Station of the Central Air Command. Beriev A-50 is based on the air-frame of the Ilyushin Il-76 and fitted by Beriev with PS-90A-76 engines and Israeli radar system EL/W-2090(Phalcon) mounted on the aircraft by Israeli company Elta Electronics Industries. </li><li> Completed May23, uploaded May 31 2025 </li><li> Also shown two Sukhoi Su30 as working with this aircraft </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Ishaan, my wife Snehal's nephew June 1 2025 Birthday. Upload Same day","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/IshanBirthday-June1-2025.jpeg","description":"<ul><li>Ishaan, my wife Snehal's nephew June 1 2025 Birthday. Upload Same day</li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Prakash, RAIT 93 Batch May 31 2025 Birthday. Upload Same day","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/PrakashBDayMay31-2025.jpeg","description":"<ul><li>Prakash, RAIT 93 Batch  May 31 2025 Birthday. Upload Same day </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Anurag Mendhekar May 31 2025 Birthday. Upload Same day","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Anurag-Birthday-May31-2025.jpeg","description":"<ul><li>Anurag Mendhekar May 31 2025 Birthday. Upload Same day </li><li> Anurag is a close friend of mine since my Engineering days </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Anurag Mendhekar May 31 2025 Birthday. Upload Same day","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Anurag-Birthday-May31-2025.jpeg","description":"<ul><li>Anurag Mendhekar May 31 2025 Birthday. Upload Same day </li><li> Anurag is a close friend of mine since my Engineering days </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"05-29-2025","duplicate":"true","summaryLabel":"Baba Feb 20 2025","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2024-q1-2025/BabaFeb202025.jpeg","description":"<ul><li> Baba Feb 20 2025 </li><li> Uploaded May 29 2025 </li></ul>"}
         ]
   }
]
}
/*

*/
