 import {  ImageElement } from '@settings-and-models/image-detail'
// /Users/Shantanu/Documents/GitHub/cms-sources/journey-of-drawings/src/${this.imageRoot}Ganesh-1-March1723.jpeg
export class MostRecentlyUploadedImageList {
 sort: string = 'asc'
 imageRoot=`assets/gallery-files/images/religion/aumkar-shree-ganesh/gte-q1-2024/` ;
public allImageList:ImageElement[]  =  [
   { 
        folder:'shree-ganesh-gte-q1-2024',
        theme:'Shree Ganesh',
        themeSummary:
        `Lord Ganesh, remover of Obstacles. Vigneshwar, Aumkar, Gamapati, Vignahartha - Compilation of sketches Q1 2024 onward. *INCLUDING WATER COLOR SKETCHES`,
        files: [
         {
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '06-14-2025',
duplicate:  'true',
summaryLabel:  `Father's day special Jun 15 2025. Upload Same day`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/FathersDay2025.jpeg`, 
description: `<ul><li>Father's day special Jun 15 2025. Upload Same day</li><li>Shirdi Sai from Dec 2021 to my flower vase template</li></ul>`
} ,{
canvassMaterial: 'Plain paper',
canvassSize: 'A4',
content: 'black-white',
dateUploaded: 'Sat Jun 14 2025 17:34:45 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `DDayJune122025 Upload June 14`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/DDayJune122025Shades1Complete.jpeg`,
description: `<ul><li> DDayJune122025 Upload June 14 </li><li> A belated commemorative of one of several game changing events of WW2 - D Day June 6 1944 The ship numbers on the LCTs are a (tongue in cheek) reference and tribute to the 82nd and 101st airborne: for their significant contributions to D-Day </li></ul>`,
},{
canvassMaterial: 'Plain paper',
canvassSize: '',
content: 'black-white',
dateUploaded: 'Sat Jun 14 2025 17:28:45 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `Rafi June12 2025 Upload June 14`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/RafiJUne122025Shades1Complete.jpeg`,
description: `<ul><li> Rafi June12 2025 Upload June 14 </li><li> Mohammed Rafi, Legendary Playback singer </li><li> December 24, 1924, Kotla Sultan Singh, India </li><li> Died July 31, 1980 </li><li> Actually the sketch was completed Dec 24 ish 2024 </li><li> But it needed some work which I finally got down to doin June 2025 </li></ul>`,
},{
canvassMaterial: 'Plain paper',
canvassSize: 'A4',
content: 'color-pencil',
dateUploaded: 'Sat Jun 14 2025 17:21:55 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `Baba June12 2025 - June 14 upload`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/BabaJune122025Complete.jpeg`,
description: `<ul><li> Baba June12 2025 - June 14 upload </li><li> Baba Shirdi Murthy Idol with attempt of Milpitas throne backgrpund </li><li> Gray color pencil. Made decision of not to add to the special list since it wasnt up to the mark </li></ul>`,
},{
canvassMaterial: 'Plain paper',
canvassSize: '',
content: 'soft',contentOther: 'charcoal and shading',
dateUploaded: 'Sat Jun 14 2025 17:09:27 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `Jag Pradakshina Jun10,25 Charcoal1 Upload Jun14`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/JagPradakshinaJun102025Charcoal1Complete.jpeg`,
description: `<ul><li> Jag Pradakshina Jun10,25 Charcoal1 Upload Jun14 </li><li> Mahadev had a contest where the God would get special status who completed 'Pradakshina' (clockwise religious circumambulation ) fastest of the World </li><li> Shree Ganesh showed His wisdom by doing Pradakshina of His parents who mean the wordl </li></ul>`,
},
           ,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"06-01-2025 18:25","duplicate":"true","summaryLabel":"Baba- Shivling Gray June1 2025 SIXHUNDREDTH","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/BabaShivlingGrayJune12025-SIXHUNDREDTH.jpeg","description":"<ul><li> Baba- Shivling Gray June1 2025 SIXHUNDREDTH </li><li> Celebrating my 600th website uploaded sketch them my beloved Baba and Mahadev </li><li> June 1, 2025 </li></ul>"}
,{"canvassMaterial":"Photo print matt paper","canvassSize":"A4","content":"watercolor-pencil","dateUploaded":"06-01-2025 17:00","duplicate":"true","summaryLabel":"General Sunrise Scene.. March 1 2024, Upload June 1 2025","fullFileName":"assets/gallery-files/images/places-scenes-objects/WCPencilsMar1-2024-June1-2025.jpeg","description":"<ul><li> General Sunrise Scene.. March 1 2024, Upload June 1 2025 </li><li> Watercolor pencils some regular color pencils on matt paper </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"color-pencil","dateUploaded":"06-01-2025 17:00","duplicate":"true","summaryLabel":"Possible Mosquito Bomber Juky 2022/ June 2025","fullFileName":"assets/gallery-files/images/transports-and-machines/machines-others/planes-ships-cars/QuestonableMosquiteJuly2022.jpeg","description":"<ul><li> Possible Mosquito Bomber Juky 2022/ June 2025 </li><li> Completed July 5 2022, upload June 1, 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"06-01-2025 16:30","duplicate":"true","summaryLabel":"Experimental sketch of Cock April 22, June 2025","fullFileName":"assets/gallery-files/images/flora-and-fauna/CockApril20-2022.jpeg","description":"<ul><li> Experimental sketch of Cock April 22, June 2025 </li><li> Shared April 20, 2022, uploaded June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 16:10","duplicate":"true","summaryLabel":"Baba Dec 16 2021 Uploaded June 1 2025","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q3-q4-2021/BabaDec162021.jpeg","description":"<ul><li> Baba Dec 16 2021 Uploaded June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"black-white","dateUploaded":"06-01-2025 16:05","duplicate":"true","summaryLabel":"Baba Nov2022 Upload Jun12025","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2022-q1-2023/BabaNov2022-Jun12025.jpeg","description":"<ul><li> Baba Nov2022 Upload Jun12025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"black-white","dateUploaded":"06-01-2025 14:55","duplicate":"true","summaryLabel":"Atal Bihari Bajpayee Nov2-2023 June1 2025","fullFileName":"assets/gallery-files/images/people-places/AtalBajpayeeNov2-2023-June1-2025.jpeg","description":"<ul><li> Atal Bihari Bajpayee Nov2-2023 June1 2025 </li><li> Atal Bihari Vajpayee[1] (25 December 1924 – 16 August 2018) was an Indian poet, writer and statesman who served as the prime minister of India, first for a term of 13 days in 1996, then for a period of 13 months from 1998 to 1999, followed by a full term from 1999 to 2004 </li><li> Drawing completed Nov 2023, upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 14:50","duplicate":"true","summaryLabel":"Vishwesaraiya 09152023 June12025 ","fullFileName":"assets/gallery-files/images/people-places/Vishwesaraiya-09152023-June12025.jpeg","description":"<ul><li> Vishwesaraiya 09152023 June12025  </li><li> Sir Mokshagundam Visvesvaraya (Moːkśguṇam Viśveśvarayya; 15 September 1861 – 12/14 April 1962),[1][2] also referred to by his initials, MV, was an Indian civil engineer, administrator, and statesman,[3] who served as the 19th Dewan of Mysore from 1912 to 1918.[4]  Visvesvaraya is regarded in India as one of the foremost civil engineers whose birthday, 15 September, is celebrated every year as Engineer's Day in India </li><li> Completed Sep 15. 2023, uploaded June 1 2023 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 14:45","duplicate":"true","summaryLabel":"Famous Musician Bhupen Hazarika 09/23 - 06/25","fullFileName":"assets/gallery-files/images/people-places/BhupenHazarikaSept82023-June1-25.jpeg","description":"<ul><li> Famous Musician Bhupen Hazarika 09/23 - 06/25 </li><li> Known as the Bard of the Brahmaputra, A Bharat Ratna, hailing from Assam he has lot of famous works </li><li> Uploaded June 1 2024</li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 14:40","duplicate":"true","fullFileName":"assets/gallery-files/images/people-places/GilmourNov8-2022-June1-2025.jpeg","summaryLabel":"David Gilmour (Comfortably Numb) Pink Floyd Nov8,'22 Upload June 1 2025","description":"<ul><li> One of the famous 'THE WALL' quartet Waters, Mason, Wright, Gilmour </li>\n<li> He joined in 1967, shortly before the departure of the founder member Syd Barrett.[1] By the early 1980s, Pink Floyd had become one of the highest-selling and most acclaimed acts in music history</li>\n<li>His Guitar solo in \"THE WALL:Comfortably Numb\" is aclaimed to be one of the best lead solos of all time - it was \"an utter master at work, leaving space, repeating and building on licks to give a sense of structure, not overplaying, building to a shrieking climax, and then fading out while leaving the listener wanting more\"</li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"06-01-2025 14:30","duplicate":"true","album":{"name":"the-divine-in-colors-so-fine","status":"added","sequence":15},"summaryLabel":"Swami Samartha June 1 2025","fullFileName":"assets/gallery-files/images/religion/swami-samartha-q2-2023/SwamiJune1-2025.jpeg","description":"<ul><li> Swami Samartha June 1 2025 </li><li> Completion and upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 11:30","duplicate":"true","summaryLabel":"Baba Ardhanareshwar Sept 22, June 1 2025","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2022/BabaArdhanareshwar-ShripadhVallabh-Sept012022.jpeg","description":"<ul><li> Baba Ardhanareshwar Sept 22, June 1 2025 </li><li> Inspired by Chapter from Shripad Vallabh Charit, Baba with Shiva Shakti </li><li> Completed Sept 1 2022, upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","contentOther":"charcoal and shading","dateUploaded":"06-01-2025 11:00","album":{"name":"the-third-album","status":"added","sequence":34},"duplicate":"true","evolution":"<b>The first A3 Charcoal sketch. .. Also inserted a copy in 'Charcoal Times Other Colors Shines'<br/></B>","evolutionSequence":5,"evolutionDate":"06-01-2025","summaryLabel":"Hanuman A3 Charcoal May 31, upload June 1, 2025","fullFileName":"assets/gallery-files/images/religion/laxmi-vishnu-hanuman/HanumanMay31-2025.jpeg","description":"<ul><li> CHANGER: The first A3 Charcoal sketch. .. Also inserted a copy in 'Charcoal Times Other Colors Shines' </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"06-01-2025 10:10","duplicate":"true","summaryLabel":"Sambhajiraje Shivaji Son. Punyatithi 05/14/25.. upload June 1 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/SambhajMay14-2025Ounyatithi0June12025.jpeg","description":"<ul><li> Sambhajiraje Shivaji Son. Punyatithi 05/14/25.. upload June 1 2025 </li><li> The legendary son, Sambhaji of Shivaji Raje, the founder of the Maratha Raj  </li><li> Completed for May 14 2025 (the Heir's punyatithi) </li><li> Final touches and upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"black-white","dateUploaded":"06-01-2025 10:05","duplicate":"true","summaryLabel":"Original Baba Samadhi Mandir -- final touch and upload June 1 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BabaSamadhiMandirJun12025.jpeg","description":"<ul><li> Original Baba Samadhi Mandir -- final touch and upload June 1 2025 </li><li> This is what the original Samadhi Mandir looked at Shirdi </li></ul>"}
,{"canvassSize":"","content":"","dateUploaded":"06-01-2025 10:00","duplicate":"true","summaryLabel":"Baba Sketch final touch and upload June 1 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BabaJun12025.jpeg","description":"<ul><li> Baba Sketch final touch and upload June 1 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Beriev A50 AWAC + SU30 May23-31,2025","fullFileName":"assets/gallery-files/images/transports-and-machines/machines-others/majestic-lifters-legendary-carriers/IL76BerievA50IAFSu30-0523-05312025.jpeg","description":"<ul><li> Beriev A50 AWAC + SU30 May23-31,2025 </li><li> IAF il76 variant Beriev A50 awac with phalcon radar with 2 su30 </li><li> The No. 50 Squadron were raised in 2009 at Agra Airforce Station of the Central Air Command. Beriev A-50 is based on the air-frame of the Ilyushin Il-76 and fitted by Beriev with PS-90A-76 engines and Israeli radar system EL/W-2090(Phalcon) mounted on the aircraft by Israeli company Elta Electronics Industries. </li><li> Completed May23, uploaded May 31 2025 </li><li> Also shown two Sukhoi Su30 as working with this aircraft </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Ishaan, my wife Snehal's nephew June 1 2025 Birthday. Upload Same day","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/IshanBirthday-June1-2025.jpeg","description":"<ul><li>Ishaan, my wife Snehal's nephew June 1 2025 Birthday. Upload Same day</li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Prakash, RAIT 93 Batch May 31 2025 Birthday. Upload Same day","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/PrakashBDayMay31-2025.jpeg","description":"<ul><li>Prakash, RAIT 93 Batch  May 31 2025 Birthday. Upload Same day </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Anurag Mendhekar May 31 2025 Birthday. Upload Same day","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Anurag-Birthday-May31-2025.jpeg","description":"<ul><li>Anurag Mendhekar May 31 2025 Birthday. Upload Same day </li><li> Anurag is a close friend of mine since my Engineering days </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"05-31-2025","duplicate":"true","summaryLabel":"Anurag Mendhekar May 31 2025 Birthday. Upload Same day","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Anurag-Birthday-May31-2025.jpeg","description":"<ul><li>Anurag Mendhekar May 31 2025 Birthday. Upload Same day </li><li> Anurag is a close friend of mine since my Engineering days </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"05-29-2025","duplicate":"true","summaryLabel":"Baba Feb 20 2025","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2024-q1-2025/BabaFeb202025.jpeg","description":"<ul><li> Baba Feb 20 2025 </li><li> Uploaded May 29 2025 </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"soft","content":"soft","dateUploaded":"05-29-2025","duplicate":"true","summaryLabel":"The 'Himalayan Geese' An12 and Il76 (Gajraj) planes Jan 9 / May 29 2025","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/HimalayanGeese-Jan9-2025.jpeg","description":"<ul><li> The 'Himalayan Geese' An12 and Il76 (Gajraj) planes Jan 9 / May 29 2025 </li><li> A 'software stitch' of the two (main) aircraft of IAF 44 Squadron, the 'Himalayan Geese' </li><li> Feature Antonov An12 the previous, and 'Gajraj' IL76, the current main aircraft of the squadron </li><li> Upload May 29 2025 </li></ul>"}
,{"canvassMaterial":"Watercolor paper","canvassSize":"A4","content":"soft","dateUploaded":"05-27-2025","duplicate":"true","summaryLabel":"Baba - May 29 2025","album":{"name":"the-divine-in-colors-so-fine","status":"added","sequence":14},"fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/BabaMay28-2025.jpeg","description":"<ul><li> Baba - May 29 2025 </li><li> Sketch started May 1st week, final touches and upload May 29 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"Other","contentOther":"Using color pencil, charcoal pencil, metal color pencil","dateUploaded":"05-02-2025","duplicate":"true","summaryLabel":"INS MUMBAI DELHI Class ship  at MUMBAI May1-2, 2025.jpeg","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Mumbai-Delhi-Mumbai-May1-2-2025.jpeg","description":"<ul><li> INS MUMBAI DELHI Class ship  at MUMBAI May1-2, 2025.jpeg </li><li> INS Mumbai, Indian Navy Guided Missile Destroyer - Delhi class shown at Mumbai Port </li><li> Completed May1 uploaded May 2 2025 </li></ul>"}
,{"canvassMaterial":"Watercolor paper","canvassSize":"A4","content":"watercolor-pencil","dateUploaded":"05-01-2025","duplicate":"true","summaryLabel":"Gallivat 092624 050125 Maharashtra Day 575th ","fullFileName":"assets/gallery-files/images/transports-and-machines/machines-others/planes-ships-cars-2/Gallivat-Sept2624-May125-575th-final.jpeg","description":"<ul><li> Gallivat 092624 050125 Maharashtra Day 575th  </li><li> Timed to upload on May 1st 2025 Labor/Maharashtra Day, and 575th upload </li><li> Gallivat one of the smaller warships (warboat) of the Maratha Navy  </li><li> The Maratha Navy was the naval wing of the armed forces of the Maratha Empire , which existed from around mid-17th century to mid-18th century in the Indian Subcontinent 37 km a day Historian Sir Jadunath Sarkar noted:� “Nothing proves Chhatrapati Shivaji Maharaj's genius as a born statesman more clearly than his creation of a navy and naval bases.” </li><li> Was completed Sept 26, 2024 </li></ul>","rating":1,"ratingYear":2025,"iterations":[{"fullFileName":"assets/gallery-files/images/transports-and-machines/machines-others/planes-ships-cars-2/Gallivat-Sept2624-May125-575th-final.jpeg","description":"<ul><li> Gallivat 092624 050125 Maharashtra Day 575th  </li><li> Timed to upload on May 1st 2025 Labor/Maharashtra Day, and 575th upload </li><li> Gallivat one of the smaller warships (warboat) of the Maratha Navy  </li><li> The Maratha Navy was the naval wing of the armed forces of the Maratha Empire , which existed from around mid-17th century to mid-18th century in the Indian Subcontinent 37 km a day Historian Sir Jadunath Sarkar noted:� “Nothing proves Chhatrapati Shivaji Maharaj's genius as a born statesman more clearly than his creation of a navy and naval bases.” </li><li> Was completed Sept 26, 2024 </li></ul>"},{"fullFileName":"assets/gallery-files/images/transports-and-machines/machines-others/planes-ships-cars-2/Gallivat-Sept2624-May125-575th-final-1.jpeg","description":"<ul><li> Gallivat 092624 050125 Maharashtra Day 575th  </li><li> Timed to upload on May 1st 2025 Labor/Maharashtra Day, and 575th upload </li><li> Gallivat one of the smaller warships (warboat) of the Maratha Navy  </li><li> The Maratha Navy was the naval wing of the armed forces of the Maratha Empire , which existed from around mid-17th century to mid-18th century in the Indian Subcontinent 37 km a day Historian Sir Jadunath Sarkar noted:� “Nothing proves Chhatrapati Shivaji Maharaj's genius as a born statesman more clearly than his creation of a navy and naval bases.” </li><li> Was completed Sept 26, 2024 </li></ul>"}]}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"watercolor-pencil","dateUploaded":"04-30-2025","duplicate":"true","summaryLabel":"Baba March 27 (04/30/2025)","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2024-q1-2025/BabaMarch27-april30-2025.jpeg","description":"<ul><li> Baba March 27 (04/30/2025) </li><li> In Water color pencil, some charcoal touch up </li><li> This was an old unfinished sketch, using white charcoal pencil, I was able to get the 'correction' made </li><li> upload 04/30/2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"color-pencil","dateUploaded":"04-30-2025","duplicate":"true","summaryLabel":"Baba for March 17 St Patricks Day March 20 (04/30/2025)","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2024-q1-2025/Baba-forMarch13-20-StPatricks-April302025.jpeg","description":"<ul><li> Baba for March 17 St Patricks Day March 20 (04/30/2025) </li><li> St Patricks Day, Irish festival has a green color significance </li><li> Shown Baba in this theme. Lord Datta Silhouette on top </li><li> For March 20, upload Apr 30 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"04-30-2025","duplicate":"true","summaryLabel":"Baba Holi theme March13 (28) 04/30/2025Holi","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2024-q1-2025/BabaForMarch13-March28-April30-2025Holi.jpeg","description":"<ul><li> Baba Holi theme March13 (28) 04/30/2025Holi </li><li> Holi, Vishnu had taken Narsimha avatar and killed Hiranyakashyap, during which the lion form used His nails in the killing </li><li> The nails got toxic so Devi Laxmi plunged them into audumbar fruit to remove the poison </li><li> This is sort of based on that, Baba detoxing the lions nails doing the same </li><li> Completed March 28 For March 13, 2025 </li><li> Uploaded April 30 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"","dateUploaded":"04-30-2025","duplicate":"true","summaryLabel":"Baba For Ram Navmi April 5, ---> 30 2025","fullFileName":"assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/BabaRamNavmiApril5-10-29-30-2025.jpeg","description":"<ul><li> Baba For Ram Navmi April 5, ---> 30 2025 </li><li> Milpitas Temple celebrates Ramnavmi in a grand fashion </li><li> Palki procession and devotees hand prints in sandalwood </li><li> Dates: Ramnavmi was April 5, Sketch was for April 10  </li><li> final touches April 29, upload April 30 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"04-30-2025","duplicate":"true","summaryLabel":"USN Phantom Tomcat Hornet Nuclear SuperCarrier Nov 2023( 04/30/25)","fullFileName":"assets/gallery-files/images/transports-and-machines/machines-others/planes-ships-cars-2/USN-planes112023-0425.jpeg","description":"<ul><li> USN Phantom Tomcat Hornet Nuclear SuperCarrier Nov 2023( 04/30/25) </li><li> Showing three iconic US Navy planes down the ages </li><li> From bottom to top - F4 Phantom, F14 Tomcat, F18 Super hornet </li><li> US nuclear supercarrier at lower portion </li><li> Nov 1 2023, upload 04-30-2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"","dateUploaded":"04-30-2025","duplicate":"true","summaryLabel":"Swami Punyatithi 20250425 0429 light brown color","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/SwamiPunyatithi2025Apr25-Apr29.jpeg","description":"<ul><li> Swami Punyatithi 20250425 0429 light brown color </li><li> Started afternoon 2025 April 24, initial share April 25 (Swami Samartha Punyatithi) </li><li> Final touches and share April 29 Akshay Tritiya </li><li> Upload April 30. Light brown color pencil </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"04-30-2025","duplicate":"true","summaryLabel":"Anjali Pathak April 28 Birthday. Upload April 30","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Anjali-2025-Birthday.jpeg","description":"<ul><li> Anjali Pathak April 28 Birthday. Upload April 30 </li><li> Anjali is a close friend of mine since my Engineering days </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"04-30-2025","duplicate":"true","summaryLabel":"Old Bombay Facebook group 7th anniv 27th - 28th ","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/OldBombay7thanniv.jpeg","description":"<ul><li> Old Bombay Facebook group 7th anniv 27th - 28th  </li><li> This is a group which is all about Bombay. </li><li> I submit a large number of sketches here each Friday </li><li> A poem I wrote with the 'card': <br/> <em>&nbsp;&nbsp;This Group is a great INSPIRATION, <br/>&nbsp;&nbsp;&nbsp;&nbsp;Gives me a NEW MOTIVATION <br/>&nbsp;&nbsp;Flow the juices of CREATION, <br/>&nbsp;&nbsp;&nbsp;&nbsp;Coming LATE with my FELICITATION,<br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BLESSED to be in this CELEBRATION!!!</em><br/> </li><li> Created April 28, uploaded April 30 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"","dateUploaded":"04-29-2025","duplicate":"true","summaryLabel":"Lord Datta Metalic gold pencil - April 24 April 29 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/DattaApril24-GoldMetalColorPencil.jpeg","description":"<ul><li> Lord Datta Metalic gold pencil - April 24 April 29 2025 </li><li> Uploaded on Akhsay Tritiya, CA (april 29) this sketch was completed April 24 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"04-23-2025","duplicate":"true","summaryLabel":"WAG12,High Pantograph dedicated freight corrider 04/11 - 04/23/2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/WAG12HighPantographDedicatedFreightCorridor-Apr11-23-2025.jpeg","description":"<ul><li> WAG12,High Pantograph dedicated freight corrider 04/11 - 04/23/2025 </li><li> Featuring symbols of a resurgent India and a modern Indian Railways:<br/> WAG12 MU electric locomotive at 12000 hp one of the most powerful in the world capable of 120 kph<br/> with   high pantograph (unique indigenously developed)<br/>  in one of the dedicated freight corridors ( which are free of passenger traffic and average speeds are high) </li><li> Completed April 11, uploaded and stored April 23, 2025 </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"","content":"soft","contentOther":"Collage","dateUploaded":"04-18-2025","duplicate":"true","evolution":"<b>1st time - soft copy for Baba thursday<br/></B>","evolutionSequence":4,"evolutionDate":"04-18-2025","summaryLabel":"Ganesh Swami Datta Sai Apr 17-18 2025","fullFileName":"assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/GaneshSwamiDattaSai-April172025.jpeg","description":"<ul><li> Ganesh Swami Datta Sai Apr 17-18 2025 </li><li> Since, probably Feb 2021, I've been posting one Baba drawing every Thursday.  This will continue, in general, but it may not be on the Thursday - I'll keep the regularity  The 2nd and more significantly, I am shifting focus on creating more soft copy shares, like this collage.  Partly because I am getting a heap of Baba sketches and finding it difficult to catch up on storing them decently </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","dateUploaded":"04-16-2025","duplicate":"true","summaryLabel":"Second Sangeet Ashtavinayak, 1st with Saraswati Jan 2 24, upload 04/16/2025","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SangeetAshtavinayakMaaSaraswatiJan022025April16-2025.jpeg","description":"<ul><li> Second Sangeet Ashtavinayak, 1st with Saraswati Jan 2 24, upload 04/16/2025 </li><li> The Sangeet Ashtavinayaks with Art college Maa Saraswati idol in center </li><li> completed Jan 2 2024, upload April 16 2025 </li></ul>"}

         ]
   }
]
}
/*

*/