 import {  ImageElement } from '@settings-and-models/image-detail'
// /Users/Shantanu/Documents/GitHub/cms-sources/journey-of-drawings/src/${this.imageRoot}Ganesh-1-March1723.jpeg
export class MostRecentlyUploadedImageList {
 sort: string = 'asc'
 imageRoot=`assets/gallery-files/images/religion/aumkar-shree-ganesh/gte-q1-2024/` ;
public allImageList:ImageElement[]  =  [
   { 
        folder:'shree-ganesh-gte-q1-2024',
        theme:'Shree Ganesh',
        themeSummary:
        `Lord Ganesh, remover of Obstacles. Vigneshwar, Aumkar, Gamapati, Vignahartha - Compilation of sketches Q1 2024 onward. *INCLUDING WATER COLOR SKETCHES`,
        files: [ 
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-crayon',
dateUploaded:  'Tue Apr 28 2026 07:08:12 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `DC3 of Kalinga Air Siang River Arunachal Feb10-26, Apr 28 2026`,
fullFileName: `assets/gallery-files/images/transports-and-machines/machines-others/majestic-lifters-legendary-carriers/Majestic-Carriers-3-DC3-Kalinga-Siangriver-Feb10-26.jpeg`,
description: `<ul><li> DC3 of Kalinga Air Siang River Arunachal Feb10-26, Apr 28 2026 </li><li> DC3 of Kalinga Airlines, founded in 1947 by Biju Patnaik, aviator and former CM of Odisha, over Siang/Brahmaputra, river, Arunachal( North East was one region the Airline used to service ) </li><li> Completed Feb 26, uploaded April 28 2026 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Tue Apr 28 2026 06:50:04 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Anjali Pathak birthday Aprill 28 2026`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SW-Anju-Birthday-Apr28-26.jpeg`,
description: `<ul><li> Anjali Pathak birthday Aprill 28 2026 </li><li> Wishes to one of my closest friends and 'muh boli' sister from RAIT engineering days!! </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Sun Apr 26 2026 23:54:18 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `BritishAirways Airbus 380 over Bay Bridge Jan11-April 26 2026`,
fullFileName: `assets/gallery-files/images/transports-and-machines/machines-others/majestic-lifters-legendary-carriers/Majestic-Carriers-2-BritishAirways-380-BayBridge-Jan11-2026.jpeg`,
description: `<ul><li> BritishAirways Airbus 380 over Bay Bridge Jan11-April 26 2026 </li><li> Bay Bridge Oakland - tongue in cheek showing 4 modes of transport: </li><li> Ships - one carrying rail locomotives, the plane and road traffic on the bridge </li><li> Comp Jan 11, upload Apr 26 2026 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Sun Apr 26 2026 23:48:22 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Air India 787 over Atal Setu Jan10 2026 - Apr 26 26`,
fullFileName: `assets/gallery-files/images/transports-and-machines/machines-others/majestic-lifters-legendary-carriers/Majestic-Carriers-1-787-AI-NewLivery-Atal-Setu-Jan10-2026.jpeg`,
description: `<ul><li> Air India 787 over Atal Setu Jan10 2026 - Apr 26 26 </li><li> 787 Dreamliner showing off the latest (2026) livery of Air India </li><li> Imaginary scene flying over Mumbai-Uran transharbor link Atal Setu </li><li> Completed Jan 10, uploaded April 26 2026 </li></ul>`,
},
{
canvassMaterial:  'Photo print matt paper',
canvassSize:  '',
content:  'watercolor-pencil',
dateUploaded:  'Sun Apr 26 2026 22:19:44 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 34} ,
summaryLabel:  `Baba Water Colors Apr2- 26 2026 `,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2025-q2-2026/Baba-WC-Apr2-26-Divine-34.jpeg`,
description: `<ul><li> Baba Water Colors Apr2- 26 2026  </li><li> Completed April2. Upload Apr 26 2026 </li></ul>`,
},
{
canvassMaterial:  'Photo print matt paper',
canvassSize:  '',
content:  'watercolor-pencil',
dateUploaded:  'Sun Apr 26 2026 16:03:42 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true', album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 32} ,
summaryLabel:  `Swami in Devi roop Nov7 25 Upload Apr 26 2026`,
fullFileName: `assets/gallery-files/images/religion/swami-samartha-q2-2023/Swami-Devi-Nov7-25-Divine-32.jpeg`,
description: `<ul><li> Swami in Devi roop Nov7 25 Upload Apr 26 2026 </li><li> Swami in Devi Roop </li><li> Watercolor pencil completed Nov 7 2025 </li><li> Uploaded Apr 26 2026 </li></ul>`,
},
{
canvassMaterial:  'Photo print matt paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  'Sun Apr 26 2026 15:48:36 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba-Swami-Nov6-25- Upload 4/26/2026`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2025-q2-2026/Baba-Swami-Nov6-25-Divine-31.jpeg`,
description: `<ul><li> Baba-Swami-Nov6-25- Upload 4/26/2026 </li><li> Baba with Swami Silhouette </li><li> Watercolor pencils completed Nov 6 2025 </li><li> upload April 26 2026 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Sun Apr 26 2026 09:21:31 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Ganesh Pastel colors Mum 12/28/25 -> Apr 26 26`,
fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/Divine-33-GaneshMumbai-Dec8-25-pastel-changers.jpeg`,
description: `<ul><li> Ganesh Pastel colors Mum 12/28/25 -> Apr 26 26 </li><li> My first Ganesh pic with  pastel color pencils usage </li><li> Completed Dec 8 2025 during our long Mumbai Trip Nov 15 25 to Jan 7 2026 </li><li> Uploaded April 26 2026 </li></ul>`,
},

{
canvassMaterial:  'other',
canvassSize:  'A4',
content:  '',
dateUploaded:  'Wed Feb 18 2026 23:12:55 GMT-0800 (Pacific Standard Time)',
duplicate:  'true',
summaryLabel:  `787 print give away Nov1425 inflight - 2`,

fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Soft-copy-changers-111425-Ba135-2-Mumbai-2.jpeg`,
description: `<ul><li> 787 print give away Nov1425 inflight .. 2 </li><li> Our trip to India.. this is one of two 787 British Airways drawings I gave to two kids on the flight from London to Mumbai </li><li> UNIQUE (THEREFORE CHANGER) since I have only soft copy AND it was drawn complete in flight </li><li> Nov 14-15 2025, uploaded Feb 18 2026 </li></ul>`,

},
{
canvassMaterial:  'other',
canvassSize:  'A4',
content:  '',
dateUploaded:  'Wed Feb 18 2026 22:37:40 GMT-0800 (Pacific Standard Time)',
duplicate:  'true',
summaryLabel:  `787 print give away Nov1425 inflight - 1`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Soft-copy-changers-111425-Ba135-2-Mumbai-1.jpeg`,
description: `<ul><li> 787 print give away Nov1425 inflight ..1 </li><li> Our trip to India.. this is one of two 787 British Airways drawings I gave to two kids on the flight from London to Mumbai </li><li> UNIQUE (THEREFORE CHANGER) since I have only soft copy AND it was drawn complete in flight </li><li> Nov 14-15 2025, uploaded Feb 18 2026 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  'Wed Feb 18 2026 19:40:33 GMT-0800 (Pacific Standard Time)',
duplicate:  'true',
summaryLabel:  `SLV3 July 18 1980 (Nov 25->Feb 26) `,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/ISRO-SLV3-112125-Mum-alag-shades1.jpeg`,
description: `<ul><li> SLV3 July 18 1980 (Nov 25->Feb 26)  </li><li> ndia's first successful SLV-3 (Satellite Launch Vehicle-3) launch occurred on July 18, 1980, from the Satish Dhawan Space Centre (SHAR). The 4-stage solid-propellant rocket successfully placed the 35-kg Rohini (RS-1) satellite into orbit, making India the sixth nation to achieve indigenous satellite launch </li><li> Sketched in Mumbai complete Nov 21 2025 </li><li> Uploaded Feb 18 2026 </li></ul>`,
},

{
canvassMaterial:  'Photo print matt paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  'Mon Feb 16 2026 00:01:05 GMT-0800 (Pacific Standard Time)',
duplicate:  'true',
summaryLabel:  `Laxmi (Diwali) Oct20-2025 -> Feb17-2026`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Laxmi-Oct20-2025-Feb17-2026.jpeg`,
description: `<ul><li> Laxmi (Diwali) Oct20-2025 -> Feb17-2026 </li><li> Sketched Diwali 2025, uploaded Feb 17 2026 </li><li> Watercolor pencils + charcoal </li></ul>`,
},
{
canvassMaterial:  'Photo print matt paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  'Sun Feb 15 2026 23:16:22 GMT-0800 (Pacific Standard Time)',
duplicate:  'true',
summaryLabel:  `Amol Muzumdar tribute- Harmandar Saheb, Nov 5 2025, Feb 15 2026`,
fullFileName: `assets/gallery-files/images/places-scenes-objects/GuruPUrabNov4-5-2025.jpeg`,
description: `<ul><li> Amol Muzumdar tribute- Harmandar Saheb, Nov 5 2025, Feb 15 2026 </li><li> Sketch of Harmandar Saheb (Golden Temple) </li><li> Wanted to do this for a long time, that too on A3 paper </li><li> Finally got down to A4 and water color pencils </li><li> Completed Nov 5 2025, Upload Feb 15 25 </li><li> Dedicated to Amol Muzumdar, ex cricketer, Achrekar Pupil who never made it big as a player BUT wrote his name in India Cricket History as the coach of the ODI  World cup winning women's team </li></ul>`,
},
,
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  '',
dateUploaded:  'Wed Feb 04 2026 07:04:45 GMT-0800 (Pacific Standard Time)',
duplicate:  'true',
summaryLabel:  `Deepa Naik Nov 2 2026 birthday`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/DeepaNailBirthdayNov2-2025.jpeg`,
description: `<ul><li>Deepa Naik is an RAIT college mate, who is also on a musical whatsapp group fellow member </li>
  <li>Her husband Ravi (also from RAIT) and I worked together abt 1 year at SanDisk</li></ul>`,
},{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  '',
dateUploaded:  'Mon Feb 02 2026 07:04:45 GMT-0800 (Pacific Standard Time)',
duplicate:  'true',
summaryLabel:  `Jan 22 (Ganesh Jayanti)- Feb 2 2026(Gurupratipada) upload`,
fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/Ganesh-Jayanti-Baba-Thu-Jan22-2026.jpeg`,
description: `<ul><li> Jan 22 (Ganesh Jayanti)- Feb 2 2026(Gurupratipada) upload </li><li> soft copy merge of Sai with Ganapati </li><li> Publish after long time...  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Wed Oct 29 2025 23:59:33 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Russian (AirForce?) IL76 Oct29 2025`,
fullFileName: `assets/gallery-files/images/transports-and-machines/machines-others/majestic-lifters-legendary-carriers/Russian-AirForce-possible-IL76-Oct29-2025.jpeg`,
description: `<ul><li> Russian (AirForce?) IL76 Oct29 2025 </li><li> Completed and Uploaded Oct 29 (Oct 30 12:00 AM PST) 2025 </li><li> Color pencils (including metallic) </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Wed Oct 29 2025 19:29:59 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Laxmi Narayan for Diwali Sandhya 2 print 10/12 - 10/29/2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Charcoal-Divine-LaxmiNarayan-Oct12-29-2025.jpeg`,
description: `<ul><li> Laxmi Narayan for Diwali Sandhya 2 print 10/12 - 10/29/2025 </li><li> Oct 19 2025 Manteca Marathi community organized a 'Diwali Sandhya'.. </li><li> This drawing I submitted - made a photo print of 18x24 which itself I edited  </li><li> Note this 'original' looks a bit different from the photo print because of latter 'edits' </li><li> All types of color pencils and charcoal </li><li> Completed around Oct 12 upload Oct 29 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',
dateUploaded:  'Wed Oct 29 2025 19:15:13 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Manteca Diwali Sandhya LaxmiNarayan Photoprint exhibition Oct19-29 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Softcopy-Diwali-Sandhya-LaxmiNarayan-Oct19-282025.jpeg`,
description: `<ul><li> Manteca Diwali Sandhya LaxmiNarayan Photoprint exhibition Oct19-29 2025 </li><li> Oct 19 2025 Marathi community organized a 'Diwali Sandhya'..  </li><li> At Senior Center, I'd made a photo print of a Laxmi Narayan drawing </li><li> However, the original print colors looked very faded  </li><li> To edit/ update, I used sandpaper blocks to roughen the glossiness so I could run pencil and brush over these areas </li><li> There were some gotcha's on the way so I 'threw everything at it' - color-, watercolor-, metallic-, pastel-, charcoal pencils.. Even used crayons  </li><li> Completed Oct 17-18 Uploaded Oct 29 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  'Wed Oct 29 2025 07:40:14 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `IAF Squadron 12 C47 Oct26 29 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Charcoal-lifters-Squad12-C47-Oct26-28-2025.jpeg`,
description: `<ul><li> IAF Squadron 12 C47 Oct26 29 2025 </li><li> Charcoal finish of C47 Dakota attempted livery of IAF No 12 Squadron 'Yaks' </li><li> Commemorative of Infantry Day Oct 27 </li><li> "In October 1947, No. 12 Squadron played a critical role during a pivotal moment for India. With Srinagar on the brink of being overrun and the Banihal Pass impassable, The Yaks stepped in to intervene. Their operations started on October 27, now commemorated as Infantry Day by the Indian Army"  </li><li> Stationed (at least as of 1947) in Agra </li><li> Completed Oc 26, upload Oct 29 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Tue Oct 28 2025 23:23:36 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Lamborghini Aventador LP-780-4 Oct282025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Lamborghini-Aventador-LP-780-4 Ultimae—221MPH-Oct282025.jpeg`,
description: `<ul><li> Lamborghini Aventador LP-780-4 Oct282025 </li><li> Ultimae top speed 221MPH </li><li> start to finish to upload Oct282025.jpeg </li><li> black metallic color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A3',
content:  'color-pencil',
dateUploaded:  'Thu Oct 23 2025 16:40:13 GMT-0700 (Pacific Daylight Time)',album: { name: 'the-fourth-album', status: 'added', sequence: 23},
duplicate:  'true',
summaryLabel:  `IAF Mig21 tribute 3 landmark planes Oct9- 23 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/IAF-Mig21-tribute-3-landmark-charcoalA3-A4-Oct9-2025.jpeg`,
description: `<ul><li> IAF Mig21 tribute 3 landmark planes Oct9- 23 2025 </li><li> Charcoal finish A3 (copy A4 to the charcoal album) </li><li> A tribute to the Mig21 which   backbone to Indian Air Force and had its last flight 26 Sept 2025. </li><li> Attempt to draw 3  versions </li><li> F13 Type 74 - 1963 - the first variant used by IAF  </li><li> FL Type 77 1966 - Longest in service - about 47 years </li><li> Bison - 2001 - the last variant (Note: we had 93rd IAF day on October 8  ) </li><li> complete Oct 9, upload Oct 23 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Thu Oct 23 2025 16:27:12 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Mumbai Diary 400001..BEST.. VT.. Dabba 09/30-10/23/2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Charcoal-Mumbai-Best-VT-Dabba-Sept30-2025.jpeg`,
description: `<ul><li> Mumbai Diary 400001..BEST.. VT.. Dabba 09/30-10/23/2025 </li><li> Charcoal finish three icons in Mumbai Town </li><li> Lifelines and Symbols of Mumbai BEST, (ac bus)  with VT/ CST in the background .. and... dabbas (as in dabbawala) in the foreground </li><li> Completed Sept 30, uploaded Oct 23 2025 </li></ul>`,
},

{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  'Thu Oct 23 2025 16:00:01 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Mumbai Diary 400016..Achrekar memorial Sholay 09/18-10/23/2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Charcoal-Mumbai-ShivajiParkNE-Sholay-Achrekar-Sept18-2025.jpeg`,
description: `<ul><li> Mumbai Diary 400016..Achrekar memorial Sholay 09/18-10/23/2025 </li><li> Charcoal finish showing three icons of Mumbai </li><li> Attempt to draw Ramakant Achrekar Memorial North East Corner of Shivaji Park with a truck carrying 'Sholay' banner </li><li> The Late Achrekar, recipient of Dronacharya award coached the likes of Sachin Tendulkar, Vinod Kambli, Pravin Amre, etc </li><li> Sholay a game changer completed 50 years this year (2025) </li><li> Completed Sept 18, uploaded Oct 23 2025 </li></ul>`,
},{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  'Thu Oct 23 2025 16:13:28 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `WDM1 WDP3 unsung diesel heroes of IR 09/12-10/23/2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/IRs-Unsung-Diesel-Heros-Sept12-Oct23-2025.jpeg`,
description: `<ul><li> WDM1 WDP3 unsung diesel heroes of IR 09/12-10/23/2025 </li><li> Charcoal finish 'Lesser Sung' Workhorses of Indian Railways. </li><li> WDM1 (top) 1957 – mid/late 1990s ... 120 kph </li><li> India’s first mainline diesel-electric locomotive, paving the way for dieselisation, but remembered less than the iconic WDM2 </li><li> ... </li><li> WDP3A (bottom) A high-speed passenger diesel that hauled prestigious trains like the Shatabdi, but never reached the same fame or fleet size as other passenger diesels like the WDP4. Speeds: 160 km/h (trial), ~140–145 km/h in regular service </li><li> Completed Sept 12, uploaded Oct 23 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Wed Oct 22 2025 10:54:37 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba lighting lamps (2) Diwali 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Baba-Diwali-Oct21-22-2025.jpeg`,
description: `<ul><li> Baba lighting lamps (2) Diwali 2025 </li><li> Compiled using merge of another of my drawings with ChatGPT </li><li> Compiled Oct 21 upload Oct 22 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Wed Oct 22 2025 10:44:06 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `JRD Tata photo with AI planes - 93rd anniversary Oct 15 2025 - Oct 22 upload`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/AirIndia-Founder-93-Anniv-Oct15-2025.jpg`,
description: `<ul><li> JRD Tata photo with AI planes - 93rd anniversary Oct 15 2025 - Oct 22 upload </li><li> Photo of Tata in the center with 4 of (what I think I are) lamndmark aircraft and drawn by me </li><li> DC3 - Dakota, Lokheed Super Connie, 707, Emperor Ashoka 747 </li><li> Compiled and shared Oct 15 2025 (93rd anniv) uploaded Oct 22 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:29:22 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Aruna (Anurag's wife) DOB MM/DD 10/03 complete 10/04/2025 -> Oct 16 `,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Aruna-Birthday-Oct3-belated-2025.jpeg`,
description: `<ul><li>Aruna (Anurag's wife) DOB MM/DD 10/03 complete 10/04/2025 -> Oct 16 </li>
  <li> Aruna is the wife of Anurag very close friend since RAIT engineering </li><li>Falooda concept in Greeting since she loves ice cream </li><li>VIDAMs is Vijay Pawar, Diwakar Menon(Murali), Anurag and Mohan (who is not with us since 2002), lower case 's' is Shantanu - me </li>
  <li>'Snohal' is tongue in cheek by Shridhar Ranganathan also from RAIT combo of Snehal and Sonal</li>
  <li>Note - the words ARUNA - they are generated by ChatGPT
  <li>Birthday was Oct 3, card was made Oct 4, uploaded Oct 16 2025</li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:39:13 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Samadhi Anniv (Gregorian) Oct 15 2025 (1918) -> Oct 16 `,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Baba-Samadhi-Gregorian-for-Oct15-2025.jpeg`,
description: `<ul><li> Baba Samadhi Anniv (Gregorian) Oct 15 2025 (1918) -> Oct 16  </li><li> Sai took Samadhi on Dassera Day 1918 which was Oct 15, Tuesday </li><li> Uploaded Oct 16 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:29:22 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Santosh Manjrekar MM/DD 09/28 2025 - Oct 16`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SISL-Santosh-Birthday-09282025.png`,
description: `<ul><li> Santosh Manjrekar MM/DD 09/28 2025 - Oct 16 </li><li> Santosh is an ex colleague from SISL </li><li> He is a great enthusiast of planes and flies small planes (of the kind shown) </li><li> Also likes the high life, party, and a carnivore </li><li> His wife Teju, also ex SISL is a vegan ;)  </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 08:07:38 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Tribute to IAF Mig21 last flight 26 Sept 2025 drawing 1, 09/27-10/16`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Mig21-farewell-tribute-Sept27-2025.jpeg`,
description: `<ul><li> Tribute to IAF Mig21 last flight 26 Sept 2025 drawing 1, 09/27-10/16 </li><li> A tribute to the Mig21 which was  backbone to Indian Air Force and had its last flight 26 Sept 2025. </li><li> 63 years of service </li><li> This is a soft copy made from two original sketches showing 2 mig 21's and a mig 29 </li><li> compiled and completed Sept 27, uploaded Oct 16 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Thu Oct 16 2025 07:44:14 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Karva Chauth 2025 Ganesh from Sept 2024`,
fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/Ganesh-divine-09-13-25-2-Oct925-Oct16.jpeg`,album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 27} ,
description: `<ul><li> Karva Chauth 2025 Ganesh from Sept 2024 </li><li> Updated the 'hard copy' final sketch of my sarvajanik idol sequence of Sept 13 2025 </li><li> Added Durva, background, etc </li><li> Completed Oct 9 over the existing (Sept 13 2025) and uploaded Oct 13 </li><li>Note: This makes its way to the album 'Divine in colors so fine' BUT I expect insert: a print out of the earlier version AND insert the Diwali Laxmi Narayan sketch before</li></ul>`,
},

{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Thu Oct 02 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Dassera special 2025 Oct 1 - 3 2025. Sanskrit Prayer to Maa Saraswati`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/VijayDashmiSaraswatiPrayer-Oct1-Oct2-2025.jpeg`,
description: `<ul>
<li>Dassera special 2025 Oct 1 - 3 2025. Sanskrit Prayer to Maa Saraswati</li>
  <li>(The words mean something like this:)<br/><br/>
          <ul>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like a lotus may the mind open with learning and enlightenment.</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like a lotus may the mind bloom with creativity spreading beautiful pure and innocent art</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Like the lotus thrives even in mud, to practise these in any time</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like a swan, pure, simple, white elegant, yet distinguishing milk from water</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Like the swan gliding over water without getting its feathers wet, a calmness to reach my divine goal </li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My devotion carry these O veena pustak dharini</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Offer my prayers at your lotus feet Maa Saraswati</li>
            <li><b>***** HAPPY VIJAYADASHMI ********</li></ul><br/>(My composition, thought I'd make it extra special by translating to Sanskrit)
    </li>
    <li> Upload Oct 2-3 2025 </li></ul>`,
},{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  'Thu Oct 02 2025 11:10:00 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Kishore Kumar Birthday.. Bhimsen Tribute Scene - 08/08 - Oct 2 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/Bhimsen-Kishore-Trbute-Aug8-Oct2-2025.jpeg`,
description: `<ul><li> Kishore Kumar Birthday.. Bhimsen Tribute Scene - 08/08 - Oct 2 2025 </li><li> A hallmark of artists true to their passion, humble, down to earth, grounded Attempt to capture how legendary classical singer Bharat Ratna Pt Bhimsen Joshi was enamored by  Kishore Kumar's voice and singing ability esp Amar Prem songs </li><li> Complete on Aug8  in celebration of Kishore Da birth anniversary Aug 4 2025 </li><li> Uploaded Oct 2 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  'Thu Oct 02 2025 10:37:38 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Typical Battle of Britain Scene Complete 09/20 Upl 10/02/2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BattleOfBritain-Sept20-Oct-2-2025.jpeg`,
description: `<ul><li> Typical Battle of Britain Scene Complete 09/20 Upl 10/02/2025 </li><li> Actually an enhancement of a previous sketch </li><li> Attempt to show a bombing raid by Heinkel He-111 with Me-109 escorts being attacked by Spitfires </li><li> Enhancement completed Sept 20, uploaded Oct 2 2025 </li></ul>`,
},
                {
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '10-02-2025',
duplicate:  'true',
summaryLabel:  `Baba Dassera 2025 - Oct 1- 2 2025`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2025-q2-2026/Baba-Dassera-Oct1-Oct2-2025.jpeg`,
description: `<ul><li> Special sketch for Baba Samadhi using metallic and othe color pencils</li><li> Uploaded Oct 2 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Thu Aug 28 2025 22:47:07 Indian Standard Time',

album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 0} ,
duplicate:  'true',
summaryLabel:  `Home Ganapati Sept 30 - Oct 2 2025`,
fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/HomeGanapatiSept30-Oct2-2025.jpeg`,
description: `<ul>
        <li>An appropriate first for a physical album ('The Divine in Colors So Fine') = our 'Home Ganapati' </li>
         <li>Started around Ganesh Chaturthi 2025 time 1st version was released then.  </li>
         <li>Completed Sept 30 2025, detailing with new Silver metallic pencil and <b> trying out fluorescent color pencils (see attempt to draw lights around main piC)<b></li>
         <li>Uploaded Oct 2 2025</li>
       </ul>`,
},

{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Mon Sep 29 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Tushar Pradhan SISL ex colleague Birthday Sept 24`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Falooda-Tushar-Birthday-Sept24-29-2025.jpeg`,
description: `<ul><li>Tushar Pradhan SISL ex colleague Birthday Sept 24</li><li> Upload Sept 29 2025 </li></ul>`,
},
              
{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Mon Sep 29 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Aparna Abhyankar RAIT mate birthday Sept 16`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Falooda-Aparna-Birthday-Sept16-29-2025.jpeg`,
description: `<ul><li> Aparna Abhyankar RAIT mate birthday Sept 16 </li><li> I affectionately call her Guru Maiyya </li><li> Upload Sept 29 2025 </li></ul>`,
},            
{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Mon Sep 29 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Aparna Abhyankar RAIT mate birthday Sept 16`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Falooda-Aparna-Birthday-Sept16-29-2025.jpeg`,
description: `<ul><li> Aparna Abhyankar RAIT mate birthday Sept 16 </li><li> I affectionately call her Guru Maiyya </li><li> Upload Sept 29 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',
dateUploaded:  'Sun Sep 28 2025 15:17:40 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Swami, Datta Sai Chatgpt 09/18 - 9/28/2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SwamiDattaSaiSept172025-chatGPT-pasteback-final.jpeg`,
description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> FINAL VERSION (Step 4 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> 2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> 3. Asked ChatGPT to extend the background  </li><li> 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>`,
iterations: [
{fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SwamiDattaSaiSept172025-chatGPT-pasteback-final.jpeg`, description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> FINAL VERSION (Step 4 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> 2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> 3. Asked ChatGPT to extend the background  </li><li> 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>` },
{fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SwamiDattaSaiSept172025-rawl.jpeg`, description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> Initial RAW VERSION (Step 1 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> (next)2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> (next)3. Asked ChatGPT to extend the background  </li><li> (last) 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>` },
{fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SwamiDattaSaiSept172025-chatGPT-background.png`, description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> CHATGPT VERSION (Step 3 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> (next)2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> (next)3. Asked ChatGPT to extend the background  </li><li> (last) 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>` },
]
},{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '09/11/2025Thu Sep 11 2025 11:03:15 GMT-0700 (Pacific Daylight Time)',

duplicate:  'true',
summaryLabel:  `Baba and Bajrangbali Sept 11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Baba-Bajrangbali-0911-2025.jpg`,
description: `<ul><li>Baba and Bajrangbali compiled and uploaded Sept 11 2025</li></ul>`,
       },  {
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '09/11/2025Thu Sep 11 2025 11:02:34 GMT-0700 (Pacific Daylight Time)',

duplicate:  'true',
summaryLabel:  `A tribute to 4th std Class teacher Ms. Dandekar Sept 10-11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/MsDandekarThanksCardSept10-11-2025.jpeg`,
description: `<ul><li>Ms Dandekar was my class teacher in school in the 4th std which was the only year I stood 1st in class</li><li> A couple of our alumni were to visit her Sept 11 lunch time (IST) so was inspired to create this</li><li> My second tribute to a school teacher after Mr Rodricks our Art teacher</ul>`,
       },
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  'Wed Sep 10 2025 23:03:04 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Sai Doing Ganesh Visarjan complete: Sept 28 2023 upload: Sept 10 2025`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2023/SaiAnantChaturdashi-092823-091025.jpeg`,
description: `<ul><li> Sai Doing Ganesh Visarjan complete: Sept 28 2023 upload: Sept 10 2025 </li></ul>`,
},{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '09/01/2025',

duplicate:  'true',
summaryLabel:  `Carnival Legend cruise to Ensenada Gratitude soft copy Sept 1 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/CarnivalLegendEnsenada4-SC-thanksSep125.jpeg`,

description: `<ul><li>Soft copy gratitude</li><li> Carnival Legend cruise to Ensenada July, (Aug18/19-2025) </li><li> Our very first cruise!!! Carnival Legend SFO-Ensenada(Baja Mexico)-SFO </li><li> Sail 17th afternoon, dock one day - all day Ensenada 19th.. Return 21st Morning </li><li> A *MUST DO* for complete rest and fooding </li><li> Completed Aug 18, upload Aug 19 </li></ul>`,
       },
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Aug 28 2025 22:47:07 Indian Standard Time',

duplicate:  'true',
summaryLabel:  `Gurus with Shree Ganesh Aug 28 2025, Ganesh Chaturthu`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Sai-Ganesh-Chaturthi-Aug27-28.jpeg`,
description: `<ul><li>Collage of Ganesh, with Gurus compiled and uploaded Aug 28 2025</li>
        </ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Wed Aug 27 2025 7:47:07 Indian Standard Time',

duplicate:  'true',
summaryLabel:  `Shripad Vallabh Parayan Aug 27 2025, Ganesh Chaturthu`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Guru-Ganesh-Chaturthi-Aug27.jpeg`,
description: `<ul><li>Collage of Ganesh, Datta and Shripad Vallabh compiled and uploaded Aug 27 2025</li>
        <li>as part of my chapter read (49th) of Shripad Vallabh charitamrutam</li></ul>`,
},{
canvassMaterial:  'Plain paper',
canvassSize:  'A3',
content:  'color-pencil',
dateUploaded:  'Tue Aug 19 2025 22:46:24 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Carnival Legend cruise to Ensenada July, (Aug18/19-2025)`,
fullFileName: `assets/gallery-files/images/transports-and-machines/machines-others/planes-ships-cars-2/CarnivalLegendEnsenada4July19-Aug18-2025.jpeg`,
description: `<ul><li> Carnival Legend cruise to Ensenada July, (Aug18/19-2025) </li><li> Our very first cruise!!! Carnival Legend SFO-Ensenada(Baja Mexico)-SFO </li><li> Sail 17th afternoon, dock one day - all day Ensenada 19th.. Return 21st Morning </li><li> A *MUST DO* for complete rest and fooding </li><li> Completed Aug 18, upload Aug 19 color pencils + charcoal </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A3',
content:  'color pencils + charcoal',
dateUploaded:  'Tue Aug 19 2025 19:31:06 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `India 79th Independence Day Theme Aug 15 - Aug 19 2025`,
fullFileName: `assets/gallery-files/images/themes-misc/India79thIndependenceDay-Aug15-18-2025.jpeg`,
description: `<ul><li> India 79th Independence Day Theme Aug 15 - Aug 19 2025 </li><li> My August 15 theme.. Made in India  centered around Atal Setu - Nhava Sheva end.. Dhruv Helicopter.. At the top, center right is a sort of Independence Day 'mela' with floats of Vande Bharat, PSLV3, Mumbai Sealink  etc. </li><li> Complete Aug 15, uploaded Aug 19 2025 </li></ul>`,
},
 
{ // /Users/shantanug/Documents/GitHub/cms-code/customized-cms/cms-main/src/assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/BabaFeetAug1-2025-Upload-AUg13.jpeg
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  'Wed Aug 13 2025 19:28:25 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Sai Sitting on Stone,. position of hands and legs - Aug 1 - 13 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/BabaFeetAug1-2025-Upload-AUg13.jpeg`,
description: `<ul><li> Sai Sitting on Stone,. position of hands and legs - Aug 1 - 13 2025 </li><li> The significance of Baba's fingers over His toe in sitting posture is profound. It symbolizes that if one wishes to see His Light, they should be ego-less and humble, meditating on His toe through the opening between the two branches. This posture reflects a state of awareness and connection to the divine, emphasizing the importance of humility and meditation in spiritual practice.  </li><li> Completed Aug 1 - uploaded Aug 13 2025 </li><li> Shading pencils and Charcoal </li></ul>`,
},{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Aug 13 2025 12:07:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Wife Uncle Deepak 75th Birthday August 13 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/DeepakKakaBirthdayAug13-2025.jpeg`,
description: `<ul><li>Deepak Rele is my wife's paternal Uncle, who lives in CBD Navi Mumbai (date of this upload)</li>
<li> 75th (platinum) Birthday </li><li> Created and Uploaded Aug 13 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  'Sat Aug 09 2025 10:11:04 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Kargil War Vijay Din July26 (complete Aug1) 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/VijayDinJuly26-CompAug1.jpeg`,
description: `<ul><li> Kargil War Vijay Din July26 (complete Aug1) 2025 </li><li> Symbolic celebration of Victory at Kargil July 26 1999 </li><li> Photo of  victorious Indian Army at Tololing, a pivotal battle  </li><li> ('victory above the clouds') </li><li> The cylinders at either side, at the bottom are empty artillery shells </li><li> Color pencils with Charcoal finish </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Aug 08 2025 19:13:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Sai ChaturMaas compilation Aug8-2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SaiChaturMaasAug8-2025.jpeg`,
description: `<ul><li> Sai ChaturMaas compilation Aug8-2025 </li><li> Compilation of Shirdi Sai sketches across Chaturmass (4 months)  </li><li> Four lunar months, Ashadh, Shravan, Bhadrapad, and Ashwin, or four solar months, starting from Shravana to Kartika.  </li><li> Vithal Ashadh, Shiv + Rakee - Shravan, Ganesh - Bhadrapadh, Ramayan Ashwin, Baba lighting Lamps - Karthik </li><li> compiled and uploaded Aug 8 2025 (Aug 7 Thu, Aug 8 Raksha Bandhan) </li></ul>`,
},

{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Fri Aug 08 2025 19:00:32 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba 2022 --> 2025 RakshaBandan`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2022/BabaAug112022-RakshaBandan-NrliPnima.jpeg`,
description: `<ul><li> Baba 2022 --> 2025 RakshaBandan </li><li> This sketch of Baba wearing Rakhee (Raksha Bandan), having 'Narali Bhaat' (coconut rice) and sea with coconut trees background ('Narali Poornima') was  completed Aug 11 2022, Raskha Bandan THEN  </li><li> uploaded August 8 2025 Raksha Bandan </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Jul 25 2025 10:41:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Samadhi to Masjid July 24-25 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/BabaSamadhiToMAshidJuly242025.jpeg`,
description: `<ul><li> Baba Samadhi to Masjid July 24-25 2025 </li><li> Collage of two paper sketches (unless requested) soft copy only </li><li> "समाधि उथ्रोनिया गुरु चला मशीदी कड़े " Part of Baba Kakad arti line - come from Samadhi and go to the Masjid (Dwarkamai) </li><li> compiled July 24, upload July 25, 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  'Fri Jul 25 2025 10:32:45 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `MV Chidambaram SCI Chennai<->Singapore/Penang`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/MVChidambaramJuly24-2025.jpeg`,
description: `<ul><li> MV Chidambaram SCI Chennai<->Singapore/Penang </li><li> MV Chidambaram was owned by  Shipping Corporation of India(SCI). This liner was originally the M.V. Pasteur and was build in Dunkerque, France. It was sold to the Indian government in 1972. </li><li> Service started 1972, she used to ply the route from Madras to Penang, Port Klang and Singapore, then back again to Madras.  </li><li> Unfortunately ended abruptly 1985 when she caught fire and was decommissioned shortly after </li><li> Drawing completed July 24, uploaded July 25, 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  'Wed Jul 23 2025 00:53:30 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Konkan S** Steamship Mumbai Panjim July22-23 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/KonkanS---SteamshipMumbaiPanjimJuly232025.jpeg`,
description: `<ul><li> Konkan S** Steamship Mumbai Panjim July22-23 2025 </li><li> There used to be a  steamship service between Mumbai and Panjim in the 70s and the 80s.<br/> I traveled by this steamer service once in 1975. My dad had gotten transferred to Goa, Vasco and we decided to travel by the steamer.  Konkan Sevak, Konkan Shakti, - Sarita (not sure if this was renamed Konkan Shakti) and one or two more </li><li>  It was a fantastic and very pleasant journey including a sighting of a dolphin/porpoise that I remember vividly  </li><li> I've captured this <a href="https://art-is-worship.web.app/view/places-scenes-objects">in this list</a> scroll to the bottom </li><li> Completed using regular 4B pencil around July 21, but refreshed with charcoals and uploaded july 23 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A3',
content:  '',
dateUploaded:  'Mon Jul 14 2025 06:48:15 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Gurupoornima 2025 Samadhi Mandir`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/Baba-Gurupoornima-11x17-A4-july10-25.jpeg`,
description: `<ul><li> Baba Gurupoornima 2025 Samadhi Mandir </li><li> Completed a previous unfinished sketch </li><li> Gurupoornima was Thu July 10 2025 </li><li> (Changers 2025 qualifier) to add to the physical album 'The Divine in colors so fine' an A4 copy was made  </li><li> another ground breaker.. allow multiple physical albums if the original list is only a soft copy list like this one </li><li> Uploaded July 14 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  '',
dateUploaded:  'Sun Jul 13 2025 21:31:10 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Vari Symbolic July4, 13 2026`,
fullFileName: `assets/gallery-files/images/religion/laxmi-vishnu-hanuman/Vari-July-4-2025.jpeg`,
description: `<ul><li> Vari Symbolic July4, 13 2026 </li><li> Ashadi Ekadahi being July 6 this year, Varis(Sacred Pilgrimages) leave from different parts of Maharashtra to end at Pandharpur before this date  </li><li> Symbolic of 'Bhagwa' flags, Paduka Palkhi top, and Vithal Rakhumabai in the top left minature  </li><li> Completed July 4, uploaded July 13 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  'Sun Jul 13 2025 15:26:54 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Vari July 3, 13 2025`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/Baba-Vari-July3-2025.jpeg`,
description: `<ul><li> Baba Vari July 3, 13 2025 </li><li> Ashadi Ekadahi being July 6 this year, Varis(Sacred Pilgrimages) leave from different parts of Maharashtra to end at Pandharpur before this date  </li><li> Symbolic of Baba carrying the 'Bhagwa' flag and Vithal Rakhumabai in the top left minature </li><li> Completed July 3, uploaded July 13 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  '',
dateUploaded:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>Comemorating fresh Parayan of Unabridged Sai SatCharit Thu June 26<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Sai Satcharit Chapt1 June 26-27 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/BabaSatCharit1NewParayanJun262025.jpeg`,
description: `<ul><li> Sai Satcharit Chapt1 June 26-27 2025 </li><li> Sai Satcharit Chapt1 .. Hemadpant who (physically) wrote the script pays obeisance to Shree Ganesh, Maa Saraswati, and the 'Guru' which I depict as Lord Datta, then the main story of Baba grinding wheat to keep away the cholera epidemic </li><li> A collage from previous drawings..  </li><li> Compiled June 26 late evening, uploaded just post midnight June 27 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Fri Jun 27 2025 00:06:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>Commemorative of one of the most disruptive events in  Cricket History<br/>Giving the 'underdog' the power of belief that they can win, make it their day<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Fri Jun 27 2025 00:06:07 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Prudential World Cup Oct 23 - June 25`,
fullFileName: `assets/gallery-files/images/places-scenes-objects/PrudentialCup83-Oct1723-June262025.jpeg`,
description: `<ul><li> Prudential World Cup Oct 23 - June 25 </li><li> The Cricketing World was stunned on JUne 25 1983, when the Indian Cricket Team lead by Kapil Dev won the One Day World Cup at Lords England </li><li> Cup shown with a red cricket ball. India defeated West Indies to lift the cup.. a 'nothing short of a miracle event' </li><li> Originally completed Oct 17 2023 - when the latest edition of the World Cup was going on (India, lost the finals, unfortunately, to Australia) </li><li> This was shared on June 25 2025 as a 42nd anniversary commemorative </li><li> Uploaded Midnight June 27 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>A first with the Deity combination<br/>The 1st upload using one click add to 'Most Recent  Uploads' and 'Changers' (2025)<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Ganesh Shiv Hanuman, June 24-26 2025 `,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/GaneshShivHanumanJune24-26-2025.jpeg`,
description: `<ul><li> Ganesh Shiv Hanuman, June 24-26 2025  </li><li> Towards the end of the Jyesth Lunar Month </li><li> Showing Ganesh ji doing milk Abhishek to Shivling and Hanuman ji waiting for His turn </li><li> Showing a 'not waste' concept of the milk being collected from the Shivling </li><li> Completed June 24, uploaded June 26 2025 </li></ul>`,
},
         
         
         {
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '06-14-2025',
duplicate:  'true',
summaryLabel:  `Father's day special Jun 15 2025. Upload Same day`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/FathersDay2025.jpeg`, 
description: `<ul><li>Father's day special Jun 15 2025. Upload Same day</li><li>Shirdi Sai from Dec 2021 to my flower vase template</li></ul>`
} ,{
canvassMaterial: 'Plain paper',
canvassSize: 'A4',
content: 'black-white',
dateUploaded: 'Sat Jun 14 2025 17:34:45 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `DDayJune122025 Upload June 14`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/DDayJune122025Shades1Complete.jpeg`,
description: `<ul><li> DDayJune122025 Upload June 14 </li><li> A belated commemorative of one of several game changing events of WW2 - D Day June 6 1944 The ship numbers on the LCTs are a (tongue in cheek) reference and tribute to the 82nd and 101st airborne: for their significant contributions to D-Day </li></ul>`,
},{
canvassMaterial: 'Plain paper',
canvassSize: '',
content: 'black-white',
dateUploaded: 'Sat Jun 14 2025 17:28:45 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `Rafi June12 2025 Upload June 14`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/RafiJUne122025Shades1Complete.jpeg`,
description: `<ul><li> Rafi June12 2025 Upload June 14 </li><li> Mohammed Rafi, Legendary Playback singer </li><li> December 24, 1924, Kotla Sultan Singh, India </li><li> Died July 31, 1980 </li><li> Actually the sketch was completed Dec 24 ish 2024 </li><li> But it needed some work which I finally got down to doin June 2025 </li></ul>`,
},{
canvassMaterial: 'Plain paper',
canvassSize: 'A4',
content: 'color-pencil',
dateUploaded: 'Sat Jun 14 2025 17:21:55 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true', roles: ["guru"],
summaryLabel: `Baba June12 2025 - June 14 upload`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/BabaJune122025Complete.jpeg`,
description: `<ul><li> Baba June12 2025 - June 14 upload </li><li> Baba Shirdi Murthy Idol with attempt of Milpitas throne backgrpund </li><li> Gray color pencil. Made decision of not to add to the special list since it wasnt up to the mark </li></ul>`,
},{
canvassMaterial: 'Plain paper',
canvassSize: '',
content: 'soft',contentOther: 'charcoal and shading',
dateUploaded: 'Sat Jun 14 2025 17:09:27 GMT-0700 (Pacific Daylight Time)',
duplicate: 'true',
summaryLabel: `Jag Pradakshina Jun10,25 Charcoal1 Upload Jun14`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/JagPradakshinaJun102025Charcoal1Complete.jpeg`,
description: `<ul><li> Jag Pradakshina Jun10,25 Charcoal1 Upload Jun14 </li><li> Mahadev had a contest where the God would get special status who completed 'Pradakshina' (clockwise religious circumambulation ) fastest of the World </li><li> Shree Ganesh showed His wisdom by doing Pradakshina of His parents who mean the wordl </li></ul>`,
},    ]
   }
]
}
/*

*/
