
import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class GaneshGte112024ImageList {
imageRoot = 'assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/';
public allImageList:ImageElement[]  =  [
  {  
            folder:'ganesh-gte-11-2024',
            theme:'<theme>',
            themeSummary: '',
files: [ 

{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Aug 28 2025 22:47:07 Indian Standard Time',

duplicate:  'true',
summaryLabel:  `Gurus with Shree Ganesh Aug 28 2025, Ganesh Chaturthu`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Sai-Ganesh-Chaturthi-Aug27-28.jpeg`,
description: `<ul><li>Collage of Ganesh, with Gurus compiled and uploaded Aug 28 2025</li>
        </ul>`,
},

{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Wed Aug 27 2025 7:47:07 Indian Standard Time',

duplicate:  'true',
summaryLabel:  `Shripad Vallabh Parayan Aug 27 2025, Ganesh Chaturthu`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Guru-Ganesh-Chaturthi-Aug27.jpeg`,
description: `<ul><li>Collage of Ganesh, Datta and Shripad Vallabh compiled and uploaded Aug 27 2025</li>
        <li>as part of my chapter read (49th) of Shripad Vallabh charitamrutam</li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>A first with the Deity combination<br/>The 1st upload using one click add to 'Most Recent  Uploads' and 'Changers' (2025)<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Ganesh Shiv Hanuman, June 24-26 2025 `,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/GaneshShivHanumanJune24-26-2025.jpeg`,
description: `<b>A first with the Deity combination<br/>The 1st upload using one click add to 'Most Recent  Uploads' and 'Changers' (2025)<br/></B><ul><li> Ganesh Shiv Hanuman, June 24-26 2025  </li><li> Towards the end of the Jyesth Lunar Month </li><li> Showing Ganesh ji doing milk Abhishek to Shivling and Hanuman ji waiting for His turn </li><li> Showing a 'not waste' concept of the milk being collected from the Shivling </li><li> Completed June 24, uploaded June 26 2025 </li></ul>`,
},
  
  
{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',contentOther: 'Collage',
dateUploaded:  '04-18-2025',
duplicate:  'false',
evolution:  `<b>1st time - soft copy for Baba thursday<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '04-18-2025',
summaryLabel:  `Ganesh Swami Datta Sai Apr 17-18 2025`,
fullFileName: `${this.imageRoot}GaneshSwamiDattaSai-April172025.jpeg`,
description: `<ul><li> Ganesh Swami Datta Sai Apr 17-18 2025 </li><li> Since, probably Feb 2021, I've been posting one Baba drawing every Thursday.  This will continue, in general, but it may not be on the Thursday - I'll keep the regularity  The 2nd and more significantly, I am shifting focus on creating more soft copy shares, like this collage.  Partly because I am getting a heap of Baba sketches and finding it difficult to catch up on storing them decently </li></ul>`,
}, {
  canvassMaterial:  'other',
  canvassSize:  'soft',
  content:  'soft',
  dateUploaded:  '04-15-2025',
  duplicate:  'true',
  summaryLabel:  `Sangeet Ashtavinayak, Sharada Maa April 8, (15) 2024`,
  fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/SangeetAshtavinayakMaaSaraswatiApril815-2024.jpeg`,
  description: `<ul><li> Sangeet Ashtavinayak, Sharada Maa April 8, (15) 2024 </li><li> Compilation of the recently shared color Ashtavinayaks with Maa Sarawswati in the center </li><li> All color pencils, some water color pencils, charcoal </li><li> Compiled and Shared April 8, uploaded April 15 2025 (eve of Sankatahara Chaturthi) </li></ul>`,
  },
  {
  canvassMaterial:  'Plain paper',
  canvassSize:  'A4',
  content: 'Other',contentOther: 'Using color pencil, charcoal pencil, metal color pencil',
  dateUploaded:  '03-29-2025',
  duplicate:  'true',
  summaryLabel:  `Colored Sangeet Ashtavinayaks 8 March 29 2025`,
  fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-8-Mar29-2025.jpeg`,
  description: `<ul><li> Colored Sangeet Ashtavinayaks 8 March 29 2025 </li><li> FINAL of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 29 2025 (Gudi Padwa in Bay Area, CA) </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
  },
{
canvassSize:  'A4',
content:  'Other',contentOther: 'Using color pencil, charcoal pencil, metal color pencil',
dateUploaded:  '03-29-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 7 March 29 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-7-Mar29-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 7 March 29 2025 </li><li>7th of 8 Ganesh with musical instruments</li><li> Base template copied from B&W </li><li> Completion and upload March 29 2025 (Gudi Padwa in Bay Area, CA) </li><li>  Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft', contentOther: 'Mix of color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '03-28-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 6 March 27-28 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-6-Mar27-28-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 6 March 27-28 2025 </li><li> Base template copied from B&W </li><li> 6th of 8 Ganesh with musical instruments Completion 27th, upload March 28 2025 Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'soft', contentOther: 'Mix of color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '03-25-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 5 March 25 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-5-Mar25-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 5 March 25 2025 </li><li> Colored Sangeet Ashtavinayaks 4 March 11 20255th of 8 Ganesh with musical instruments   </li><li> Base template copied from B&W   </li><li> Completion and upload March 25 2025 Using color pencil, charcoal pencil, metal color pencil  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'other',
contentOther: 'Mix of color pencils, metal color pencils and shading',  

dateUploaded:  '03-18-2025',
duplicate:  'false',
summaryLabel:  `Siddhivinayak Prabhadevi Completed and Upload 03/18/25`,
fullFileName: `${this.imageRoot}Siddhivinayak-Prabhadevi-March18-2025.jpeg`,album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 14} ,
description: `<ul><li> Siddhivinayak Prabhadevi Completed and Upload 03/18/25 </li><li> Old sketch completed  used shading pencils, metal color pencils in add to regular color pencils </li></ul>`,
rating:  1,
ratingYear:  2025,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  '03-11-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 4 March 11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-4-Mar11-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 4 March 11 2025 </li><li> 4th of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 11 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '03-11-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 3 March 11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-3-Mar11-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 3 March 11 2025 </li><li> 3rd of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 11 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color pencil, charcoal pencil, metal color pencil',
dateUploaded:  '03-04-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 2 March 4 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-2-Mar4-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 2 March 4 2025 </li><li> 2nd of 8 Ganesh with musical instruments - Tanpura </li><li> Base template copied from B&W </li><li> Completion and upload March 4 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color pencil, charcoal pencil, metal color pencil',
dateUploaded:  '03-04-2025',
duplicate:  'true',
summaryLabel:  `Colored Sangeet Ashtavinayaks 1 March 4 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Sur-Niragas-Ho-Template-1-Mar4-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 1 March 4 2025 </li><li> 1st of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 4 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '03-04-2025',
duplicate:  'true',
evolution:  `<b>First charcoal sketch <br/></B>`,
evolutionSequence:  5,
evolutionDate:  '03-04-2025',
summaryLabel:  `Ganesh using Charcoal pencils March 3 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Ganesh-Charcoal-March-3-2025.jpeg`,
description: `<ul><li> Ganesh using Charcoal pencils March 3 2025 </li><li> Using Kalour Hard, Medium and Soft black, and white charcoal pencils </li><li> These pencils were gifted by my wife long back and I finally got down to using them  </li><li> Uploaded March 4 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '02-17-2025',
duplicate:  'true',
evolution:  `<b>first metal color drawing<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-17-2025',
summaryLabel:  `Ganesh Metal Gold color pencil Feb 17 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-metal-gold-pencil-Feb17-2025.jpeg`,
description: `<ul><li> Ganesh Metal Gold color pencil Feb 17 2025 </li><li> Using 'Kalour' metal pencil Gold shade </li><li> based on a Brass Ganesh Idol I've had since engineering days </li><li> Upload feb 17 itself </li></ul>`,
rating:  1,
ratingYear:  2025,
},
{
canvassMaterial:  'other',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '02-13-2025',
duplicate:  'true',
evolution:  `<b>print out of an original hard copy and a processed soft copy next to each other<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-13-2025',
summaryLabel:  `Ganesh Reverse Color(3) Original & Processed Feb06-2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-Reverse-Shade-Orig+ProcessedFeb06-2025.jpeg`,
description: `<ul><li> Ganesh Reverse Color(3) Original & Processed Feb06-2025 </li><li> Felt it best to 'collage' the original and processed </li><li> This goes a little tangential in this list by placing two separate images next to each other. But felt the need to </li><li> uploaded Feb 13 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '02-13-2025',
duplicate:  'true',
evolution:  `<b>Reverse color processed. Unique where this image is not a collage but actually processed. Also a print out of a soft copy <br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-13-2025',
summaryLabel:  `Ganesh Reverse color (2) Processed Green Feb 6 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-Reverse-Shade-Processed-Green-Feb06-2025.jpeg`,
description: `<ul><li> Ganesh Reverse color (2) Processed Green Feb 6 2025 </li><li> See 'Ganesh Reverse color (1) Red Feb 6 2025'  </li><li> This is the same image, run through an image processing tool to invert the colors </li><li> Uploaded Feb 13 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  '02-13-2025',
duplicate:  'true',
evolution:  `<b>The description says it all. (See the next = before or after sketch also)<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-13-2025',
summaryLabel:  `Ganesh Reverse color Red Feb 6 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-Reverse-Shade-Red-Feb06-2025.jpeg`,
description: `<ul><li> Ganesh Reverse color Red Feb 6 2025 </li><li> Tried to create a 'negative print' effect here </li><li> normal bright areas are shaded dark and, normally dark areas are not colored or shaded light </li><li> Next (either after or before) is this image processed to reverse the colors </li></ul>`,
rating:  1,
ratingYear:  2025,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '01-16-2025',
duplicate:  'true',
summaryLabel:  `Ganesh Tan color pencil Jan 16 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/GaneshTanMonochromeJan162025.jpeg`,
description: `<ul><li> Ganesh Tan color pencil Jan 16 2025 </li><li>hopeful sandalwood look</li><li> 'Templatized' off an earlier color pencil sketch </li><li> completion AND upload 01/16/2025 </li></ul>`,
},
  {
    canvassMaterial:  'Plain paper',
    canvassSize:  '',
    content:  'color-pencil',
    dateUploaded:  '01-07-2025',
    duplicate:  'true',
    summaryLabel:  `Ganesh Color Monochrome Jan 2 2025`,
    fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/GaneshRedOrangeJan22025.jpeg`,
    description: `<ul><li> Ganesh Color Monochrome Jan 2 2025 </li><li> Start of a new series shades and shines color </li><li> Using red orange color pencil </li></ul>`,
    },
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'true',
summaryLabel:  `Baby Ganesh on Swing Nov 19 2024`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BalGaneshNov192024.jpeg`,
description: `<ul><li> 'Bal Ganesh Jhula' (tongue in cheek on Laxman Jhula)</li><li>Baby Ganesh on Swing Nov 19 2024 </li><li> The 1st  </li><li> So this initial sketch in this series </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '11-18-2024',
duplicate:  'false',
evolution:  `Testing almost complete automation of new image list and menu update`,
evolutionSequence:  4,
evolutionDate:  '11-18-2024',
summaryLabel:  `Ganesh Sankashti Chaturthi Nov 18 2024`,
fullFileName: `${this.imageRoot}GaneshSankashtiChaturthiNov182024.jpeg`,
description: `<ul><li> Ganesh Sankashti Chaturthi Nov 18 2024 </li><li> This also happened to be a Monday </li><li> drawing finish and upload same day  </li></ul>`,
rating:  1,
ratingYear:  2024,
},
  ]}]}
