
import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class ShadesAndShines1ImageList {
reverseStack =  'true';
imageRoot = 'assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/';
public allImageList:ImageElement[]  =  [
  {  
            folder:'shades-and-shines-1',
            theme:'<theme>',
            themeSummary: '',
files: [
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-27-2024',
duplicate:  'false',
summaryLabel:  `Mumbai Meri Jaan.. a City of Centurions 12/26/2024`,
fullFileName: `${this.imageRoot}GatewayTajSRTSMG-Dec2627-2024.jpeg`,
description: `<ul><li> Mumbai Meri Jaan.. a City of Centurions 12/26/2024 </li><li> Featuring 100+ anniversary structures </li><li> 1. Gateway of India (Dec 4 1924-2024) </li><li> 2 Taj Mahal Hotel (Dec 16 1903 - 2003) </li><li> AND (picture book at bottom) Cricket Centurions </li><li> SRT - Sachin Tendulkar 100 international centuries </li><li> SMG - Sunil Gavaskar 34 Test Centuries </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-20-2024',
duplicate:  'false',
summaryLabel:  `RajKapoor Centennial Dec14 1924-2024(12-19-2024)`,
fullFileName: `${this.imageRoot}RajKapoor-Centennial-Dec14-1924-2024-1219.jpeg`,
description: `<ul><li> RajKapoor Centennial Dec14 1924-2024(12-19-2024) </li><li> In remembrance of Raj Kapoor who's centennial anniversary was Dec 14 (1924- 2024) </li><li> Ganesh - Kapoors used to have Ganeshotsav at RK Studios Chembur  </li><li> Started by Raj Kapoor, the legacy was carried by his descendants until 2018 </li><li> The Joker puppet is from his movie Mera Naam Joker </li><li> And RK Banner (minus the figurines) </li><li>completed Dec 19 2024</li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-19-2024',
duplicate:  'false',
summaryLabel:  `Ganesh, Mahadev and Gurus, Dec 19 2024`,
fullFileName: `${this.imageRoot}Ganesh-Mahadev-Guru-12182024.jpeg`,
description: `<ul><li> Ganesh, Mahadev and Gurus, Dec 19 2024 </li><li> Sketch 501.. starting new Guru list </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  '12-14-2024',
duplicate:  'false',
evolution: `<b>500th sketch uploaded!!.<br/>`,
evolutionSequence: 4, evolutionDate: `12-14-2024`,
// coreDescription: 'Timed for Datta Jayanti and Shree Datta to be 500th upload', // 'core user type'
summaryLabel:  `Datta Jayanti Dec 14 2024 - 500th upload`,
fullFileName: `${this.imageRoot}DattaJayanti-2024-12-14-500th.jpeg`,
description: `<ul><li> Datta Jayanti Dec 14 2024 - 500th upload </li><li> Completed and uploaded Dec 14 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-11-2024',
duplicate:  'false',
summaryLabel:  `Swami Vivekanand Rock Kanyakumari  1 2024 - 12 2024`,
fullFileName: `${this.imageRoot}SwamiVivekanandRock-Jan1223-Dec1124.jpeg`,
description: `<ul><li> Swami Vivekanand Rock Kanyakumari  1 2024 - 12 2024 </li><li> Vivekananda Rock Memorial is a monument and popular tourist attraction in Kanyakumari, India's southernmost tip.[1] The memorial stands on one of the two rocks located about 500 meters off mainland of Vavathurai, Tamil Nadu. It was built in 1970 in honour of Swami Vivekananda, who is said to have attained enlightenment on the rock.[ </li><li> Original Sketch completed Jan 12 2024 Swami Birthday </li><li> Touch up Dec 11 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-11-2024',
duplicate:  'false',
summaryLabel:  `Vithal Rukhmini Dec 11 2024`,
fullFileName: `${this.imageRoot}VithalRakhumabai-Dec11-2024.jpeg`,
description: `<ul><li> Vithal Rukhmini Dec 11 2024 </li></ul>`,
},

{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  '12-11-2024',
duplicate:  'false',
summaryLabel:  `Mumbai Metro Dec 11 2024`,
fullFileName: `${this.imageRoot}MumbaiMetroDec112024.jpg`,
description: `<ul><li> Mumbai Metro Dec 11 2024 </li><li> Sketch of Mumbai's Metro with a backdrop based on Contemporary (2020s) Mumbai Skyline </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-09-2024',
duplicate:  'false',
evolution:  `First of its kind. small private planes`,
evolutionSequence:  4,
evolutionDate:  '12-09-2024',
summaryLabel:  `Piper Archer Dec 9 2024`,
fullFileName: `${this.imageRoot}piper-archer-dec-9-2024.jpeg`,
description: `<ul><li> Piper Archer Dec 9 2024 </li><li> Friend of mine, Santosh based in  CO (at this point) flies these </li><li> he sent me reference pics </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-28-2024',
duplicate:  'false',
summaryLabel:  `Baba Thanksgiving Nov 28 2024`,
fullFileName: `${this.imageRoot}BabaNov282024Thanksgiving.jpeg`,
description: `<ul><li> Baba Thanksgiving Nov 28 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-27-2024',
duplicate:  'false',
summaryLabel:  `Swami Samartha 11/21-11/27/2024`,
fullFileName: `${this.imageRoot}SwamiNiv21-272024.jpeg`,
description: `<ul><li> Swami Samartha 11/21-11/27/2024 </li><li> Swami  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-22-2024',
duplicate:  'false',
summaryLabel:  `Vande Bharat (CR Ghat) 11/22/24`,
evolution:  `This has a duplicate entry in 'special trains' the 1st B&W entry in that category `, evolutionSequence:  4, evolutionDate:  '11-18-2024',
fullFileName: `${this.imageRoot}VandeBharatGhatNov2224.jpeg`,
description: `<ul><li> Vande Bharat (CR Ghat) 11/22/24 </li><li> India designed and developed Vande Bharat </li><li> Capable of speeds of 180 kph. </li><li> Trainsets being used on number of routes all over India  </li><li> Mumbai Pune, Delhi Katra (Vaishnodevi), Delhi Benaras to name a few </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-21-2024',
duplicate:  'false',
summaryLabel:  `WDG4 Indian Railways Goods Loco (11/2024)`,
fullFileName: `${this.imageRoot}WDG4-11-21-2024.jpeg`,
description: `<ul><li> WDG4 Indian Railways Goods Loco (11/2024) </li><li> The Indian locomotive class WDG-4 (EMD GT46MAC) is a type of six-axle (Co-Co) freight-hauling diesel–electric locomotive with AC electric transmission designed by General Motors Electro-Motive Diesel </li><li> sketch completed Nov 21 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'false',
summaryLabel:  `Tejas Mk2 IAF HAL Nov 7-19 2024`,
fullFileName: `${this.imageRoot}TejasMk2Nov7-19-2024.jpeg`,
description: `<ul><li> Tejas Mk2 IAF HAL Nov 7-19 2024 </li><li> Hindustan Aeronautics Ltd Tejas LCA  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'false',
summaryLabel:  `Shirdi Sai Baba`,
fullFileName: `${this.imageRoot}ShirdiSaiNov7-19-2024.jpeg`,
description: `<ul><li> Shirdi Sai Baba </li><li> Sai Baba was a saint late 1800's to 1918 </li><li> Sketch 11/07 - 11/19 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'false',
summaryLabel:  `Goddess Durga Navratri Idol November 2024`,
fullFileName: `${this.imageRoot}DeviNov8-192024.jpeg`,
description: `<ul><li> Goddess Durga Navratri Idol November 2024 </li><li> Sketched Nov 8 - 19 2024 </li><li> This is attempting to sketch typical 'Bengali Devi' idol </li><li> She is shown killing the super demon Mahishasur  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'false',
summaryLabel:  `Kashi Vishweshar Temple Citylight Nov 2024`,
fullFileName: `${this.imageRoot}KashiVishweshwarNov11-192024.jpeg`,
description: `<ul><li> Kashi Vishweshar Temple Citylight Nov 2024 </li><li> Started Nov 11, completed Nov 19 2024 </li><li> Attempt to sketch the magnificent sculpture overlooking the main Temple chamber  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'false',
summaryLabel:  `Baby Ganesh on Swing Nov 19 2024`,
fullFileName: `${this.imageRoot}BalGaneshNov192024.jpeg`,
description: `<ul><li> Baby Ganesh on Swing Nov 19 2024 </li><li> It is traditional that starting is involvinng Ganesh. </li><li> So this initial sketch in this series </li></ul>`,
},
  ]}]}
