
import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class ShadesAndShinesOtherColors1ImageList {
  
imageRoot = 'assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/'; 
reverseStack =  'true';
public allImageList:ImageElement[]  =  [
  {  
            folder:'shades-and-shines-other-colors-1',
            theme:'<theme>',
            themeSummary: '',
files: [
{
canvassMaterial:  'other',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '02-13-2025',
duplicate:  'false',
evolution:  `<b>print out of an original hard copy and a processed soft copy next to each other<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-13-2025',
summaryLabel:  `Ganesh Reverse Color(3) Original & Processed Feb06-2025`,
fullFileName: `${this.imageRoot}Ganesh-Reverse-Shade-Orig+ProcessedFeb06-2025.jpeg`,
description: `<ul><li> Ganesh Reverse Color(3) Original & Processed Feb06-2025 </li><li> Felt it best to 'collage' the original and processed </li><li> This goes a little tangential in this list by placing two separate images next to each other. But felt the need to </li><li> uploaded Feb 13 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '02-13-2025',
duplicate:  'false',
evolution:  `<b>Reverse color processed. Unique where this image is not a collage but actually processed. Also a print out of a soft copy <br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-13-2025',
summaryLabel:  `Ganesh Reverse color (2) Processed Green Feb 6 2025`,
fullFileName: `${this.imageRoot}Ganesh-Reverse-Shade-Processed-Green-Feb06-2025.jpeg`,
description: `<ul><li> Ganesh Reverse color (2) Processed Green Feb 6 2025 </li><li> See 'Ganesh Reverse color (1) Red Feb 6 2025'  </li><li> This is the same image, run through an image processing tool to invert the colors </li><li> Uploaded Feb 13 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  '02-13-2025',
duplicate:  'false',
evolution:  `<b>The description says it all. (See the next = before or after sketch also)<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '02-13-2025',
summaryLabel:  `Ganesh Reverse color (1) Red Feb 6 2025`,
fullFileName: `${this.imageRoot}Ganesh-Reverse-Shade-Red-Feb06-2025.jpeg`,
description: `<ul><li> Ganesh Reverse color (1) Red Feb 6 2025 </li><li> Tried to create a 'negative print' effect here </li><li> normal bright areas are shaded dark and, normally dark areas are not colored or shaded light </li><li> Next (either after or before) is this image processed to reverse the colors </li></ul>`,
rating:  1,
ratingYear:  2025,
},
  {
    canvassMaterial:  'Plain paper',
    canvassSize:  'A4',
    content:  'color-pencil',
    dateUploaded:  '02-13-2025',
    duplicate:  'false',
    
    summaryLabel:  `Bugatti Chiron (Feb 5 2025) aqua green`,
    fullFileName: `${this.imageRoot}Bugatti-Chiron-Feb-05-2025.jpeg`,
description: `<ul><li> Bugatti Chiron (Feb 5 2025) aqua green </li><li> One of the fastest street legal cars, this Hyper exotic rubs shoulders with Koenigsegg, Ferrari, Lamborgini, Saleen and others </li><li> Uploaded Feb 13 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '01-18-2025',
duplicate:  'false',
evolution:  `<b>first super speeder exotic<br/></B>`,
evolutionSequence:  5,
evolutionDate:  '01-18-2025',
summaryLabel:  `Koenigsegg Agera RS (Jan-17 2025) sky blue`,
fullFileName: `${this.imageRoot}Koenigsegg-Agera-RS-Jan-17-2025.jpeg`,
description: `<ul><li> Koenigsegg Agera RS (Jan-17 2025) sky blue </li><li> One of the fastest street legal cars, this Hyper exotic rubs shoulders with Buggati, Ferrari, Lamborgini, Saleen and others </li><li> Uploaded Jan 18 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '01-16-2025',
duplicate:  'false',
summaryLabel:  `Ganesh Tan color pencil Jan 16 2025`,
fullFileName: `${this.imageRoot}GaneshTanMonochromeJan162025.jpeg`,
description: `<ul><li> Ganesh Tan color pencil Jan 16 2025 </li><li>hopeful sandalwood look</li><li> 'Templatized' off an earlier color pencil sketch </li><li> completion AND upload 01/16/2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  '01-07-2025',
duplicate:  'false',
summaryLabel:  `Shirdi Sai Jan 2 2025`,
fullFileName: `${this.imageRoot}ShirdiSaiGreenJan22025.jpeg`,
description: `<ul><li> Shirdi Sai Jan 2 2025 </li><li> Using green color pencil  </li></ul>`,
},

{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  '01-07-2025',
duplicate:  'false',
summaryLabel:  `Ganesh Color Monochrome Jan 2 2025`,
fullFileName: `${this.imageRoot}GaneshRedOrangeJan22025.jpeg`,
description: `<ul><li> Ganesh Color Monochrome Jan 2 2025 </li><li> Start of a new series shades and shines color </li><li> Using red orange color pencil </li></ul>`,
},
  ]}]}
