import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class ShirdiSaiQ42024Q12025ImageList {
imageRoot = `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2024-q1-2025/`;

public allImageList:ImageElement[]  =  [
  {  
    folder:'shirdi-sai-q4-2024-q1-2025',
    theme:'Shirdi Sai Sketches Q4 2024 Q1 2025',
            themeSummary: '',
files: [
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  '03-07-2025',
duplicate:  'true',
summaryLabel:  `Baba 'Unplugged' face in Charcoal March 6 2025 (for Feb 27)  `,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Baba-Charcoal-March-6-2025.jpeg`,
description: `<ul><li> Baba 'Unplugged' face March 6 2025  (for Feb 27)  </li><li>Using hard, medium, soft black, and white charcoal pencil</li><li> Uploaded March 7  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  '02-15-2025',album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 10} ,
duplicate:  'false',
summaryLabel:  `Baba on Stone in orange Gurupratibada 2025`,
fullFileName: `${this.imageRoot}Baba-Thursday-Feb13-2025-GuruPratipada.jpeg`,
description: `<ul><li> Baba on Stone in orange Gurupratibada 2025 </li><li> GuruPratibada. Date of Nrusimha Saraswati renouncing regular routine and going to Kardali forest to do Samadhi </li><li> Completed Feb 13, Uploaded Feb 15 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '01-30-2025',
duplicate:  'false',
summaryLabel:  `Baba Handi  Jan 30 2025`,
fullFileName: `${this.imageRoot}BabaHandiJan302025.jpeg`,
description: `<ul><li> Baba Handi </li><li> (actually a scene from Sai Satcharit) </li><li> completed and uploaded Jan 30 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '01-26-2025',
duplicate:  'trye',
summaryLabel:  `Dwarkamai Sai photo 01/23/25`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/SaiDwarkamaiJan232025-012625.jpeg`,
description: `<ul><li> Dwarkamai Sai photo 01/23/25 </li><li> Uploaded Jan 26 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '01-16-2025',
duplicate:  'false',
summaryLabel:  `Baba For Sankrant (Jan 14) - 01/16/2025`,
fullFileName: `${this.imageRoot}BabaPostSankranthJan162025.jpeg`,
description: `<ul><li> Baba For Sankrant (Jan 14) - 01/16/2025 </li><li> Sequence following previous Thursday (Jan 9) drawing </li><li> Til Ladoos and flying kites  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  '01-11-2025',
duplicate:  'false',
summaryLabel:  `Baba making til ladoo Sankranth 2025`,
fullFileName: `${this.imageRoot}BabaPreSankranthJan92025.jpeg`,
description: `<ul><li> Baba making til ladoo Sankranth 2025 </li><li> Posted Jan 9 2025 </li><li> Uploaded Jan 11 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  '01-07-2025',
duplicate:  'false',
summaryLabel:  `Shirdi Sai Jan 2 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/ShirdiSaiGreenJan22025.jpeg`,
description: `<ul><li> Shirdi Sai Jan 2 2025 </li><li> Using green color pencil  </li>
<li>Uploaded Jan 7 2025</li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'color-pencil',
dateUploaded:  '12-26-2024',
duplicate:  'false',
summaryLabel:  `Dec 26 2024`,
fullFileName: `${this.imageRoot}BabaDec262024.jpeg`,
description: `<ul><li> Dec 26 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-12-2024',
duplicate:  'false',
summaryLabel:  `Baba Pre Datta Jayanti (12/14) - 12/12/2024`,
fullFileName: `${this.imageRoot}BabaPreDattaJayantiDec12-2024.jpeg`,
description: `<ul><li> Baba Pre Datta Jayanti (12/14) - 12/12/2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '12-05-2024',
duplicate:  'false',
summaryLabel:  `Baba Dec 4 2024 Milpitas Thu Kakad robes`,
fullFileName: `${this.imageRoot}MilpitasBabaDec42024-Thu-Kakad-night-robes.jpeg`,
description: `<ul><li> Baba Dec 4 2024 Milpitas Thu Kakad robes </li></ul>`,
},

  {
    canvassMaterial:  'Plain paper',
    canvassSize:  'A4',
    content:  'black-white',
    dateUploaded:  '11-28-2024',
    duplicate:  'true',
    summaryLabel:  `Baba Thanksgiving Nov 28 2024`,
    fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BabaNov282024Thanksgiving.jpeg`,
    description: `<ul><li> Baba Thanksgiving Nov 28 2024 </li></ul>`,
    },{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '11-21-2024',
duplicate:  'false',
summaryLabel:  `Baba Nov 21 2024`,
fullFileName: `${this.imageRoot}Baba-11-21-2024.jpeg`,
description: `<ul><li> Baba Nov 21 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'true',
summaryLabel:  `Shirdi Sai Baba`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/ShirdiSaiNov7-19-2024.jpeg`,
description: `<ul><li> Baba  Sketch 11/07 - 11/19 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'true',
summaryLabel:  `Shirdi Sai Baba`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/ShirdiSaiNov7-19-2024.jpeg`,
description: `<ul><li> Baba  Sketch 11/07 - 11/19 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  '11-17-2024',
duplicate:  'false',
evolution:  `rgererge`,
evolutionSequence:  4,
evolutionDate:  '11-17-2024',
summaryLabel:  `Baba from a photo at 1221 CA Circle Milpitas Niv 14 24`,
fullFileName: `${this.imageRoot}Milpitas-Baba-Nov-14-24.jpeg`,
description: `<ul><li> Baba from a photo at 1221 CA Circle Milpitas Niv 14 24 </li></ul>`,
rating:  1,
ratingYear:  2024,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-05-2024',
duplicate:  'false',
summaryLabel:  `Baba Diwali Oct 31 2024`,
fullFileName: `${this.imageRoot}Sai-diwali-oct31-2024.jpeg`,
description: `<ul><li> Baba Diwali Oct 31 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '10-26-2024',
summaryLabel:  `Pre-diwali Special Oct 24 2024`,
fullFileName: `${this.imageRoot}Sai-making-kandeel-diwali-oct24-2024.jpeg`,
description: `<ul><li> Pre-diwali Special Oct 24 2024 </li><li> Showing Baba making the traditional Akash Kandeel </li></ul>`,
},
{
canvassMaterial:  'Watercolor paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  '10-26-2024',
summaryLabel:  `Oct 17 2024 for Kojagiri Poornima (Oct 16) Special`,
fullFileName: `${this.imageRoot}Sai-Oct17-2024-1.jpeg`,
description: `<ul><li> Oct 17 2024 for Kojagiri Poornima (Oct 16) Special </li></ul>`,
iterations: [
{fullFileName: `${this.imageRoot}Sai-Oct17-2024-1.jpeg`, description: `<ul><li> Oct 17 2024 for Kojagiri Poornima (Oct 16) Special </li></ul>` },
{fullFileName: `${this.imageRoot}Sai-Oct17-2024-2.jpeg`, description: `<ul><li> Oct 17 2024 for Kojagiri Poornima (Oct 16) Special </li></ul>` },
{fullFileName: `${this.imageRoot}Sai-Oct17-2024-3.jpeg`, description: `<ul><li> Oct 17 2024 for Kojagiri Poornima (Oct 16) Special </li></ul>` },
]
},
{
canvassMaterial:  'Watercolor paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  '10-26-2024',
summaryLabel:  `Oct 10 2024`,
fullFileName: `${this.imageRoot}Sai-Oct10-2024.jpeg`,
description: `<ul><li> Oct 10 2024 </li></ul>`,
},
{
canvassMaterial:  'Watercolor paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  '10-26-2024',
summaryLabel:  `Sai using Water color`,
fullFileName: `${this.imageRoot}Sai-Oct3-2024-1.jpeg`,
description: `<ul><li> Sai using Water color </li></ul>`,
iterations: [
{fullFileName: `${this.imageRoot}Sai-Oct3-2024-1.jpeg`, description: `<ul><li> Sai using Water color </li></ul>` },
{fullFileName: `${this.imageRoot}Sai-Oct3-2024-2.jpeg`, description: `<ul><li> Sai using Water color </li></ul>` },
]
},
  ]}]}
