import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class ShirdiSaiQ42024Q12025ImageList {
imageRoot = `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2024-q1-2025/`;

public allImageList:ImageElement[]  =  [
  {  
    folder:'shirdi-sai-q4-2024-q1-2025',
    theme:'Shirdi Sai Sketches Q4 2024 Q1 2025',
            themeSummary: '',
files: [
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-12-2024',
duplicate:  'false',
summaryLabel:  `Baba Pre Datta Jayanti (12/14) - 12/12/2024`,
fullFileName: `${this.imageRoot}BabaPreDattaJayantiDec12-2024.jpeg`,
description: `<ul><li> Baba Pre Datta Jayanti (12/14) - 12/12/2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '12-05-2024',
duplicate:  'false',
summaryLabel:  `Baba Dec 4 2024 Milpitas Thu Kakad robes`,
fullFileName: `${this.imageRoot}MilpitasBabaDec42024-Thu-Kakad-night-robes.jpeg`,
description: `<ul><li> Baba Dec 4 2024 Milpitas Thu Kakad robes </li></ul>`,
},

  {
    canvassMaterial:  'Plain paper',
    canvassSize:  'A4',
    content:  'black-white',
    dateUploaded:  '11-28-2024',
    duplicate:  'true',
    summaryLabel:  `Baba Thanksgiving Nov 28 2024`,
    fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BabaNov282024Thanksgiving.jpeg`,
    description: `<ul><li> Baba Thanksgiving Nov 28 2024 </li></ul>`,
    },{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '11-21-2024',
duplicate:  'false',
summaryLabel:  `Baba Nov 21 2024`,
fullFileName: `${this.imageRoot}Baba-11-21-2024.jpeg`,
description: `<ul><li> Baba Nov 21 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'true',
summaryLabel:  `Shirdi Sai Baba`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/ShirdiSaiNov7-19-2024.jpeg`,
description: `<ul><li> Baba  Sketch 11/07 - 11/19 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '11-19-2024',
duplicate:  'true',
summaryLabel:  `Shirdi Sai Baba`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/ShirdiSaiNov7-19-2024.jpeg`,
description: `<ul><li> Baba  Sketch 11/07 - 11/19 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  '11-17-2024',
duplicate:  'false',
evolution:  `rgererge`,
evolutionSequence:  4,
evolutionDate:  '11-17-2024',
summaryLabel:  `Baba from a photo at 1221 CA Circle Milpitas Niv 14 24`,
fullFileName: `${this.imageRoot}Milpitas-Baba-Nov-14-24.jpeg`,
description: `<ul><li> Baba from a photo at 1221 CA Circle Milpitas Niv 14 24 </li></ul>`,
rating:  1,
ratingYear:  2024,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '12-05-2024',
duplicate:  'false',
summaryLabel:  `Baba Diwali Oct 31 2024`,
fullFileName: `${this.imageRoot}Sai-diwali-oct31-2024.jpeg`,
description: `<ul><li> Baba Diwali Oct 31 2024 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '10-26-2024',
summaryLabel:  `Pre-diwali Special Oct 24 2024`,
fullFileName: `${this.imageRoot}Sai-making-kandeel-diwali-oct24-2024.jpeg`,
description: `<ul><li> Pre-diwali Special Oct 24 2024 </li><li> Showing Baba making the traditional Akash Kandeel </li></ul>`,
},
{
canvassMaterial:  'Watercolor paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  '10-26-2024',
summaryLabel:  `Oct 17 2024 for Kojagiri Poornima (Oct 16) Special`,
fullFileName: `${this.imageRoot}Sai-Oct17-2024-1.jpeg`,
description: `<ul><li> Oct 17 2024 for Kojagiri Poornima (Oct 16) Special </li></ul>`,
iterations: [
{fullFileName: `${this.imageRoot}Sai-Oct17-2024-1.jpeg`, description: `<ul><li> Oct 17 2024 for Kojagiri Poornima (Oct 16) Special </li></ul>` },
{fullFileName: `${this.imageRoot}Sai-Oct17-2024-2.jpeg`, description: `<ul><li> Oct 17 2024 for Kojagiri Poornima (Oct 16) Special </li></ul>` },
{fullFileName: `${this.imageRoot}Sai-Oct17-2024-3.jpeg`, description: `<ul><li> Oct 17 2024 for Kojagiri Poornima (Oct 16) Special </li></ul>` },
]
},
{
canvassMaterial:  'Watercolor paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  '10-26-2024',
summaryLabel:  `Oct 10 2024`,
fullFileName: `${this.imageRoot}Sai-Oct10-2024.jpeg`,
description: `<ul><li> Oct 10 2024 </li></ul>`,
},
{
canvassMaterial:  'Watercolor paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  '10-26-2024',
summaryLabel:  `Sai using Water color`,
fullFileName: `${this.imageRoot}Sai-Oct3-2024-1.jpeg`,
description: `<ul><li> Sai using Water color </li></ul>`,
iterations: [
{fullFileName: `${this.imageRoot}Sai-Oct3-2024-1.jpeg`, description: `<ul><li> Sai using Water color </li></ul>` },
{fullFileName: `${this.imageRoot}Sai-Oct3-2024-2.jpeg`, description: `<ul><li> Sai using Water color </li></ul>` },
]
},
  ]}]}
