
import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class SoftCopiesAndCompilations1List {
  
imageRoot = 'assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/'; 
reverseStack =  'true';
public allImageList:ImageElement[]  =  [
  {  
            folder:'soft-copies-and-compilations-1',
            theme:'<theme>',
            themeSummary: '',
files: [ 
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Wed Oct 22 2025 10:54:37 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Baba lighting lamps (2) Diwali 2025`,
fullFileName: `${this.imageRoot}Baba-Diwali-Oct21-22-2025.jpeg`,
description: `<ul><li> Baba lighting lamps (2) Diwali 2025 </li><li> Compiled using merge of another of my drawings with ChatGPT </li><li> Compiled Oct 21 upload Oct 22 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Wed Oct 22 2025 10:44:06 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `JRD Tata photo with AI planes - 93rd anniversary Oct 15 2025 - Oct 22 upload`,
fullFileName: `${this.imageRoot}AirIndia-Founder-93-Anniv-Oct15-2025.jpg`,
description: `<ul><li> JRD Tata photo with AI planes - 93rd anniversary Oct 15 2025 - Oct 22 upload </li><li> Photo of Tata in the center with 4 of (what I think I are) lamndmark aircraft and drawn by me </li><li> DC3 - Dakota, Lokheed Super Connie, 707, Emperor Ashoka 747 </li><li> Compiled and shared Oct 15 2025 (93rd anniv) uploaded Oct 22 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:29:22 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Aruna (Anurag's wife) DOB MM/DD 10/03 complete 10/04/2025 -> Oct 16 `,
fullFileName: `${this.imageRoot}Aruna-Birthday-Oct3-belated-2025.jpeg`,
description: `<ul><li>Aruna (Anurag's wife) DOB MM/DD 10/03 complete 10/04/2025 -> Oct 16 </li>
  <li> Aruna is the wife of Anurag very close friend since RAIT engineering </li><li>Falooda concept in Greeting since she loves ice cream </li><li>VIDAMs is Vijay Pawar, Diwakar Menon(Murali), Anurag and Mohan (who is not with us since 2002), lower case 's' is Shantanu - me </li>
  <li>'Snohal' is tongue in cheek by Shridhar Ranganathan also from RAIT combo of Snehal and Sonal</li>
  <li>Note - the words ARUNA - they are generated by ChatGPT
  <li>Birthday was Oct 3, card was made Oct 4, uploaded Oct 16 2025</li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:39:13 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Baba Samadhi Anniv (Gregorian) Oct 15 2025 (1918) -> Oct 16 `,
fullFileName: `${this.imageRoot}Baba-Samadhi-Gregorian-for-Oct15-2025.jpeg`,
description: `<ul><li> Baba Samadhi Anniv (Gregorian) Oct 15 2025 (1918) -> Oct 16  </li><li> Sai took Samadhi on Dassera Day 1918 which was Oct 15, Tuesday </li><li> Uploaded Oct 16 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:29:22 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Santosh Manjrekar MM/DD 09/28 2025 - Oct 16`,
fullFileName: `${this.imageRoot}SISL-Santosh-Birthday-09282025.png`,
description: `<ul><li> Santosh Manjrekar MM/DD 09/28 2025 - Oct 16 </li><li> Santosh is an ex colleague from SISL </li><li> He is a great enthusiast of planes and flies small planes (of the kind shown) </li><li> Also likes the high life, party, and a carnivore </li><li> His wife Teju, also ex SISL is a vegan ;)  </li><li>But both are extremely fit and work out regularly</li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 08:07:38 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Tribute to IAF Mig21 last flight 26 Sept 2025 drawing 1, 09/27-10/16`,
fullFileName: `${this.imageRoot}Mig21-farewell-tribute-Sept27-2025.jpeg`,
description: `<ul><li> Tribute to IAF Mig21 last flight 26 Sept 2025 drawing 1, 09/27-10/16 </li><li> A tribute to the Mig21 which was  backbone to Indian Air Force and had its last flight 26 Sept 2025. </li><li> 63 years of service </li><li> This is a soft copy made from two original sketches showing 2 mig 21's and a mig 29 </li><li> compiled and completed Sept 27, uploaded Oct 16 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Thu Oct 02 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Dassera special 2025 Oct 1 - 3 2025. Sanskrit Prayer to Maa Saraswati`,
fullFileName: `${this.imageRoot}VijayDashmiSaraswatiPrayer-Oct1-Oct2-2025.jpeg`,
description: `<ul>
<li>Dassera special 2025 Oct 1 - 3 2025. Sanskrit Prayer to Maa Saraswati</li>
  <li>(The words mean something like this:)<br/><br/>
          <ul>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like a lotus may the mind open with learning and enlightenment.</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like a lotus may the mind bloom with creativity spreading beautiful pure and innocent art</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Like the lotus thrives even in mud, to practise these in any time</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;like a swan, pure, simple, white elegant, yet distinguishing milk from water</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Like the swan gliding over water without getting its feathers wet, a calmness to reach my divine goal </li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My devotion carry these O veena pustak dharini</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Offer my prayers at your lotus feet Maa Saraswati</li>
            <li><b>***** HAPPY VIJAYADASHMI ********</li></ul><br/>(My composition, thought I'd make it extra special by translating to Sanskrit)
    </li>
    <li> Upload Oct 2-3 2025 </li></ul>`,
},

{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Mon Sep 29 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Tushar Pradhan SISL ex colleague Birthday Sept 24`,
fullFileName: `${this.imageRoot}Falooda-Tushar-Birthday-Sept24-29-2025.jpeg`,
description: `<ul><li>Tushar Pradhan SISL ex colleague Birthday Sept 24</li><li> Upload Sept 29 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Mon Sep 29 2025 19:19:58 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Aparna Abhyankar RAIT mate birthday Sept 16`,
fullFileName: `${this.imageRoot}Falooda-Aparna-Birthday-Sept16-29-2025.jpeg`,
description: `<ul><li> Aparna Abhyankar RAIT mate birthday Sept 16 </li><li> I affectionately call her Guru Maiyya </li><li> Upload Sept 29 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',
dateUploaded:  'Sun Sep 28 2025 15:17:40 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Swami, Datta Sai Chatgpt 09/18 - 9/28/2025`,
fullFileName: `${this.imageRoot}SwamiDattaSaiSept172025-chatGPT-pasteback-final.jpeg`,
description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> FINAL VERSION (Step 4 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> 2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> 3. Asked ChatGPT to extend the background  </li><li> 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>`,
iterations: [
{fullFileName: `${this.imageRoot}SwamiDattaSaiSept172025-chatGPT-pasteback-final.jpeg`, description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> FINAL VERSION (Step 4 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> 2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> 3. Asked ChatGPT to extend the background  </li><li> 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>` },
{fullFileName: `${this.imageRoot}SwamiDattaSaiSept172025-rawl.jpeg`, description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> Initial RAW VERSION (Step 1 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> (next)2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> (next)3. Asked ChatGPT to extend the background  </li><li> (last) 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>` },
{fullFileName: `${this.imageRoot}SwamiDattaSaiSept172025-chatGPT-background.png`, description: `<ul><li> Swami, Datta Sai Chatgpt 09/18 - 9/28/2025 </li><li> A soft copy compilation with a difference </li><li> CHATGPT VERSION (Step 3 below) <br/>1. Taking the soft copy of a full sketch of Lord Dattatreya, and Shree Swami Samartha </li><li> (next)2. Canvass extended and copied a free select outline (using Photo pad) to paste Sai sketch on the blank area </li><li> (next)3. Asked ChatGPT to extend the background  </li><li> (last) 4. ChatGPT did a GREAT JOB but warped the Guru images, so 'free selected' (Photo pad) them from 1. above and pasted to get the final </li></ul>` },
]

},
 {
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '09/11/2025Thu Sep 11 2025 11:03:15 GMT-0700 (Pacific Daylight Time)',

duplicate:  'false',
summaryLabel:  `Baba and Bajrangbali Sept 11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Baba-Bajrangbali-0911-2025.jpg`,
description: `<ul><li>Baba and Bajrangbali compiled and uploaded Sept 11 2025</li></ul>`,
       },  {
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '09/11/2025Thu Sep 11 2025 11:02:34 GMT-0700 (Pacific Daylight Time)',

duplicate:  'false',
summaryLabel:  `A tribute to 4th std Class teacher Ms. Dandekar Sept 10-11 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/MsDandekarThanksCardSept10-11-2025.jpeg`,
description: `<ul><li>Ms Dandekar was my class teacher in school in the 4th std which was the only year I stood 1st in class</li><li> A couple of our alumni were to visit her Sept 11 lunch time (IST) so was inspired to create this</li><li> My second tribute to a school teacher after Mr Rodricks our Art teacher</ul>`,
       },
  {
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '09/01/2025',

duplicate:  'false',
summaryLabel:  `Carnival Legend cruise to Ensenada Gratitude soft copy Sept 1 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/CarnivalLegendEnsenada4-SC-thanksSep125.jpeg`,

description: `<ul><li>Soft copy gratitude</li><li> Carnival Legend cruise to Ensenada July, (Aug18/19-2025) </li><li> Our very first cruise!!! Carnival Legend SFO-Ensenada(Baja Mexico)-SFO </li><li> Sail 17th afternoon, dock one day - all day Ensenada 19th.. Return 21st Morning </li><li> A *MUST DO* for complete rest and fooding </li><li> Completed Aug 18, upload Aug 19 </li></ul>`,
       },
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Aug 28 2025 22:47:07 Indian Standard Time',

duplicate:  'false',
summaryLabel:  `Gurus with Shree Ganesh Aug 28 2025, Ganesh Chaturthu`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Sai-Ganesh-Chaturthi-Aug27-28.jpeg`,
description: `<ul><li>Collage of Ganesh, with Gurus compiled and uploaded Aug 28 2025</li>
        </ul>`,
},{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Wed Aug 27 2025 7:47:07 Indian Standard Time',

duplicate:  'false',
summaryLabel:  `Shripad Vallabh Parayan Aug 27 2025, Ganesh Chaturthu`,
fullFileName: `${this.imageRoot}Guru-Ganesh-Chaturthi-Aug27.jpeg`,
description: `<ul><li>Collage of Ganesh, Datta and Shripad Vallabh compiled and uploaded Aug 27 2025</li>
        <li>as part of my chapter read (49th) of Shripad Vallabh charitamrutam</li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Aug 13 2025 12:07:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Wife Uncle Deepak 75th Birthday August 13 2025`,
fullFileName: `${this.imageRoot}DeepakKakaBirthdayAug13-2025.jpeg`,
description: `<ul><li>Deepak Rele is my wife's paternal Uncle, who lives in CBD Navi Mumbai (date of this upload)</li>
<li> 75th (platinum) Birthday </li><li> Created and Uploaded Aug 13 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Aug 08 2025 19:13:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Sai ChaturMaas compilation Aug8-2025`,
fullFileName: `${this.imageRoot}SaiChaturMaasAug8-2025.jpeg`,
description: `<ul><li> Sai ChaturMaas compilation Aug8-2025 </li><li> Compilation of Shirdi Sai sketches across Chaturmass (4 months)  </li><li> Four lunar months, Ashadh, Shravan, Bhadrapad, and Ashwin, or four solar months, starting from Shravana to Kartika.  </li><li> Vithal Ashadh, Shiv + Rakee - Shravan, Ganesh - Bhadrapadh, Ramayan Ashwin, Baba lighting Lamps - Karthik </li><li> compiled and uploaded Aug 8 2025 (Aug 7 Thu, Aug 8 Raksha Bandhan) </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Jul 25 2025 10:41:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Baba Samadhi to Masjid July 24-25 2025`,
fullFileName: `${this.imageRoot}BabaSamadhiToMAshidJuly242025.jpeg`,
description: `<ul><li> Baba Samadhi to Masjid July 24-25 2025 </li><li> Collage of two paper sketches (unless requested) soft copy only </li><li> "समाधि उथ्रोनिया गुरु चला मशीदी कड़े " Part of Baba Kakad arti line - come from Samadhi and go to the Masjid (Dwarkamai) </li><li> compiled July 24, upload July 25, 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  '',
dateUploaded:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
evolution:  `<b>Comemorating fresh Parayan of Unabridged Sai SatCharit Thu June 26<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Sai Satcharit Chapt1 June 26-27 2025`,
fullFileName: `${this.imageRoot}BabaSatCharit1NewParayanJun262025.jpeg`,
description: `<ul><li> Sai Satcharit Chapt1 June 26-27 2025 </li><li> Sai Satcharit Chapt1 .. Hemadpant who (physically) wrote the script pays obeisance to Shree Ganesh, Maa Saraswati, and the 'Guru' which I depict as Lord Datta, then the main story of Baba grinding wheat to keep away the cholera epidemic </li><li> A collage from previous drawings..  </li><li> Compiled June 26 late evening, uploaded just post midnight June 27 2025 </li></ul>`,
},
  {
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '06-14-2025',
duplicate:  'false',
summaryLabel:  `Father's day special Jun 15 2025. Upload Same day`,
fullFileName: `${this.imageRoot}FathersDay2025.jpeg`, 
description: `<ul><li>Father's day special Jun 15 2025. Upload Same day</li><li>Shirdi Sai from Dec 2021 to my flower vase template</li></ul>`
} ,
  {
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '05-31-2025',
duplicate:  'false',
summaryLabel:  `Ishaan, my wife Snehal's nephew June 1 2025 Birthday. Upload Same day`,
fullFileName: `${this.imageRoot}IshanBirthday-June1-2025.jpeg`, 
description: `<ul><li>Ishaan, my wife Snehal's nephew June 1 2025 Birthday. Upload Same day</li></ul>`
} ,
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '05-31-2025',
duplicate:  'false',
summaryLabel:  `Prakash, RAIT 93 Batch May 31 2025 Birthday. Upload Same day`,
fullFileName: `${this.imageRoot}PrakashBDayMay31-2025.jpeg`, 
description: `<ul><li>Prakash, RAIT 93 Batch  May 31 2025 Birthday. Upload Same day </li></ul>`
} ,
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '05-31-2025',
duplicate:  'false',
summaryLabel:  `Anurag Mendhekar May 31 2025 Birthday. Upload Same day`,
fullFileName: `${this.imageRoot}Anurag-Birthday-May31-2025.jpeg` ,
description: `<ul><li>Anurag Mendhekar May 31 2025 Birthday. Upload Same day </li><li> Anurag is a close friend of mine since my Engineering days </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '05-29-2025',
duplicate:  'false',
summaryLabel:  `The 'Himalayan Geese' An12 and Il76 (Gajraj) planes Jan 9 / May 29 2025`,
fullFileName: `${this.imageRoot}HimalayanGeese-Jan9-2025.jpeg`,
description: `<ul><li> The 'Himalayan Geese' An12 and Il76 (Gajraj) planes Jan 9 / May 29 2025 </li><li> A 'software stitch' of the two (main) aircraft of IAF 44 Squadron, the 'Himalayan Geese' </li><li> Feature Antonov An12 the previous, and 'Gajraj' IL76, the current main aircraft of the squadron </li><li> Upload May 29 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '04-30-2025',
duplicate:  'false',
summaryLabel:  `Anjali Pathak April 28 Birthday. Upload April 30`,
fullFileName: `${this.imageRoot}Anjali-2025-Birthday.jpeg`,
description: `<ul><li> Anjali Pathak April 28 Birthday. Upload April 30 </li><li> Anjali is a close friend of mine since my Engineering days </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '04-30-2025',
duplicate:  'false',
summaryLabel:  `Old Bombay Facebook group 7th anniv 27th - 28th `,
fullFileName: `${this.imageRoot}OldBombay7thanniv.jpeg`,
description: `<ul><li> Old Bombay Facebook group 7th anniv 27th - 28th  </li><li> This is a group which is all about Bombay. </li><li> I submit a large number of sketches here each Friday </li><li> A poem I wrote with the 'card': <br/> <em>&nbsp;&nbsp;This Group is a great INSPIRATION, <br/>&nbsp;&nbsp;&nbsp;&nbsp;Gives me a NEW MOTIVATION <br/>&nbsp;&nbsp;Flow the juices of CREATION, <br/>&nbsp;&nbsp;&nbsp;&nbsp;Coming LATE with my FELICITATION,<br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BLESSED to be in this CELEBRATION!!!</em><br/> </li><li> Created April 28, uploaded April 30 2025 </li></ul>`,
},
  {
    canvassMaterial:  'other',
    canvassSize:  '',
    content:  'soft',contentOther: 'Collage',
    dateUploaded:  '04-18-2025',
    duplicate:  'true',
    evolution:  `<b>1st time - soft copy for Baba thursday<br/></B>`,
    evolutionSequence:  4,
    evolutionDate:  '04-18-2025',
    summaryLabel:  `Ganesh Swami Datta Sai Apr 17-18 2025`,
    fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/GaneshSwamiDattaSai-April172025.jpeg`,
    description: `<ul><li>स्वामी स्नेही शिर्डी साई </li><li> श्रद्धा सबुरी द्वारकामाई </li><li>करा गुरुस्मरण</li><li>होता  गुरुशरण</li><li> माथी  ठेवी गुरुचरण</li><li>मुखी मनात सदा  गुरुनामन </li><li>स्वामी प्रचंड बाळ पाठीशी हो</li><li>  स्वामी साई दत्त भक्ती निरागस हो</li><li> Ganesh Swami Datta Sai Apr 17-18 2025 </li><li> Since, probably Feb 2021, I've been posting one Baba drawing every Thursday.  This will continue, in general, but it may not be on the Thursday - I'll keep the regularity  The 2nd and more significantly, I am shifting focus on creating more soft copy shares, like this collage.  Partly because I am getting a heap of Baba sketches and finding it difficult to catch up on storing them decently </li></ul>`,
    },{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',
dateUploaded:  '04-16-2025',
duplicate:  'false',
summaryLabel:  `Second Sangeet Ashtavinayak, 1st with Saraswati Jan 2 24, upload 04/16/2025`,
fullFileName: `${this.imageRoot}SangeetAshtavinayakMaaSaraswatiJan022025April16-2025.jpeg`,
description: `<ul><li> Second Sangeet Ashtavinayak, 1st with Saraswati Jan 2 24, upload 04/16/2025 </li><li> The Sangeet Ashtavinayaks with Art college Maa Saraswati idol in center </li><li> completed Jan 2 2024, upload April 16 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  '04-15-2025',
duplicate:  'false',
summaryLabel:  `Sangeet Ashtavinayak, Sharada Maa April 8, (15) 2024`,
fullFileName: `${this.imageRoot}SangeetAshtavinayakMaaSaraswatiApril815-2024.jpeg`,
description: `<ul><li> Sangeet Ashtavinayak, Sharada Maa April 8, (15) 2024 </li><li> Compilation of the recently shared color Ashtavinayaks with Maa Sarawswati in the center </li><li> All color pencils, some water color pencils, charcoal </li><li> Compiled and Shared April 8, uploaded April 15 2025 (eve of Sankatahara Chaturthi) </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft',contentOther:'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '03-28-2025',
duplicate:  'false',
summaryLabel:  `Shankar Mahadevan Thanks March 27 -28 2025`,
fullFileName: `${this.imageRoot}Shankar-rocks-March27-28-2025.jpeg`,
description: `<ul><li> Shankar Mahadevan Thanks March 27 -28 2025 </li><li> Shankar Mahadevan from my engineering college RAIT </li><li> Famous National award wining singer and music director (those who dont know him) </li></ul>`,
},
{
canvassSize:  'other',
content:  'other',contentOther: 'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '03-28-2025',
duplicate:  'false',
summaryLabel:  `Nivedita Raut / Badve (Scottish) Grandma March 23 2025`,
fullFileName: `${this.imageRoot}Nive-Congrats-card-March-23-2025.jpeg`,
description: `<ul><li> Nivedita Raut / Badve (Scottish) Grandma March 23 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'other',
content:  'soft', contentOther: 'Template based Software edit AND Mix of all drawing "utensils" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '03-28-2025',
duplicate:  'false',
evolution:  `<b>sort of first attempt to do an eCard<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '03-28-2025',
summaryLabel:  `Blank Template March 24 - 28 2025`,
fullFileName: `${this.imageRoot}Generic-Thanks-card-032425.jpeg`,
description: `<ul><li> Blank Template March 24 - 28 2025 </li></ul>`,
},
    {  
    // /Users/shantanu/Documents/GitHub/js-frameworks/Angular_lte_4/shan-cms-template/src/assets/all-images/religion/mahadev/MahadevJan102022.jpeg
    // /Users/shantanu/Documents/GitHub/js-frameworks/Angular_lte_4/shan-cms-template/src/assets/all-images/religion/mahadev/Shivji2022ShravanMonday_1.jpeg
    canvassSize: 'soft', content:'black-white',
    duplicate:'true',
        fullFileName: `assets/gallery-files/images/salaam-mumbai/mumbai-meri-jaan/mumbai-theme2.png`, 
    description: 
       `<ul>
         <li>26/11 terrorist attack tribute - similar to the one I sketched two years back,but with different and more recent sketches around the center</li>
         <li>Central pic - top L to R : Mumba Devi, mostly Sandeep Unikrishnan, Tukram Omble, Ashok Kamte, Vijay Salaskar, Hemant Karkare, Havaldar Gajendra Singh,Mother Mary </li>
         <li>Other pics - Left to Right, top to bottom<br/>
          - VJTI engineering institute. INS Rajput class destroyer at Gateway of India, Nehru Planetarium, Nehru Science Center<br/>
          - Marine Drive vista. Typical Launch at Gateway of India (navy battery), Butcher island(Jawahar Dweep) and Elephanta (Gharapuri)island<br/></li>
         </ul>`,
      
   dateUploaded: '11-28-2022',}
 ,  { 
    canvassSize: 'soft', content:'black-white',
        fullFileName: `assets/gallery-files/images/salaam-mumbai/mumbai-meri-jaan/MumbaiTheme26112020_finalVer1.png`,
        duplicate:'true',
        description: `<ul>
    <li>26/11 Tribute - the complete compilation</li>
    <li>..continuing from the 1st sketch, compilation which is 9 A4 size sketches 'stitched' together.. </li>
    <li>click the '>>' button above to see the (other) individual pieces in more detail</li>
    <li>Nov 2020 timeframe</li>
  </ul>`,
    dateUploaded: '01-15-2022',
}, {
    canvassSize: 'soft', content:'black-white',
    fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/pre-q4-2021ganesh/sangeet-vinayak-Q3-2021/SangeetVinayakJuly26-27-2021.png`, 
    duplicate:'true',
    description: `<ul>
    <li>July 26-27 2021</li>
        <li>AND THE COMPILATION!!!! </li>
        <li>..</li>
    </ul>`
    }
  ]}]}
