
import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class CharcoalTimesOtherColorsShinesImageList {
  reverseStack =  'true';
imageRoot = 'assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/'; 
public allImageList:ImageElement[]  =  [
  {  
            folder:'charcoal-times-other-colors-shines',
            theme:'<theme>',
            themeSummary: '',
files: [
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'other',
contentOther: 'Mix of color pencils, watercolor pencils, charcoals, metal color pencils and shading',  
dateUploaded:  '03-18-2025',
duplicate:  'false',
summaryLabel:  `Dessert of darbari daawat: A drink of Badshah(') s 03/16-03/18/25`,
fullFileName: `${this.imageRoot}Falooda-March-16-18-2025.jpeg`,
description: `<ul><li> Dessert of darbari daawat: A drink of Badshah(') s 03/16-03/18/25 </li><li> "A (Delhi ) darbari daawat has to end with the drink of Badshah(') s " </li><li> The above is a sort of Pun, but first - the picture compositionn: </li><li> Falooda a rich and sumptious desset - ice cream, milk, rose syrup, sweetened vermiccelli, pearls, garnish with dry fruits </li><li> 'Paan' Betel leaves in the background </li><li> OK - the pun - Badshah(')s is a cold drink house in Central Mumbai </li><li> And Delhi Darbar is a famous Moghlai Restaurant nearby  </li><li> Used all color material, shading pencils and (of course) charcoal except crayons </li><li> completed March 16, upload March 18 2025</li></ul>`,
},
{

  canvassMaterial:  'Plain paper',
  canvassSize:  'A4',
  content:  'other',
  contentOther: `Mix of all drawing 'utensils' used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading`,  
  
dateUploaded:  '03-16-2025',
duplicate:  'false',
evolution:  `<b>550th sketch and a sort of uncategorized (as yet) sketch<br/>Also uses ALL coloring and B&W tools - black and white, Shading, color pencils, crayons (a bit), watercolor pencils, metallic pencils, and charcoal</B>`,
evolutionSequence:  4,
evolutionDate:  '03-16-2025',
summaryLabel:  `(#550) Combined Holi Drawing and Art Teacher Rodricks Sir Tribure March13- 16 '25`,
fullFileName: `${this.imageRoot}Holi-And-Rodricks-Sir-Tribute-March13-16-2025.jpeg`,
description: `<ul><li> (#550) Combined Holi Drawing and Art Teacher Rodricks Sir Tribure March13- 16 '25 </li><li> The idea came to draw something different to signify a splash of colors for Holi </li><li> One thing evolved into another, and one major lapse of not acknowledging my Art Teacher at School </li><li> Mr Rodricks who retired when I was in mid school - I was a sort of favorite of his </li><li> This is a still life, object drawing with sunflowers and a few other types in all the flowers which Sir taught us </li><li> Also I thought the card would be a nice way to express tribute, with Sir's name inside </li><li> Completed Mar 13, uploaded Mar 16 2025 </li><li> Timed to be the 550th sketch </li><li>Also uses ALL coloring and B&W tools I've used since THIS journey started - black and white, Shading, color pencils, crayons (a bit), watercolor pencils, metallic pencils, and charcoal</li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  '03-11-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 4 March 11 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-4-Mar11-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 4 March 11 2025 </li><li> 4th of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 11 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '03-11-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 3 March 11 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-3-Mar11-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 3 March 11 2025 </li><li> 3rd of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 11 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  '03-10-2025',
duplicate:  'false',
summaryLabel:  `Hookah  March10 2025 `,
fullFileName: `${this.imageRoot}Hookah-Charcoal-March10-2025.jpeg`,
description: `<ul><li> Hookah,  March10 2025  </li><li>Start, complete, upload March 10 2025 (pm)</li><li> Trying ambitious - earthenware, metal, cloth shading</li><li>Also tried wet cloth and water droplets around the metal water container (lower part/base)</li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '03-10-2025',
duplicate:  'false',
summaryLabel:  `Baba on Stone famous pose March 10 2025`,
fullFileName: `${this.imageRoot}Baba-March10-for-Feb20-2025.jpeg`,
description: `<ul><li> Baba on Stone famous pose March 10 2025 </li><li> Upload same day. From an old sketch </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '03-07-2025',
duplicate:  'false',
summaryLabel:  `Dhow with 'Mumbai Bandstand' backdrop March 7 2025`,
fullFileName: `${this.imageRoot}Dhow-Bandstand-March7-2025.jpeg`,
description: `<ul><li> Dhow with 'Mumbai Bandstand' backdrop March 7 2025 </li><li> Uploaded same day (March 7) </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  '03-07-2025',
duplicate:  'false',
summaryLabel:  `Baba 'Unplugged' face March 6 2025  `,
fullFileName: `${this.imageRoot}Baba-Charcoal-March-6-2025.jpeg`,
description: `<ul><li> Baba 'Unplugged' face March 6 2025   </li><li> Uploaded March 7  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  '03-04-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 2 March 4 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-2-Mar4-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 2 March 4 2025 </li><li> 2nd of 8 Ganesh with musical instruments - Tanpura </li><li> Base template copied from B&W </li><li> Completion and upload March 4 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color pencil, charcoal pencil, metal color pencil',
dateUploaded:  '03-04-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 1 March 4 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-1-Mar4-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 1 March 4 2025 </li><li> 1st of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 4 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '03-04-2025',
duplicate:  'false',
evolution:  `<b>First charcoal sketch <br/></B>`,
evolutionSequence:  5,
evolutionDate:  '03-04-2025',
summaryLabel:  `Ganesh using Charcoal pencils March 3 2025`,
fullFileName: `${this.imageRoot}Ganesh-Charcoal-March-3-2025.jpeg`,
description: `<ul><li> Ganesh using Charcoal pencils March 3 2025 </li><li> Using Kalour Hard, Medium and Soft black, and white charcoal pencils </li><li> These pencils were gifted by my wife long back and I finally got down to using them  </li><li> Uploaded March 4 2025 </li></ul>`,
},
  ]}]}
