
import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class CharcoalTimesOtherColorsShinesImageList {
  reverseStack =  'true';
imageRoot = 'assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/'; 
public allImageList:ImageElement[]  =  [
  {  
            folder:'charcoal-times-other-colors-shines',
            theme:'<theme>',
            themeSummary: '',
files: [
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  'Sat Aug 09 2025 10:11:04 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Kargil War Vijay Din July26 (complete Aug1) 2025`,
fullFileName: `${this.imageRoot}VijayDinJuly26-CompAug1.jpeg`,
description: `<ul><li> Kargil War Vijay Din July26 (complete Aug1) 2025 </li><li> Symbolic celebration of Victory at Kargil July 26 1999 </li><li> Photo of  victorious Indian Army at Tololing, a pivotal battle  </li><li> ('victory above the clouds') </li><li> The cylinders at either side, at the bottom are empty artillery shells </li><li> Color pencils with Charcoal finish </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  'Fri Jul 25 2025 10:32:45 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `MV Chidambaram SCI Chennai<->Singapore/Penang`,
fullFileName: `${this.imageRoot}MVChidambaramJuly24-2025.jpeg`,
description: `<ul><li> MV Chidambaram SCI Chennai<->Singapore/Penang </li><li> MV Chidambaram was owned by  Shipping Corporation of India(SCI). This liner was originally the M.V. Pasteur and was build in Dunkerque, France. It was sold to the Indian government in 1972. </li><li> Service started 1972, she used to ply the route from Madras to Penang, Port Klang and Singapore, then back again to Madras.  </li><li> Unfortunately ended abruptly 1985 when she caught fire and was decommissioned shortly after </li><li> Drawing completed July 24, uploaded July 25, 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  'Wed Jul 23 2025 00:53:30 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Konkan S** Steamship Mumbai Panjim July22-23 2025`,
fullFileName: `${this.imageRoot}KonkanS---SteamshipMumbaiPanjimJuly232025.jpeg`,
description: `<ul><li> Konkan S** Steamship Mumbai Panjim July22-23 2025 </li><li> There used to be a  steamship service between Mumbai and Panjim in the 70s and the 80s.<br/> I traveled by this steamer service once in 1975. My dad had gotten transferred to Goa, Vasco and we decided to travel by the steamer.  Konkan Sevak, Konkan Shakti, - Sarita (not sure if this was renamed Konkan Shakti) and one or two more </li><li>  It was a fantastic and very pleasant journey including a sighting of a dolphin/porpoise that I remember vividly  </li><li> I've captured this <a href="https://art-is-worship.web.app/view/places-scenes-objects">in this list</a> scroll to the bottom </li><li> Completed using regular 4B pencil around July 21, but refreshed with charcoals and uploaded july 23 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
evolution:  `<b>A first with the Deity combination<br/>The 1st upload using one click add to 'Most Recent  Uploads' and 'Changers' (2025)<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Ganesh Shiv Hanuman, June 24-26 2025 `,
fullFileName: `${this.imageRoot}GaneshShivHanumanJune24-26-2025.jpeg`,
description: `<ul><li> Ganesh Shiv Hanuman, June 24-26 2025  </li><li> Towards the end of the Jyesth Lunar Month </li><li> Showing Ganesh ji doing milk Abhishek to Shivling and Hanuman ji waiting for His turn </li><li> Showing a 'not waste' concept of the milk being collected from the Shivling </li><li> Completed June 24, uploaded June 26 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',contentOther: 'charcoal and shading',
dateUploaded:  'Sat Jun 14 2025 17:09:27 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Jag Pradakshina Jun10,25 Charcoal1 Upload Jun14`,
fullFileName: `${this.imageRoot}JagPradakshinaJun102025Charcoal1Complete.jpeg`,
description: `<ul><li> Jag Pradakshina Jun10,25 Charcoal1 Upload Jun14 </li><li> Mahadev had a contest where the God would get special status who completed 'Pradakshina' (clockwise religious circumambulation ) fastest of the World </li><li> Shree Ganesh showed His wisdom by doing Pradakshina of His parents who mean the wordl </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',contentOther: 'charcoal and shading',
dateUploaded:  '06-01-2025 12:00',
duplicate:  'true',
evolution:  `<b>The first A3 Charcoal sketch. .. Also inserted a copy in 'Charcoal Times Other Colors Shines'<br/></B>`,
evolutionSequence:  5,
evolutionDate:  '06-01-2025',
summaryLabel:  `Hanuman A3 Charcoal May 31, upload June 1, 2025`,
fullFileName: `assets/gallery-files/images/religion/laxmi-vishnu-hanuman/HanumanMay31-2025.jpeg`,
description: `<ul><li> CHANGER: The first A3 Charcoal sketch. .. Original inserted in what will be designated as the 3rd album </li></ul>`,
},{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  '05-29-2025',
duplicate:  'true',contentOther: 'Mix of color pencils, charcoal and shading',
summaryLabel:  `Tejas. Operation Sindoor May 8 - May 29 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/TejasOperationSindoorMay82025.jpeg`,
description: `<ul><li> Tejas. Operation Sindoor May 8 - May 29 2025 </li><li> One of my unfinished sketches, completed in a Hotel Room at Boston </li><li> Watching reports on how India decimated Pak forces in Operation Sindoor </li><li> The strikes involved 100% successful defence against Pak drones and missiles </li><li> The aircraft is HAL Tejas operated by IAF,  background is symbolic of Maa Kali forehead with bright red 'Sindoor' </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content: 'Other',contentOther: 'Using color pencil, charcoal pencil, metal color pencil',
dateUploaded:  '05-02-2025',
duplicate:  'false',
summaryLabel:  `INS MUMBAI DELHI Class ship  at MUMBAI May1-2, 2025.jpeg`,
fullFileName: `${this.imageRoot}Mumbai-Delhi-Mumbai-May1-2-2025.jpeg`,
description: `<ul><li> INS MUMBAI DELHI Class ship  at MUMBAI May1-2, 2025.jpeg </li><li> INS Mumbai, Indian Navy Guided Missile Destroyer - Delhi class shown at Mumbai Port </li><li> Completed May1 uploaded May 2 2025 </li></ul>`,
},

{  canvassMaterial:  'Plain paper',
  canvassSize:  'A4',
  content: 'Other',contentOther: 'Using color pencil, charcoal pencil, metal color pencil',
  dateUploaded:  '03-29-2025',
  duplicate:  'false',
  summaryLabel:  `Colored Sangeet Ashtavinayaks 8 March 29 2025`,
  fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-8-Mar29-2025.jpeg`,
  description: `<ul><li> Colored Sangeet Ashtavinayaks 8 March 29 2025 </li><li> FINAL of 8 Ganesh with musical instruments </li><li> ase template copied from B&W </li><li> Completion and upload March 29 2025 (Gudi Padwa in Bay Area, CA) </li><li> Using color pencil, charcoal pencil, metal color pencil </li>NOTE: this order of completion of sketches gets back to normal here</ul>`,
  },
{
canvassSize:  'A4',
content:  'Other',contentOther: 'Using color pencil, charcoal pencil, metal color pencil',
dateUploaded:  '03-29-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 7 March 29 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-7-Mar29-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 7 March 29 2025 </li><li>7th of 8 Ganesh with musical instruments</li><li> Base template copied from B&W </li><li> Completion and upload March 29 2025 (Gudi Padwa in Bay Area, CA)  </li><li>  Using color pencil, charcoal pencil, metal color pencil </li><li>NOTE: this departs from the order of completion of sketches. The sketch before this was completed AFTER this and the next one. This for logical arrangement of the themes :)</li></ul>`,
},{
  canvassMaterial:  'Plain paper',
  canvassSize:  '',
  content:  'black-white',
  dateUploaded:  '03-31-2025',
  duplicate:  'false',
  summaryLabel:  `Shivling March 31 2025 (out of turn insert)`,
  fullFileName: `${this.imageRoot}Shiving-March31-2025-outofturn.jpeg`,
  description: `<ul><li> Shivling March 31 2025 (out of turn insert) </li><li> Only Charcoal and shading pencils </li><li> NOTE: this departs from the order of completion of sketches. The sketch after this and the next were completed BEFORE. This for logical arrangement of the themes :) </li><li> Uploaded March 31 2025 </li></ul>`,
  },
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'other', contentOther: 'black and white using Charcoal',
dateUploaded:  '03-28-2025',
duplicate:  'false',
summaryLabel:  `Khanderaya .. Shiva Avatar 03/27 - 03/28/2025`,
fullFileName: `${this.imageRoot}Khanderaya-getup-March27-28-2025.jpeg`,
description: `<ul><li> Khanderaya .. Shiva Avatar 03/27 - 03/28/2025 </li><li> Khanderaya is an Avatar of Lord Shiva </li><li> He with Parvati avatar Mhalsa destroyed demons Malla and Mani </li><li> A big Temple at Jezuri Maharashtra </li><li> Turmeric 'Bhandara' is of great significance </li><li> Original pencil sketch, enhanced using charcoal, completed March 27, Uploaded March 28 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft', contentOther: 'Mix of color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '03-28-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 6 March 27-28 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-6-Mar27-28-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 6 March 27-28 2025 </li><li> Base template copied from B&W </li><li> 6th of 8 Ganesh with musical instruments Completion 27th, upload March 28 2025 Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'soft', contentOther: 'Mix of color pencils, watercolor pencils, charcoals, metal color pencils and shading',
dateUploaded:  '03-25-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 5 March 25 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-5-Mar25-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 5 March 25 2025 </li><li>  Colored Sangeet Ashtavinayaks 4 March 11 2025 5th of 8 Ganesh with musical instruments   </li><li> Base template copied from B&W   </li><li> Completion and upload March 25 2025 Using color pencil, charcoal pencil, metal color pencil  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'other',
contentOther: 'Mix of color pencils, watercolor pencils, charcoals, metal color pencils and shading',  
dateUploaded:  '03-18-2025',
duplicate:  'false',
summaryLabel:  `Dessert of darbari daawat: A drink of Badshah(') s 03/16-03/18/25`,
fullFileName: `${this.imageRoot}Falooda-March-16-18-2025.jpeg`,
description: `<ul><li> Dessert of darbari daawat: A drink of Badshah(') s 03/16-03/18/25 </li><li> "A (Delhi ) darbari daawat has to end with the drink of Badshah(') s " </li><li> The above is a sort of Pun, but first - the picture compositionn: </li><li> Falooda a rich and sumptious desset - ice cream, milk, rose syrup, sweetened vermiccelli, pearls, garnish with dry fruits </li><li> 'Paan' Betel leaves in the background </li><li> OK - the pun - Badshah(')s is a cold drink house in Central Mumbai </li><li> And Delhi Darbar is a famous Moghlai Restaurant nearby  </li><li> Used all color material, shading pencils and (of course) charcoal except crayons </li><li> completed March 16, upload March 18 2025</li></ul>`,
},
{

  canvassMaterial:  'Plain paper',
  canvassSize:  'A4',
  content:  'other',
  contentOther: `Mix of all drawing 'utensils' used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading`,  
  
dateUploaded:  '03-16-2025',
duplicate:  'false',
evolution:  `<b>550th sketch and a sort of uncategorized (as yet) sketch<br/>Also uses ALL coloring and B&W tools - black and white, Shading, color pencils, crayons (a bit), watercolor pencils, metallic pencils, and charcoal</B>`,
evolutionSequence:  4,
evolutionDate:  '03-16-2025',
summaryLabel:  `(#550) Combined Holi Drawing and Art Teacher Rodricks Sir Tribure March13- 16 '25`,
fullFileName: `${this.imageRoot}Holi-And-Rodricks-Sir-Tribute-March13-16-2025.jpeg`,
description: `<ul><li> (#550) Combined Holi Drawing and Art Teacher Rodricks Sir Tribure March13- 16 '25 </li><li> The idea came to draw something different to signify a splash of colors for Holi </li><li> One thing evolved into another, and one major lapse of not acknowledging my Art Teacher at School </li><li> Mr Rodricks who retired when I was in mid school - I was a sort of favorite of his </li><li> This is a still life, object drawing with sunflowers and a few other types in all the flowers which Sir taught us </li><li> Also I thought the card would be a nice way to express tribute, with Sir's name inside </li><li> Completed Mar 13, uploaded Mar 16 2025 </li><li> Timed to be the 550th sketch </li><li>Also uses ALL coloring and B&W tools I've used since THIS journey started - black and white, Shading, color pencils, crayons (a bit), watercolor pencils, metallic pencils, and charcoal</li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  '03-11-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 4 March 11 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-4-Mar11-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 4 March 11 2025 </li><li> 4th of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 11 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '03-11-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 3 March 11 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-3-Mar11-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 3 March 11 2025 </li><li> 3rd of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 11 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  '03-10-2025',
duplicate:  'false',
summaryLabel:  `Hookah  March10 2025 `,
fullFileName: `${this.imageRoot}Hookah-Charcoal-March10-2025.jpeg`,
description: `<ul><li> Hookah,  March10 2025  </li><li>Start, complete, upload March 10 2025 (pm)</li><li> Trying ambitious - earthenware, metal, cloth shading</li><li>Also tried wet cloth and water droplets around the metal water container (lower part/base)</li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '03-10-2025',
duplicate:  'false',
summaryLabel:  `Baba on Stone famous pose March 10 2025`,
fullFileName: `${this.imageRoot}Baba-March10-for-Feb20-2025.jpeg`,
description: `<ul><li> Baba on Stone famous pose March 10 2025 </li><li> Upload same day. From an old sketch </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '03-07-2025',
duplicate:  'false',
summaryLabel:  `Dhow with 'Mumbai Bandstand' backdrop March 7 2025`,
fullFileName: `${this.imageRoot}Dhow-Bandstand-March7-2025.jpeg`,
description: `<ul><li> Dhow with 'Mumbai Bandstand' backdrop March 7 2025 </li><li> Uploaded same day (March 7) </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  '03-07-2025',
duplicate:  'false',
summaryLabel:  `Baba 'Unplugged' face March 6 2025  `,
fullFileName: `${this.imageRoot}Baba-Charcoal-March-6-2025.jpeg`,
description: `<ul><li> Baba 'Unplugged' face March 6 2025   </li><li> Uploaded March 7  </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  '03-04-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 2 March 4 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-2-Mar4-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 2 March 4 2025 </li><li> 2nd of 8 Ganesh with musical instruments - Tanpura </li><li> Base template copied from B&W </li><li> Completion and upload March 4 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color pencil, charcoal pencil, metal color pencil',
dateUploaded:  '03-04-2025',
duplicate:  'false',
summaryLabel:  `Colored Sangeet Ashtavinayaks 1 March 4 2025`,
fullFileName: `${this.imageRoot}Sur-Niragas-Ho-Template-1-Mar4-2025.jpeg`,
description: `<ul><li> Colored Sangeet Ashtavinayaks 1 March 4 2025 </li><li> 1st of 8 Ganesh with musical instruments </li><li> Base template copied from B&W </li><li> Completion and upload March 4 2025 </li><li> Using color pencil, charcoal pencil, metal color pencil </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  '03-04-2025',
duplicate:  'false',
evolution:  `<b>First charcoal sketch <br/></B>`,
evolutionSequence:  5,
evolutionDate:  '03-04-2025',
summaryLabel:  `Ganesh using Charcoal pencils March 3 2025`,
fullFileName: `${this.imageRoot}Ganesh-Charcoal-March-3-2025.jpeg`,
description: `<ul><li> Ganesh using Charcoal pencils March 3 2025 </li><li> Using Kalour Hard, Medium and Soft black, and white charcoal pencils </li><li> These pencils were gifted by my wife long back and I finally got down to using them  </li><li> Uploaded March 4 2025 </li></ul>`,
},
  ]}]}
