 import {  ImageElement } from '@settings-and-models/image-detail'
// /Users/Shantanu/Documents/GitHub/cms-sources/journey-of-drawings/src/${this.imageRoot}Ganesh-1-March1723.jpeg
export class Changers2025ImageList {
 sort: string = 'asc'
 imageRoot=`assets/gallery-files/images/religion/aumkar-shree-ganesh/gte-q1-2024/` ;
public allImageList:ImageElement[]  =  [
   { 
        folder:'shree-ganesh-gte-q1-2024',
        theme:'Shree Ganesh',
        themeSummary:
        `Lord Ganesh, remover of Obstacles. Vigneshwar, Aumkar, Gamapati, Vignahartha - Compilation of sketches Q1 2024 onward. *INCLUDING WATER COLOR SKETCHES`,
        files: [
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  '',
dateUploaded:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>Comemorating fresh Parayan of Unabridged Sai SatCharit Thu June 26<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Sai Satcharit Chapt1 June 26-27 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/BabaSatCharit1NewParayanJun262025.jpeg`,
description: `<b>Comemorating fresh Parayan of Unabridged Sai SatCharit Thu June 26<br/></B><ul><li> Sai Satcharit Chapt1 June 26-27 2025 </li><li> Sai Satcharit Chapt1 .. Hemadpant who (physically) wrote the script pays obeisance to Shree Ganesh, Maa Saraswati, and the 'Guru' which I depict as Lord Datta, then the main story of Baba grinding wheat to keep away the cholera epidemic </li><li> A collage from previous drawings..  </li><li> Compiled June 26 late evening, uploaded just post midnight June 27 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'soft',
dateUploaded:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>A first with the Deity combination<br/>The 1st upload using one click add to 'Most Recent  Uploads' and 'Changers' (2025)<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Thu Jun 26 2025 23:24:18 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Ganesh Shiv Hanuman, June 24-26 2025 `,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/GaneshShivHanumanJune24-26-2025.jpeg`,
description: `<b>A first with the Deity combination<br/>The 1st upload using one click add to 'Most Recent  Uploads' and 'Changers' (2025)<br/></B><ul><li> Ganesh Shiv Hanuman, June 24-26 2025  </li><li> Towards the end of the Jyesth Lunar Month </li><li> Showing Ganesh ji doing milk Abhishek to Shivling and Hanuman ji waiting for His turn </li><li> Showing a 'not waste' concept of the milk being collected from the Shivling </li><li> Completed June 24, uploaded June 26 2025 </li></ul>`,
},
         
            {"canvassMaterial":"Plain paper","canvassSize":"A4","content":"color-pencil","dateUploaded":"01-18-2025","duplicate": "true","evolution":"<b>first super speeder exotic<br/></B>","evolutionSequence":5,"evolutionDate":"01-18-2025","summaryLabel":"Koenigsegg Agera RS (Jan-17 2025) sky blue","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Koenigsegg-Agera-RS-Jan-17-2025.jpeg","description":"<b>first super speeder exotic<br/></B> <ul><li> Koenigsegg Agera RS (Jan-17 2025) sky blue </li><li> One of the fastest street legal cars, this Hyper exotic rubs shoulders with Buggati, Ferrari, Lamborgini, Saleen and others </li><li> Uploaded Jan 18 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"watercolor-pencil","album":{"name":"the-divine-in-colors-so-fine","status":"added","sequence":2},"dateUploaded":"02-10-2025","duplicate": "true","summaryLabel":"Vasant Panchami 2025 Saraswati Devi","evolution":"- <b>Introducing concept of albums - the 1st of a set of sketches whose online grouping and album grouping are differnt</b><br/>","evolutionDate":"02-10-2025","evolutionSequence":3,"fullFileName":"assets/gallery-files/images/religion/devi/MaaSaraswati-Feb2-10-VasantPanchami2025.jpeg","description":"- <b>Introducing concept of albums - the 1st of a set of sketches whose online grouping and album grouping are differnt</b><br/> <ul><li> Vasant Panchami 2025 Saraswati Devi </li><li> Based off an earlier template (Dassera 2024) </li><li> (This was based on sculputure at Fine Arts College Davanegere, Karnataka) </li><li> Actually a combination of watercolor pencils and regular pencils </li><li> Resumed an old pending drawing one version for Feb 2 2025 </li><li> Final upload Feb 10 2025 </li></ul>","rating":1,"ratingYear":2025}
,{"canvassMaterial":"other","canvassSize":"A4","content":"soft","dateUploaded":"02-13-2025","duplicate": "true","evolution":"<b>print out of an original hard copy and a processed soft copy next to each other<br/></B>","evolutionSequence":4,"evolutionDate":"02-13-2025","summaryLabel":"Ganesh Reverse Color(3) Original & Processed Feb06-2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-Reverse-Shade-Orig+ProcessedFeb06-2025.jpeg","description":"<b>print out of an original hard copy and a processed soft copy next to each other<br/></B> <ul><li> Ganesh Reverse Color(3) Original & Processed Feb06-2025 </li><li> Felt it best to 'collage' the original and processed </li><li> This goes a little tangential in this list by placing two separate images next to each other. But felt the need to </li><li> uploaded Feb 13 2025 </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"A4","content":"soft","dateUploaded":"02-13-2025","duplicate": "true","evolution":"<b>Reverse color processed. Unique where this image is not a collage but actually processed. Also a print out of a soft copy <br/></B>","evolutionSequence":4,"evolutionDate":"02-13-2025","summaryLabel":"Ganesh Reverse color (2) Processed Green Feb 6 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-Reverse-Shade-Processed-Green-Feb06-2025.jpeg","description":"<b>Reverse color processed. Unique where this image is not a collage but actually processed. Also a print out of a soft copy <br/></B> <ul><li> Ganesh Reverse color (2) Processed Green Feb 6 2025 </li><li> See 'Ganesh Reverse color (1) Red Feb 6 2025'  </li><li> This is the same image, run through an image processing tool to invert the colors </li><li> Uploaded Feb 13 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"","content":"color-pencil","dateUploaded":"02-13-2025","duplicate": "true","evolution":"<b>The description says it all. (See the next = before or after sketch also)<br/></B>","evolutionSequence":4,"evolutionDate":"02-13-2025","summaryLabel":"Ganesh Reverse color (1) Red Feb 6 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-Reverse-Shade-Red-Feb06-2025.jpeg","description":"<b>The description says it all. (See the next = before or after sketch also)<br/></B> <ul><li> Ganesh Reverse color (1) Red Feb 6 2025 </li><li> Tried to create a 'negative print' effect here </li><li> normal bright areas are shaded dark and, normally dark areas are not colored or shaded light </li><li> Next (either after or before) is this image processed to reverse the colors </li></ul>","rating":1,"ratingYear":2025}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"color-pencil","dateUploaded":"02-17-2025","duplicate": "true","evolution":"<b>first metal color drawing<br/></B>","evolutionSequence":4,"evolutionDate":"02-17-2025","summaryLabel":"Ganesh Metal Gold color pencil Feb 17 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Ganesh-metal-gold-pencil-Feb17-2025.jpeg","description":"<b>first metal color drawing<br/></B> <ul><li> Ganesh Metal Gold color pencil Feb 17 2025 </li><li> Using 'Kalour' metal pencil Gold shade </li><li> based on a Brass Ganesh Idol I've had since engineering days </li><li> Upload feb 17 itself </li></ul>","rating":1,"ratingYear":2025}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","dateUploaded":"03-04-2025","duplicate": "true","evolution":"<b>First charcoal sketch <br/></B>","evolutionSequence":5,"evolutionDate":"03-04-2025","summaryLabel":"Ganesh using Charcoal pencils March 3 2025","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Ganesh-Charcoal-March-3-2025.jpeg","description":"<b>First charcoal sketch <br/></B> <ul><li> Ganesh using Charcoal pencils March 3 2025 </li><li> Using Kalour Hard, Medium and Soft black, and white charcoal pencils </li><li> These pencils were gifted by my wife long back and I finally got down to using them  </li><li> Uploaded March 4 2025 </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"other","contentOther":"Mix of all drawing 'utensils' used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"03-16-2025","duplicate": "true","evolution":"<b>550th sketch and a sort of uncategorized (as yet) sketch<br/>Also uses ALL coloring and B&W tools - black and white, Shading, color pencils, crayons (a bit), watercolor pencils, metallic pencils, and charcoal</B>","evolutionSequence":4,"evolutionDate":"03-16-2025","summaryLabel":"(#550) Combined Holi Drawing and Art Teacher Rodricks Sir Tribure March13- 16 '25","fullFileName":"assets/gallery-files/images/special-lists/alag-grouping-full-cycle/charcoal-times-other-colors-shines/Holi-And-Rodricks-Sir-Tribute-March13-16-2025.jpeg","description":"<b>550th sketch and a sort of uncategorized (as yet) sketch<br/>Also uses ALL coloring and B&W tools - black and white, Shading, color pencils, crayons (a bit), watercolor pencils, metallic pencils, and charcoal</B> <ul><li> (#550) Combined Holi Drawing and Art Teacher Rodricks Sir Tribure March13- 16 '25 </li><li> The idea came to draw something different to signify a splash of colors for Holi </li><li> One thing evolved into another, and one major lapse of not acknowledging my Art Teacher at School </li><li> Mr Rodricks who retired when I was in mid school - I was a sort of favorite of his </li><li> This is a still life, object drawing with sunflowers and a few other types in all the flowers which Sir taught us </li><li> Also I thought the card would be a nice way to express tribute, with Sir's name inside </li><li> Completed Mar 13, uploaded Mar 16 2025 </li><li> Timed to be the 550th sketch </li><li>Also uses ALL coloring and B&W tools I've used since THIS journey started - black and white, Shading, color pencils, crayons (a bit), watercolor pencils, metallic pencils, and charcoal</li></ul>"}
,{"canvassMaterial":"other","canvassSize":"other","content":"soft","contentOther":"Template based Software edit AND Mix of all drawing \"utensils\" used so far - crayons, color pencils, watercolor pencils, charcoals, metal color pencils and shading","dateUploaded":"03-28-2025","duplicate": "true","evolution":"<b>sort of first attempt to do an eCard<br/></B>","evolutionSequence":4,"evolutionDate":"03-28-2025","summaryLabel":"Blank Template March 24 - 28 2025","fullFileName":"assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Generic-Thanks-card-032425.jpeg","description":"<b>sort of first attempt to do an eCard<br/></B> <ul><li> Blank Template March 24 - 28 2025 </li></ul>"}
,{"canvassMaterial":"other","canvassSize":"","content":"soft","contentOther":"Collage","dateUploaded":"04-18-2025","duplicate": "true","evolution":"<b>1st time - soft copy for Baba thursday<br/></B>","evolutionSequence":4,"evolutionDate":"04-18-2025","summaryLabel":"Ganesh Swami Datta Sai Apr 17-18 2025","fullFileName":"assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/GaneshSwamiDattaSai-April172025.jpeg","description":"<b>1st time - soft copy for Baba thursday<br/></B> <ul><li> Ganesh Swami Datta Sai Apr 17-18 2025 </li><li> Since, probably Feb 2021, I've been posting one Baba drawing every Thursday.  This will continue, in general, but it may not be on the Thursday - I'll keep the regularity  The 2nd and more significantly, I am shifting focus on creating more soft copy shares, like this collage.  Partly because I am getting a heap of Baba sketches and finding it difficult to catch up on storing them decently </li></ul>"}
,{"canvassMaterial":"Plain paper","canvassSize":"A4","content":"black-white","contentOther":"charcoal and shading","dateUploaded":"06-01-2025 11:00","album":{"name":"the-third-album","status":"added","sequence":34},"duplicate": "true","evolution":"<b>The first A3 Charcoal sketch. .. Also inserted a copy in 'Charcoal Times Other Colors Shines'<br/></B>","evolutionSequence":5,"evolutionDate":"06-01-2025","summaryLabel":"Hanuman A3 Charcoal May 31, upload June 1, 2025","fullFileName":"assets/gallery-files/images/religion/laxmi-vishnu-hanuman/HanumanMay31-2025.jpeg","description":"<b>The first A3 Charcoal sketch. .. Also inserted a copy in 'Charcoal Times Other Colors Shines'<br/></B> <ul><li> CHANGER: The first A3 Charcoal sketch. .. Also inserted a copy in 'Charcoal Times Other Colors Shines' </li></ul>"}

                   ]
   }
]
}
/*

*/
