
import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class ShirdiSaiQ42025Q22026ImageList {
imageRoot = 'assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q4-2025-q2-2026/'; reverseStack =  'false';
public allImageList:ImageElement[]  =  [
  {  
            folder:'shirdi-sai-q4-2025-q2-2026',
            theme:'<theme>',
            themeSummary: '', 
files: [
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Thu Jun 25 2026 08:04:48 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Navagraha Gold Pencil June 25 2026`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/Baba-Navagraha-June25-2026-shades-other-colors.jpeg`,
description: `<ul><li> Baba Navagraha Gold Pencil June 25 2026 </li><li> Showing Baba wth representation of Navagraha </li><li> Surya, Chandra, Mangal (Mars), Budh (Mercury), </li><li> Guru (Jupiter), Shukra (venus),  </li><li> Shani(Saturn), Rahu, Ketu (symbols) </li><li> अनंत कोटी ब्रह्मानंद नायक योगीराज सद्गुरू साई समर्थ महाराज कि जय  </li><li> Gold metallic color pencil </li><li> complete and upload june 25 2026 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-crayon',
dateUploaded:  'Thu May 14 2026 15:15:08 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false', album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 36} ,
summaryLabel:  `Dwarkamai Template frm May 7 - May 14 2026`,
fullFileName: `${this.imageRoot}BabaDwarkaMai-Template-May142026.jpeg`,
description: `<ul><li> Dwarkamai Template frm May 7 - May 14 2026 </li><li> Baba Dwarkamai  </li><li> Template of previous May 7 - completed and  uploaded May 12 2026 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'black-white',
dateUploaded:  'Thu May 14 2026 15:22:53 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Baba Dwarkamai May 7 - 14 2026 Long gap`,
fullFileName: `${this.imageRoot}BabaDwarkamaiMay72026.jpeg`,
description: `<ul><li> Baba Dwarkamai May 7 - 14 2026 Long gap </li><li> A 'from scratch and completion during Kakad' Baba drawing after a long time </li><li> Completed May 7, Uploaded May 14 2026 </li></ul>`,
},
{
canvassMaterial:  'Photo print matt paper',
canvassSize:  '',
content:  'watercolor-pencil',
dateUploaded:  'Sun Apr 26 2026 22:19:44 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 34} ,
summaryLabel:  `Baba Water Colors Apr2- 26 2026 `,
fullFileName: `${this.imageRoot}Baba-WC-Apr2-26-Divine-34.jpeg`,
description: `<ul><li> Baba Water Colors Apr2- 26 2026  </li><li> Completed April2. Upload Apr 26 2026 </li></ul>`,
},
{
canvassMaterial:  'Photo print matt paper',
canvassSize:  'A4',
content:  'watercolor-pencil',
dateUploaded:  'Sun Apr 26 2026 15:48:36 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 31} ,
summaryLabel:  `Baba-Swami-Nov6-25- Upload 4/26/2026`,
fullFileName: `${this.imageRoot}Baba-Swami-Nov6-25-Divine-31.jpeg`,
description: `<ul><li> Baba-Swami-Nov6-25- Upload 4/26/2026 </li><li> Baba with Swami Silhouette </li><li> Watercolor pencils completed Nov 6 2025 </li><li> upload April 26 2026 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  '',
dateUploaded:  'Mon Feb 02 2026 07:04:45 GMT-0800 (Pacific Standard Time)',
duplicate:  'true',
summaryLabel:  `Jan 22 (Ganesh Jayanti)- Feb 2 2026(Gurupratipada) upload`,
fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/Ganesh-Jayanti-Baba-Thu-Jan22-2026.jpeg`,
description: `<ul><li> Jan 22 (Ganesh Jayanti)- Feb 2 2026(Gurupratipada) upload </li><li> soft copy merge of Sai with Ganapati </li><li> Publish after long time...  </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Wed Oct 22 2025 10:54:37 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba lighting lamps (2) Diwali 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Baba-Diwali-Oct21-22-2025.jpeg`,
description: `<ul><li> Baba lighting lamps (2) Diwali 2025 </li><li> Compiled using merge of another of my drawings with ChatGPT </li><li> Compiled Oct 21 upload Oct 22 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Thu Oct 16 2025 10:39:13 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Samadhi Anniv (Gregorian) Oct 15 2025 (1918) -> Oct 16 `,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/Baba-Samadhi-Gregorian-for-Oct15-2025.jpeg`,
description: `<ul><li> Baba Samadhi Anniv (Gregorian) Oct 15 2025 (1918) -> Oct 16  </li><li> Sai took Samadhi on Dassera Day 1918 which was Oct 15, Tuesday </li><li> Uploaded Oct 16 2025 </li></ul>`,
},
  {
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '10-02-2025',
duplicate:  'false',
summaryLabel:  `Baba Dassera 2025 - Oct 1- 2 2025`,

album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 23} ,
fullFileName: `${this.imageRoot}Baba-Dassera-Oct1-Oct2-2025.jpeg`,
description: `<ul><li> Special sketch for Baba Samadhi using metallic and othe color pencils</li><li> Uploaded Oct 2 2025 </li></ul>`,
},
  ]}]}
