
import {  ImageElement } from '@settings-and-models/image-detail'
enum PicsIndex  {
        aumkarGaneshSept2020Final,
        AumGaShivParKashiVishwCTLightNov172020Final,
        unsignedShivVeena12272020,
        ShreeSiddhivinayakQ42020,
        DeviMaaMay13182021,
        MixGenPlaneSept2020,
    };
export class ShirdiSaiQ2Q32025ImageList {
imageRoot = 'assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/'; reverseStack =  'false';
public allImageList:ImageElement[]  =  [
  {  
    // /Users/shantanug/Documents/GitHub/cms-code/customized-cms/cms-main/src/assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025
            folder:'assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/',
            theme:'<theme>',
            themeSummary: '',
files: [
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  'soft',
dateUploaded:  'Fri Jul 25 2025 10:41:07 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Samadhi to Masjid July 24-25 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/BabaSamadhiToMAshidJuly242025.jpeg`,
description: `<ul><li> Baba Samadhi to Masjid July 24-25 2025 </li><li> Collage of two paper sketches (unless requested) soft copy only </li><li> "समाधि उथ्रोनिया गुरु चला मशीदी कड़े " Part of Baba Kakad arti line - come from Samadhi and go to the Masjid (Dwarkamai) </li><li> compiled July 24, upload July 25, 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A3',
content:  '',
dateUploaded:  'Mon Jul 14 2025 06:48:15 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Gurupoornima 2025 Samadhi Mandir`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/Baba-Gurupoornima-11x17-A4-july10-25.jpeg`,
description: `<ul><li> Baba Gurupoornima 2025 Samadhi Mandir </li><li> Completed a previous unfinished sketch </li><li> Gurupoornima was Thu July 10 2025 </li><li> (Changers 2025 qualifier) to add to the physical album 'The Divine in colors so fine' an A4 copy was made  </li><li> another ground breaker.. allow multiple physical albums if the original list is only a soft copy list like this one </li><li> Uploaded July 14 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A3',
content:  '',
dateUploaded:  'Mon Jul 14 2025 06:48:15 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Baba Gurupoornima 2025 Samadhi Mandir`,album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 22} ,
albums: [  
           { name: 'the-third-album', status: 'added', sequence: 35}
],
fullFileName: `${this.imageRoot}Baba-Gurupoornima-11x17-A4-july10-25.jpeg`,
description: `<ul><li> Baba Gurupoornima 2025 Samadhi Mandir </li><li> Completed a previous unfinished sketch </li><li> Gurupoornima was Thu July 10 2025 </li><li> (Changers 2025 qualifier) to add to the physical album 'The Divine in colors so fine' an A4 copy was made  </li><li> another ground breaker.. allow multiple physical albums if the original list is only a soft copy list like this one </li><li> Uploaded July 14 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  'Sun Jul 13 2025 15:26:54 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
summaryLabel:  `Baba Vari July 3, 13 2025`,
fullFileName: `assets/gallery-files/images/religion/shirdi-sai/shirdi-sai-q2-q3-2025/Baba-Vari-July3-2025.jpeg`,
description: `<ul><li> Baba Vari July 3, 13 2025 </li><li> Ashadi Ekadahi being July 6 this year, Varis(Sacred Pilgrimages) leave from different parts of Maharashtra to end at Pandharpur before this date  </li><li> Symbolic of Baba carrying the 'Bhagwa' flag and Vithal Rakhumabai in the top left minature </li><li> Completed July 3, uploaded July 13 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  'Sun Jul 13 2025 15:26:54 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Baba Vari July 3, 13 2025`,
fullFileName: `${this.imageRoot}Baba-Vari-July3-2025.jpeg`,
description: `<ul><li> Baba Vari July 3, 13 2025 </li><li> Ashadi Ekadahi being July 6 this year, Varis(Sacred Pilgrimages) leave from different parts of Maharashtra to end at Pandharpur before this date  </li><li> Symbolic of Baba carrying the 'Bhagwa' flag and Vithal Rakhumabai in the top left minature </li><li> Completed July 3, uploaded July 13 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  'soft',
content:  '',
dateUploaded:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
duplicate:  'true',
evolution:  `<b>Comemorating fresh Parayan of Unabridged Sai SatCharit Thu June 26<br/></B>`,
evolutionSequence:  4,
evolutionDate:  'Fri Jun 27 2025 00:25:43 GMT-0700 (Pacific Daylight Time)',
summaryLabel:  `Sai Satcharit Chapt1 June 26-27 2025`,
fullFileName: `assets/gallery-files/images/special-lists/soft-copies-and-compilations/soft-copies-and-compilations-1/BabaSatCharit1NewParayanJun262025.jpeg`,
description: `<ul><li> Sai Satcharit Chapt1 June 26-27 2025 </li><li> Sai Satcharit Chapt1 .. Hemadpant who (physically) wrote the script pays obeisance to Shree Ganesh, Maa Saraswati, and the 'Guru' which I depict as Lord Datta, then the main story of Baba grinding wheat to keep away the cholera epidemic </li><li> A collage from previous drawings..  </li><li> Compiled June 26 late evening, uploaded just post midnight June 27 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  'Sat Jun 14 2025 17:21:55 GMT-0700 (Pacific Daylight Time)',
duplicate:  'false',
summaryLabel:  `Baba June12 2025 - June 14 upload`,
fullFileName: `${this.imageRoot}BabaJune122025Complete.jpeg`,
description: `<ul><li> Baba June12 2025 - June 14 upload </li><li> Baba Shirdi Murthy Idol with  attempt of Milpitas throne backgrpund </li><li> Gray color pencil. Made decision of not to add to the special list since it wasnt up to the mark </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  'color-pencil',
dateUploaded:  '06-01-2025 18:25',
duplicate:  'true',
summaryLabel:  `Baba- Shivling Gray June1 2025 SIXHUNDREDTH`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-other-colors-1/BabaShivlingGrayJune12025-SIXHUNDREDTH.jpeg`,
description: `<ul><li> Baba- Shivling Gray June1 2025 SIXHUNDREDTH </li><li> Celebrating my 600th website uploaded sketch them my beloved Baba and Mahadev </li><li> June 1, 2025 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  '',
content:  'black-white',
dateUploaded:  '06-01-2025 10:00',
duplicate:  'true',
summaryLabel:  `Original Baba Samadhi Mandir -- final touch and upload June 1 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BabaSamadhiMandirJun12025.jpeg`,
description: `<ul><li> Original Baba Samadhi Mandir -- final touch and upload June 1 2025 </li><li> This is what the original Samadhi Mandir looked at Shirdi </li></ul>`,
},
{
canvassSize:  '',
content:  '',
dateUploaded:  '06-01-2025 09:50',
duplicate:  'true',
summaryLabel:  `Baba Sketch final touch and upload June 1 2025`,
fullFileName: `assets/gallery-files/images/special-lists/alag-grouping-full-cycle/shades-and-shines-1/BabaJun12025.jpeg`,
description: `<ul><li> Baba Sketch final touch and upload June 1 2025 </li></ul>`,
},
{
canvassMaterial:  'Watercolor paper',
canvassSize:  'A4',
content:  'soft',
dateUploaded:  '05-27-2025',
duplicate:  'false',
summaryLabel:  `Baba - May 29 2025`,album: { name: 'the-divine-in-colors-so-fine', status: 'added', sequence: 14} ,
fullFileName: `${this.imageRoot}BabaMay28-2025.jpeg`,
description: `<ul><li> Baba - May 29 2025 </li><li> Sketch started May 1st week, final touches and upload May 29 </li></ul>`,
},
{
canvassMaterial:  'Plain paper',
canvassSize:  'A4',
content:  '',
dateUploaded:  '04-30-2025',
duplicate:  'false',
summaryLabel:  `Baba For Ram Navmi April 5, ---> 30 2025`,
fullFileName: `${this.imageRoot}BabaRamNavmiApril5-10-29-30-2025.jpeg`,
description: `<ul><li> Baba For Ram Navmi April 5, ---> 30 2025 </li><li> Milpitas Temple celebrates Ramnavmi in a grand fashion </li><li> Palki procession and devotees hand prints in sandalwood </li><li> Dates: Ramnavmi was April 5, Sketch was for April 10  </li><li> final touches April 29, upload April 30 2025 </li></ul>`,
},
{
canvassMaterial:  'other',
canvassSize:  '',
content:  'soft',contentOther: 'Collage',
dateUploaded:  '04-18-2025',
duplicate:  'true',
evolution:  `<b>1st time - soft copy for Baba thursday<br/></B>`,
evolutionSequence:  4,
evolutionDate:  '04-18-2025',
summaryLabel:  `Ganesh Swami Datta Sai Apr 17-18 2025`,
fullFileName: `assets/gallery-files/images/religion/aumkar-shree-ganesh/ganesh-gte-11-2024/GaneshSwamiDattaSai-April172025.jpeg`,
description: `<ul><li>स्वामी स्नेही शिर्डी साई </li><li> श्रद्धा सबुरी द्वारकामाई </li><li>करा गुरुस्मरण</li><li>होता  गुरुशरण</li><li> माथी  ठेवी गुरुचरण</li><li>मुखी मनात सदा  गुरुनामन </li><li>स्वामी प्रचंड बाळ पाठीशी हो</li><li>  स्वामी साई दत्त भक्ती निरागस हो</li><li> Ganesh Swami Datta Sai Apr 17-18 2025 </li><li> Since, probably Feb 2021, I've been posting one Baba drawing every Thursday.  This will continue, in general, but it may not be on the Thursday - I'll keep the regularity  The 2nd and more significantly, I am shifting focus on creating more soft copy shares, like this collage.  Partly because I am getting a heap of Baba sketches and finding it difficult to catch up on storing them decently </li></ul>`,
},
  ]}]}
